### ISSUE TITLE
How to check data exiting or not ? 

### ISSUE THREAD

**Issue by siamraj** [TryGhost/node-sqlite3#1001]
` 

     db.each('SELECT * FROM <TableName> WHERE Email = "EmailID"', function (err, result) {
           if (err) {
                  callback(err)
            } else {
                   callback(null, result)
            }
    });
`

There is no exiting email id. That time Does't throw Error. My question is  How I can check one value exiting or not ?

**Comment by timoch** [comment]
Use the completed callback and check that your row callback has never been called

	let hasAnyRow = false;
	db.each(
		'SELECT * FROM <TableName> WHERE Email = "EmailID"', 
		function (err, result) {
			if (err) {
				callback(err)
			} else {
				hasAnyRow = true;
				callback(null, result)
			} 
		}, 
		function(err) {
			// if hasAnyRow is false, no row was processed
		}
	);
