### ISSUE TITLE
db got deleted after a massive slowdown

### ISSUE THREAD

**Issue by yassinevic** [TryGhost/node-sqlite3#1017]
Hello.
I have a weird behavior with this module.
This is a the second time my db got deleted after a massive slowdown of the app.
anyone suffered from this ?

**Comment by springmeyer** [comment]
Can you provide a testcase that replicates?

**Comment by yassinevic** [comment]
unfortunately no.
it's sames to be random. but I suposed it's because the app (nw.js) slowsdown and I have to kill it in the middel of some processing.
that's why I asked if anyone is facing the same issue.
