### ISSUE TITLE
use pre-binding at runtime instead of node-pre-gyp

### ISSUE THREAD

**Issue by arolson101** [TryGhost/node-sqlite3#1022]
Could you switch the runtime dependency to use https://github.com/zertosh/pre-binding instead of node-pre-gyp?  You only use it for the loading and it introduces a large dependency tree.

**Comment by noonhorse** [comment]
@springmeyer , i still hava the "node-pre-gyp install --fallback-to-build" problem。can you think to use pre-binding instead of node-pre-gyp ?
