### ISSUE TITLE
Is PRAGMA defer_foreign_keys supported in sqlcipher?

### ISSUE THREAD

**Issue by deepak342** [TryGhost/node-sqlite3#1023]
I have a transaction with a couple of INSERT OR REPLACE statements that throws a foreign key error. I tried the statements by turning defer_foreign_keys=ON for the transaction and it worked in sqlcipher console / DBBrowser. But it is not working from my code.

Is PRAGMA defer_foreign_keys supported in sqlcipher or am I missing something?

**Comment by deepak342** [comment]
Is it supported?

**Comment by jayapal92** [comment]
I have a transaction with a couple of INSERT OR REPLACE statements that throws a foreign key error. I tried the statements by turning defer_foreign_keys=ON for the transaction and it worked in sqlcipher console / DBBrowser. But it is not working from my code.

Is PRAGMA defer_foreign_keys supported in sqlcipher or am I missing something?


I am also facing the same issue

any update ? Please Fix it.

**Comment by daniellockyer** [comment]
I think this question is more suited for the sqlcipher team - please ask there 🙂
