### ISSUE TITLE
install when there is no internet access in ci build

### ISSUE THREAD

**Issue by dagda1** [TryGhost/node-sqlite3#1030]
I am using sqlite3 but I have a problem when it comes to our continuous integration jenkins build.

It tries to download sqlite but cannot because the ci has no internet access.

Is there any way I can tell sqlite to access our nexus and not go to the internet.

We do something similar with node-sass by setting an environment variable.

Can we do something similar with sqlite3?

**Comment by daniellockyer** [comment]
You should be able to [compile from source](https://github.com/TryGhost/node-sqlite3#source-install) 🙂
