### ISSUE TITLE
Application exits (crash) without catchable errors/signals on database connection close

### ISSUE THREAD

**Issue by niclasek** [TryGhost/node-sqlite3#1038]
The error seems to occur with connection.close and connection.run executed close to each other when the run call is in a setInterval/setTimeout or other callbacks. This is a huge problem about the library stability. It's mandatory to have a catchable errors and not a whole application crash.

See the index.js sample file (rename from .js.txt to .js).
Run it with simple command "node index.js". Try to run several times.

[index.js.txt](https://github.com/mapbox/node-sqlite3/files/2370517/index.js.txt)

**Comment by daniellockyer** [comment]
@niclasek Would you be able to try with the latest version? I can't reproduce this with your file 🙂
