### ISSUE TITLE
SQLITE_BUSY: database is locked

### ISSUE THREAD

**Issue by zhangxy1035** [TryGhost/node-sqlite3#1039]
when i use node-sqlite3,always error SQLITE_BUSY: database is locked,how can i fix it?

**Comment by gms1** [comment]
you may want to increase the busy timout
e.g
PRAGMA busy_timeout = 6000

**Comment by zhangxy1035** [comment]
I've never used PRAGMA ,now i get it ,thanks a lot

**Comment by javierpal** [comment]
```
  let db = new sqlite3.Database(dbName);
  db.run('PRAGMA busy_timeout = 6000');
  db.configure("busyTimeout", 6000);
```
i did this 2 but still i'm having this error

**Comment by daniellockyer** [comment]
Closing as the issue is stale but I'm not seeing this elsewhere so I presume it's a problem with your setup, unless you can provide a reproducible test case 🙂
