### ISSUE TITLE
Syntax error on window function OVER() clause

### ISSUE THREAD

**Issue by sm-Fifteen** [TryGhost/node-sqlite3#1047]
I had a prepared statement that would keep crashing my program when I tried running it due to a reported syntax error, even though running it through command-line sqlite seemed to work just fine. Upon further inspection, it would seem that node-sqlite3 is the source of the issue.

I've managed to narrow down the issue into easy to reproduce test statements :

##### Syntax error due to `OVER ()` clause
```sql
SELECT SUM(column1) OVER () FROM (VALUES(8),(7),(6),(5),(4),(3),(2),(1));
```

```js
const sqlite3 = require('sqlite3');
(new sqlite3.Database(":memory:")).all("SELECT SUM(column1) OVER () FROM (VALUES(8),(7),(6),(5),(4),(3),(2),(1));", (err, rows) => {
		if(err) console.error(err);
		console.log(rows);
});
```

##### `OVER ()` clause removed, query runs as expected
```sql
SELECT SUM(column1) FROM (VALUES(8),(7),(6),(5),(4),(3),(2),(1));
```

```js
const sqlite3 = require('sqlite3');
(new sqlite3.Database(":memory:")).all("SELECT SUM(column1) FROM (VALUES(8),(7),(6),(5),(4),(3),(2),(1));", (err, rows) => {
		if(err) console.error(err);
		console.log(rows);
});
```

The SQL statements alone all run fine using the CLI interface for SQLite.

Platform: Linux (Arch Linux)
Node version : 10.11.0
NPM version :  6.4.1
node-sqlite version : `sqlite3@4.0.2`
`sqlite3.VERSION`: `3.24.0`
cli-sqlite version : ` 3.25.2 2018-09-25 19:08:10`

**Comment by sm-Fifteen** [comment]
The bug appears to have resolved itself after running `npm install sqlite3 --build-from-source --sqlite=/usr/lib`, so this might have more to do with the bundled libary version.

**Comment by nazar01** [comment]
Yes, window functions were added in sqlite 3.25 
https://www.sqlite.org/releaselog/3_25_0.html

**Comment by daniellockyer** [comment]
v5.0.3 now ships with SQLite v3.38.2 so this should no longer be a problem 🙂
