### ISSUE TITLE
db.close() callback never called

### ISSUE THREAD

**Issue by rico345100** [TryGhost/node-sqlite3#1060]
```javascript
/* @flow */
const sqlite3 = require('sqlite3').verbose();
const dbPath = './db/user.db';
const db = new sqlite3.Database(dbPath, sqlite3.OPEN_READWRITE | sqlite3.OPEN_CREATE, () => {
    console.log('SQLite connected!');

    db.close((err) => {
        if(err) {
            throw err;
        }

        console.log('DB Closed');

        setTimeout(() => {}, 2000);
    });
});
```

It's simple code, but callback function in db.close never called. Just application terminated right after connected to DB, even there are still some logics in there(Look at the setTimeout inside of callback function of db.close).

List of versions:
- Node@8.12.0
- SQLite@3.25.2
- sqlite3@4.0.2

**Comment by daniellockyer** [comment]
It seems this is only an issue when the dbPath is invalid (ie. it contains a directory that doesn't exist). In which case, I'm going to close this in favor of the more recent https://github.com/TryGhost/node-sqlite3/issues/1617
