### ISSUE TITLE
Update coverage

### ISSUE THREAD

**Issue by mapsam** [TryGhost/node-sqlite3#1061]
Coverage commands are failing with the following error:

```
./scripts/build_against_node.sh: line 20: cpp-coveralls: command not found
```

We should:

1. ✅ ~~[short term] rip this coverage out to avoid breaking tests~~ completed in #1062 
1. [long term] update to use codecov

cc @springmeyer

**Comment by springmeyer** [comment]
> [short term] rip this coverage out to avoid breaking tests

👍 

long term I've hoped to find time to forward port node-cpp-skel to node-sqlite, which would be a medium-size effort but would get codecov for free.

**Comment by mapsam** [comment]
PR for short-term solution over at #1062

**Comment by daniellockyer** [comment]
Closing this for now - but I will re-add coverage 🙂
