### ISSUE TITLE
node-sqlite3 hardcodes incorrect node abi into file path

### ISSUE THREAD

**Issue by mrcybermac** [TryGhost/node-sqlite3#1064]
This issue was discovered when trying to install a separate open source project called joplin which makes use of node-sqlite3:

https://github.com/laurent22/joplin/issues/886

I use 'node version manager' (nvm) to switch between versions of node. Though I might be using node v8, I will still have the latest version of npm installed.  Somehow when node-sqlite3 installs it hardcodes the wrong 'node abi' into the file path.  Here is what I get for the built node-sqlite3 path even though I have node v8 installed:

`sqlite3/lib/binding/node-v64-darwin-x64/node_sqlite3.node`

When I try to run the program however, it fails because it gets a 'node abi' of 'v57' from node v8 and fails to find the node-sqlite3 path.

We suspect that node-sqlite3 might be calculating the 'node abi' at install time from the npm version rather than the node version.  npm and node versions are not guaranteed to be correlated.

Here are some further thoughts from the original issue link:
https://github.com/laurent22/joplin/issues/886#issuecomment-432368668

All that being said, not sure why the sqlite3 install is hardcoding a file path to a specific version of node (or potentially the npm version actually). If you install joplin with brew using node/npm v8 then upgrade to v9 or v10 the installation just straight up breaks. ...The sqlite3 or joplin applications don't necessarily have any issues or errors at all with the higher version, but the installation itself just breaks due to hardcoded path. If sqlite3 is somehow dependent on a node version then it should probably be enforced when run in node rather than by a hardcoded/encoded file path in the installation. For example, sqlite3 could give an error saying, "This version of sqlite3 requires node version 10" or something like that. Just a thought.

Can node-sqlite3 be refactored to either compute the proper 'node abi' based on the actually node version, or else git rid of hardcoding the 'node abi' into the file path and relying on javascript for any needed errors/messaging about version compatibility?

**Comment by kewde** [comment]
The issue is that dependencies are downloaded at installation and not at runtime.
If you switch version of node, rerun the 'npm install' or 'yarn install'.

I think throwing an error when the version isn't found is probably the best way of dealing with it for now.

**Comment by tessus** [comment]
@kewde I'm sorry, but this is clearly a node-sqlite3 problem. So if somebody builds an app with node version X and somebody downloads the app and has node version Y installed, then what? Funny thing is that only node-sqlite3 seems to have this problem.
In the meantime there are a bunch of issues open that people can't run Joplin, because of this error. So what exactly do you suggest?

It would be great, if the owners of this project could shed some light on this.

**Comment by kewde** [comment]
@tessus 

The scenario you are presenting will not cause any issues.
The user with node version Y, when doing `npm install` will get the right version for Y.
However, when they then decide to use nvm to move to version Z, they will have to run `npm install` again.

**Comment by tessus** [comment]
Unfortunately I only understood half of what you wrote. I'm new to nodejs, react-native, and js.
I still haven't had the time to read up on these technologies and how they work together.

Thus it's rather unlikely that I will be able to create a PR.

However, it's rather inconvenient for the end user to run `npm install`. So how's the process supposed to work? People run `npm install joplin` and look where it is installed. Then they go to the base (install) directory and run `npm install`?

**Comment by kewde** [comment]
They should only have to run `npm install joplin`.
The problem should only arise when the user changes from node version (say v9 to v10). Then they should reinstall their directory.

This package provides bindings for the SQLite3 implementation in C. Usually there is a lot more inconvenience involved with using these type of native packages. Such as building the binary for multiple platforms.

What happened is, the binary was compiled for usage with a particular version of node (which you can also identify by the ABI version). This is done at the installation. When you change the version of node afterwards, the native dependency ABI doesn't match anymore and it won't find the binary.

What you wish to do is detect the arch, and abi on runtime. But generally the rule of thumb is: with native dependencies the version of node matters and I have no good mechanism to deal with that yet. The error warning could probably be clearer though.

**Comment by tessus** [comment]
Thanks for the detailed explanation.

Somehow there must be a different problem then. Because people installed Joplin via brew, which basically does a `npm install joplin`, but still ran into this issue. Very strange.
When I have more time I will be looking into it in more detail.

**Comment by daniellockyer** [comment]
Can you please try with v5.0.3? 🙂
