### ISSUE TITLE
node v10 crashes with sqlcipher

### ISSUE THREAD

**Issue by malafaya** [TryGhost/node-sqlite3#1100]
Until now, I have been using node-sqlite3@4.0.4 and node v8 with sqlcipher 3.4.2 with no problem whatsoever. I use a x64 linux machine to cross-compile to an arm linux, and it works fine (--target-arch=arm --target-platform=linux).
Problems arise when I migrate node to v10.14.2 and try to re-compile. When using the so cross-compiled module, I get a node crash when attempting to execute a get (I get no error when opening the db).
For information, I have another module that requires cross-compilation and that one works fine in node v10. Only node-sqlite3 is breaking. Also, if I compile using sqlite3 instead of sqlcipher, it also seems to work.

Two things caught my attention: a lot of warnings about deprecated stuff when compiling, but I think this is just about the same a for node v8; and the fact that an older version of nan is being used (2.10.0), and it clearly states it's for node <= 9.

Any thoughts?
Thanks.

**Comment by malafaya** [comment]
I tried today with sqlcipher v4.0.1 and node v10.15.0, with same outcome: crash when executing database.get(). Compiles and runs fine with node v8.15.0

**Comment by daniellockyer** [comment]
Would you be able to try with v5.0.3? 🙂
