### ISSUE TITLE
SQLITE_ERROR: not authorized when trying to load_extension

### ISSUE THREAD

**Issue by ricardotorquato** [TryGhost/node-sqlite3#1123]
Hey guys! How are you?

I've downloaded the `extension-functions.c` from https://www.sqlite.org/contrib and compiled with
```
gcc -fno-common -dynamiclib ./extension-functions.c -o ./libsqlitefunctions.dylib
```

Then I've tried to add this on my config:

```
pool: {
    afterCreate: (conn, done) => {
        conn.loadExtension(`/Users/ricardo/libsqlitefunctions.dylib`, (err: any) => {
            done(err, conn);
        });
    }
}
```

And I'm getting this error:
```
SELECT load_extension('/Users/ricardo/libsqlitefunctions.dylib'); - SQLITE_ERROR: not authorized
```

I've also tried to use the select syntax:
```
pool: {
    afterCreate: (conn, done) => {
        conn.run(`SELECT load_extension('/Users/ricardo/libsqlitefunctions.dylib');`, (err: any) => {
            done(err, conn);
        });
    }
}
```
But I get the same result `SQLITE_ERROR: not authorized`.

When I use the `SELECT load_extension` or the `.load` on my `sqlite3` client in console my `libsqlitefunctions.dylib` is properly loaded and I can use all the functions like `acos`, `asin`, `atan` so I don't believe the `dylib` file is the problem.

Any ideias how can I solve that?

**Comment by kewde** [comment]
Hi,

You must use the loadExtension() API.
https://github.com/mapbox/node-sqlite3/blob/723de4ca89924d464454f37b469dd1e801830632/src/database.cc#L636

Hmm, loadExtension should be authorized as long as that line is called.

**Comment by ricardotorquato** [comment]
> Hi,
> 
> You must use the loadExtension() API.
> [node-sqlite3/src/database.cc](https://github.com/mapbox/node-sqlite3/blob/723de4ca89924d464454f37b469dd1e801830632/src/database.cc#L636)
> 
> Line 636 in [723de4c](/mapbox/node-sqlite3/commit/723de4ca89924d464454f37b469dd1e801830632)
> 
>  sqlite3_enable_load_extension(baton->db->_handle, 1); 
> Hmm, loadExtension should be authorized as long as that line is called.

Hi!

I am not sure that I understood what you've said...

Should I try to do something different in my code?

I found that line here:

```
void Database::Work_LoadExtension(uv_work_t* req) {
    LoadExtensionBaton* baton = static_cast<LoadExtensionBaton*>(req->data);

    sqlite3_enable_load_extension(baton->db->_handle, 1);

    char* message = NULL;
    baton->status = sqlite3_load_extension(
        baton->db->_handle,
        baton->filename.c_str(),
        0,
        &message
    );

    sqlite3_enable_load_extension(baton->db->_handle, 0);

    if (baton->status != SQLITE_OK && message != NULL) {
        baton->message = std::string(message);
        sqlite3_free(message);
    }
}
```

**Comment by kewde** [comment]
Hi, 

I was just pointing out that the manual version of your code will not work because it doesn't call sqlite3_enable_load_extension. You must use the predefined loadExtension() API.

I haven't actually tried using that API function yet so I'm not able to help you further, but please post the results of your debugging efforts, greatly appreciated.

**Comment by jackfiallos** [comment]
If anybody here is using knex.js, the right way to run math functions with sqlite is setting up the pool like this:

```javascript
const config = {
    env: 'development',
    debug: true,
    db: {
        client: 'sqlite3',
        connection: {
            filename: `${__dirname}/data/testdb.sqlite`
        },
        useNullAsDefault: true,
        pool: {
            min: 2,
            max: 10,
            afterCreate: (conn, done) => {
                conn.loadExtension(`${__dirname}/libsqlitefunctions.dylib`, (err: any, res: any) => {
                    console.log(err);
                    done(null, conn);
                });
            }
        }
    }
};
```

with this enabled, you can perform the next query as follow

```javascript
knex.queryBuilder()
    .table('city')
    .select(knex.raw('ceil(cos(radians(lng)))'))
    .where('name', 'Dublin')
    .then(result => {
        console.log(result);
        process.exit(0);
    })
    .catch(e => {
        console.error(e)
        process.exit(0);
    });
```

**Comment by Masoud-kamali** [comment]
> If anybody here is using knex.js, the right way to run math functions with sqlite is setting up the pool like this:
> 
> ```js
> const config = {
>     env: 'development',
>     debug: true,
>     db: {
>         client: 'sqlite3',
>         connection: {
>             filename: `${__dirname}/data/testdb.sqlite`
>         },
>         useNullAsDefault: true,
>         pool: {
>             min: 2,
>             max: 10,
>             afterCreate: (conn, done) => {
>                 conn.loadExtension(`${__dirname}/libsqlitefunctions.dylib`, (err, res) => {
>                     console.log(err);
>                     done(null, conn);
>                 });
>             }
>         }
>     }
> };
> ```
> 
> with this enabled, you can perform the next query as follow
> 
> ```js
> knex.queryBuilder()
>     .table('city')
>     .select(knex.raw('ceil(cos(radians(lng)))'))
>     .where('name', 'Dublin')
>     .then(result => {
>         console.log(result);
>         process.exit(0);
>     })
>     .catch(e => {
>         console.error(e)
>         process.exit(0);
>     });
> ```

Hi, I used this commands but i got this error:

```
[Error: SQLITE_ERROR: %1 is not a valid Win32 application.
] {
  errno: 1,
  code: 'SQLITE_ERROR'
}

```

**Comment by daniellockyer** [comment]
Closing as the answer has been given 🙂
