### ISSUE TITLE
'sqlite3.h' file not found

### ISSUE THREAD

**Issue by andreddosantos** [TryGhost/node-sqlite3#1127]
Hello guys, 

When trying to install the sqlite3 with the SQLCipher extension i'm facing the current error:
<img width="1353" alt="log" src="https://user-images.githubusercontent.com/4041944/53262266-12516d80-36ce-11e9-851b-9b68454cfb98.png">

I've follow the steps in the provided [article](https://coolaj86.com/articles/building-sqlcipher-for-node-js-on-raspberry-pi-2/) and no success :( 

I'm able to install the package without the SQLCipher extension.

Can someone help to understand why?
Regards 
André

**Comment by andreddosantos** [comment]
Mange to solve the "'sqlite3.h' file not found" adding these 2 flags in the build as well:

```js
environment ('CPPFLAGS',"-I/usr/local/include -I/usr/local/include/sqlcipher")
environment ('CXXFLAGS',"-I/usr/local/include -I/usr/local/include/sqlcipher")
```

Now i have a new error :

> 23 warnings generated.
> .../platforms/android/build/standalone-toolchains/arm-linux-androideabi/bin/arm-linux-androideabi-clang++ -shared -rdynamic -fPIC  -Wl,-soname=node_sqlite3.node -o Release/obj.target/node_sqlite3.node -Wl,--start-group Release/obj.target/node_sqlite3/src/database.o Release/obj.target/node_sqlite3/src/node_sqlite3.o Release/obj.target/node_sqlite3/src/statement.o -Wl,--end-group -L/usr/local/include/lib -lsqlcipher -llog .../platforms/android/src/com/janeasystems/cdvnodejsmobile/jni/libnode//bin/armeabi-v7a/libnode.so
> .../platforms/android/build/standalone-toolchains/arm-linux-androideabi/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/**ld: error: cannot find -lsqlcipher**
> clang50++: error: linker command failed with exit code 1 (use -v to see invocation)
> make: *** [Release/obj.target/node_sqlite3.node] Error 1

**Comment by andreddosantos** [comment]
Managed to fix that one by providing the proper directory 'usr/local'

And now i have a new error ...

> platforms/android/build/standalone-toolchains/arm-linux-androideabi/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: sqlcipher: no archive symbol table (run ranlib)

**Comment by kewde** [comment]
I'll leave the issue open for a while, but I suggest you attempt to statically link the SQLCipher library and compiling your own bindings. You should be able to replace the sqlite tar archive with the SQLCipher one and force it to build it locally and thus not rely on a system wide dynamic library.

**Comment by daniellockyer** [comment]
I'm now going to close this as the issue has gone stale but LMK if you still encounter issues 🙂
