### ISSUE TITLE
Order By and Group by - Wrong result since 4.06

### ISSUE THREAD

**Issue by elrhourha** [TryGhost/node-sqlite3#1137]
Wrong result when i combine Group by and Order By.

I have this query :

Select  * 
FROM "message" "message" LEFT JOIN "conversation" "conversation" ON "conversation"."id"="message"."conversationId"  
LEFT JOIN "users_conversations" "conversation_conv_users" ON "conversation_conv_users"."conversationId"="conversation"."id" 
LEFT JOIN "user" "conv_users" ON "conv_users"."id"="conversation_conv_users"."userId"  
LEFT JOIN "user" "user" ON "user"."id"="message"."senderId"
WHERE "conversation"."id" IN(SELECT "users_conversations"."conversationId" AS "users_conversations_conversationId" 
                            FROM "users_conversations" "users_conversations"
                            WHERE "users_conversations"."userId" = 23) 
GROUP BY "conversation"."id" 
ORDER BY "message"."date_creation" DESC

that return wrong dates order ("message"."date_creation" DESC).

When i return to **version 4.0.3**, the problem is **solved**.

**Comment by kewde** [comment]
Hi,

I would need a reproducible and minimal test, could you provide that for me?
Thanks

**Comment by daniellockyer** [comment]
Closing unless a reproduction case is given 🙂
