### ISSUE TITLE
backup: segfault likely caused by timing issue

### ISSUE THREAD

**Issue by kewde** [TryGhost/node-sqlite3#1153]
Hypothesis: There seems to be a timing issue, when finish() is called before the step() completes it triggers a segfault. Finish() will clear the internal queue, but could it be that an item is still processing/stepping whilst finish is called.

**Comment by kewde** [comment]
Adding additional debug messages pretty much caused it not to segfault anymore, which means it's likely a timing issue.

**Comment by paulfitz** [comment]
This is in the tests involving the `temp` database, or do you see it elsewhere @kewde?  I've been able to replicate it with the `can backup from temp to main` and `can backup from main to temp` tests.

**Comment by paulfitz** [comment]
I see a fix got merged in #1154.  I've got an alternate tweak in hand if it is needed.

**Comment by kewde** [comment]
@paulfitz What tweak do you suggest? We still haven't found what exactly is the issue, the dumps aren't giving us useful information. But we have narrowed down what triggers it.

**Comment by kewde** [comment]
The function `assertRowsMatchDb` triggers it, but perhaps the setup for that failure is made by the previous executed backup code.

**Comment by kewde** [comment]
It's not actually the `step` function that caused it.

**Comment by paulfitz** [comment]
My alternate tweak was to switch from using the temp database to using an attached database.  I've a feeling there is some nuance in the lifetime of the temp database that I don't understand.  Once I stop using the temp database, the tests run reliably over thousands of iterations.

**Comment by daniellockyer** [comment]
I'm going to close this for now but if there's still an issue here, please let me know or open an issue with the new templates 🙂
