### ISSUE TITLE
I've compiled it, so why do prompt  to install these packages in my project?

### ISSUE THREAD

**Issue by Sun-Target** [TryGhost/node-sqlite3#1171]
These dependencies were not found:

* node-gyp in ./~/sqlite3/~/node-pre-gyp/lib/util/compile.js
* npm in ./~/sqlite3/~/node-pre-gyp/lib/util/compile.js

To install them, you can run: npm install --save node-gyp npm

**Comment by kewde** [comment]
What command did you execute? You have given me no information at all.
Thanks.
