### ISSUE TITLE
can backup from main to temp, Uncaught Error: SQLITE_ERROR: no such table: temp.foo

### ISSUE THREAD

**Issue by alex8088** [TryGhost/node-sqlite3#1181]
use sqlcipher, and test 

get 1 failed:

can backup from main to temp
Uncaught Error: SQLITE_ERROR: no such table: temp.foo

but no problem with sqlite 3.26 （node-sqlite3 4.0.6）

**Comment by kewde** [comment]
Hi,

SQLCipher is not officially supported, but I'll keep the issue open if anyone is interested in investigating it.

**Comment by daniellockyer** [comment]
Closing as the issue is stale but please re-open using an issue template if it's still an issue 🙂
