### ISSUE TITLE
List of all tables

### ISSUE THREAD

**Issue by mittalyashu** [TryGhost/node-sqlite3#1202]
I am not able to list all the tables inside a database using the dot command `.tables`.

**Comment by bruce-one** [comment]
I believe `.tables` is implemented in the sqlite CLI rather than for use by the library.

You should be able to query `sqlite_master` (and/or `sqlite_temp_master`) as an alternative way to get the same data.

Eg

    db.each("SELECT name FROM sqlite_master WHERE type='table'", (e, d) => console.log(d))

**Comment by mittalyashu** [comment]
Using the SQLite CLI is not helpful here.

I need to fetch and show all the db tables at once.

**Comment by bruce-one** [comment]
That query will work without the CLI; it only requires the node-sqlite library.

That code snippet is a Javascript example that will do what you want

**Comment by daniellockyer** [comment]
The security vulnerabilities in v5.0.3 should now be fixed so I'm going to close this as the code snippet to list tables should work 🙂
