### ISSUE TITLE
Interrupting/canceling  a query

### ISSUE THREAD

**Issue by bradisbell** [TryGhost/node-sqlite3#1205]
Is there any API for interrupting/cancelling a long-running query?

This seems to be [supported by the SQLite C interface](https://www.sqlite.org/c3ref/interrupt.html), but I didn't see if this was exposed to Node.js scripts.

**Comment by rlindner81** [comment]
Yes this is exposed. See [test/interrupt.test.js](/mapbox/node-sqlite3/blob/master/test/interrupt.test.js)

**Comment by mtgto** [comment]
API document doesn't have `interrupt`.
https://github.com/mapbox/node-sqlite3/wiki/API

Please add `interrupt` entry 🙏

**Comment by panther7** [comment]
+1

**Comment by daniellockyer** [comment]
Done: https://github.com/TryGhost/node-sqlite3/wiki/API#interrupt
