### ISSUE TITLE
How to get this.changes in DateBase.run's callback

### ISSUE THREAD

**Issue by mulingLHY** [TryGhost/node-sqlite3#1216]
The `this` object in DateBase.run's callback is always global no matter what kind of statement , so how can I get  the number of rows affected by this query

**Comment by daniellockyer** [comment]
Hey @mulingLHY 🙂 I've updated the docs about this: https://github.com/TryGhost/node-sqlite3/wiki/API#runsql--param---callback

> you must use an old-school function () { ... } style callback rather than a lambda function, otherwise this.lastID and this.changes will be undefined.
