### ISSUE TITLE
Constant minor CPU usage while using node-sqlite3

### ISSUE THREAD

**Issue by u2892** [TryGhost/node-sqlite3#1221]
Writing an Electron application, noticed that its CPU usage is constantly around 13-18% even when idling.

I think I have isolated the cause to node-sqlite3, as CPU usage is < 1% when disabling all DB calls entirely.

Examined the process using Process Hacker, it seems that there is one thread on each CPU constantly creating and closing files.

![cpu usage](https://user-images.githubusercontent.com/55481187/65126864-a481e000-da29-11e9-8d89-503abaad706d.png)

Is this expected behavior, or am I doing something wrong? The database connection is created on startup and kept open until the application closes.

The CPU usage persists regardless of the database mode (readonly/readwrite/create), and even when using :memory: as the database filename.

**Comment by kewde** [comment]
Thank you for the bug report,

I am unaware what would cause this. I will try and replicate this on Linux but I see some references to  [`libuv` ](https://github.com/libuv/libuv) which is a cross platform library. I have seen strange things come from there, especially on windows. 

Would be nice to figure out what is causing this.

**Comment by daniellockyer** [comment]
@u2892 Would you be able to provide a minimal reproduction and re-open with an issue template? 🙂
