### ISSUE TITLE
Is it possible to create a definitions file?

### ISSUE THREAD

**Issue by J-Cake** [TryGhost/node-sqlite3#1224]
Webstorm is screaming at me because it doesn't understand C++ modules. In order to fix this, you'd need a definitions file, they're typically defined in typescript and just let WebStorm know what to expect and what each function does, the parameters it takes etc. Just wanted to know if one already exists, if so, how complete is it and if it doesn't, would that be possible please.

Thanks

**Comment by J-Cake** [comment]
As you mentioned, the package is incomplete, but it is sufficient for my use case. Thank you

**Comment by kewde** [comment]
I am happy to accept a pull request with a more complete declaration file. 
I will keep this issue open.

**Comment by daniellockyer** [comment]
Closing in favor of https://github.com/TryGhost/node-sqlite3/issues/809 🙂
