### ISSUE TITLE
Update Travis dist from Precise to Xenial

### ISSUE THREAD

**Issue by siikasmaa** [TryGhost/node-sqlite3#1228]
The Linux distribution (Precise) defined in `.travis.yml` is being decomissioned from Travis CI. The following alert can be found when triggering a job:

>This job is running on our Precise environment, which is in the process of being decommissioned. Please update to a newer Ubuntu version by specifying dist: xenial in your .travis.yml.

More about this:
https://docs.travis-ci.com/user/reference/overview/#deprecated-virtualization-environments

**Comment by kewde** [comment]
For the time being, we will remain on trusty as much as possible as it produces builds with a lower version requirement for GLIBC.

**Comment by daniellockyer** [comment]
This should be no longer relevant 🙂
