### ISSUE TITLE
Can not install on windows 7/10  (win32 or x64) with nwjs.

### ISSUE THREAD

**Issue by liuyi** [TryGhost/node-sqlite3#1231]
Checked whole issue about sqlite3 and gyp, so many peole got the same problem, but have not find resolution.
target=0.37.4 to 0.42, both got the same log at beblow

**Comment by liuyi** [comment]
![image](https://user-images.githubusercontent.com/848803/67539987-6eb1d480-f716-11e9-9fc4-6b499a881158.png)

**Comment by dhulme** [comment]
Seems to be failing because of Node 12

**Comment by dhulme** [comment]
For me, upgrading to v4 of the package fixed the problem on Node 12. Why are you trying to build from source?

**Comment by morleym** [comment]
Upgrading to v4 fixed this for me on Node 12, too.

**Comment by dhulme** [comment]
I suggest this issue can be closed
