### ISSUE TITLE
Binary of sqlite3 is not getting updated

### ISSUE THREAD

**Issue by wsjwa** [TryGhost/node-sqlite3#1258]
Installed a new node version and executed rebuild on sqlite3. But sqlite won't update its binary. It stays in the old NODE_MODULE_VERSION.

installing with "--build-from-source" does not help either.

What is needed to update the binary for sqlite3?

sqlite3 is the only plugin that does not update its binary. All other DB drivers work fine,

**Comment by richardscarrott** [comment]
Not sure if this is related but `yarn install` is erroring with `node-pre-gyp http 403 https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.13/node-v72-darwin-x64.tar.gz` for us.

**Comment by bedwardly-down** [comment]
@wsjwa @richardscarrott what are the steps to reproduce this issue? I'm not fully clear about how to check this in the original report. Also, since this is several months old, is this bug still valid since SQLite's binary has been updated since?
