### ISSUE TITLE
extension error

### ISSUE THREAD

**Issue by baptistapedro** [TryGhost/node-sqlite3#1262]
Hello,
I loaded my extension and when I tried to open the browser I got this error:
https://dpaste.org/jcc8/raw

I only have this lines of code using the API:
```
var sqlite3 = require('sqlite3').verbose();
var db = new sqlite3.Database(':memory:');
db.serialize(function(){
        db.loadExtension('./myfunc3');
        db.run("SELECT TESTFUNC('CREATE TABLE foo(bar TEXT)'");
});
db.close();
```
TESTFUNC is coming from my extension. I am able to use it on the sqlite3 shell however I dont understand what that error is about.

Help please?

**Comment by lixingyangok** [comment]
i am facing the same issue, cannot loadExtension

**Comment by daniellockyer** [comment]
Please provide more details, including a reproduction case with your extension 🙂
