### ISSUE TITLE
Installing with --target=<target-node-version> results with "Unsupported target version" for targets >= 11

### ISSUE THREAD

**Issue by mceIdo** [TryGhost/node-sqlite3#1264]
When trying to install sqlite3 with `--target` arg, with targets >= 11.x.x, node-pre-gyp throws an error. It seems that there's an issue with node-pre-gyp v0.11.0. When forcing it to work with node-pre-gyp 0.14.0 (latest at the moment) - it works and selects the closest available target. 
It's important to mention that in node-pre-gyp 0.11.0, the --fallback-to-build doesn't work for this case - so if fails the installation altogether.

To reconstruct, simply run `npm install sqlite3 --target=12.13.1`

**Comment by daniellockyer** [comment]
This should no longer be relevant 🙂
