### ISSUE TITLE
Different behaviour of locking database on Windows and Linux

### ISSUE THREAD

**Issue by ANTOSzbk** [TryGhost/node-sqlite3#1270]
Today I had issue that my app was running without crash or error while debugging on Windows PC, and exited with 0 status code with `'SQLITE_BUSY: database is locked'` error while trying to run on Linux. The issue was I was using sqlite3 constructor (tried to open same db) with the same database file inside ```db.all(() => { //function that had constructor here e.g. 
// user.updateRow(xxx) } )``` callback without being aware of it. 
I think it should report me with an error on Windows too.

**Comment by bedwardly-down** [comment]
So you have the database open on Windows and are looking to open it on Linux at the same time? I'm a bit confused on what exactly is happening here.

**Comment by daniellockyer** [comment]
Closing as issue is stale 🙂
