### ISSUE TITLE
not able to install on Raspberry Pi with npm

### ISSUE THREAD

**Issue by rg-engineering** [TryGhost/node-sqlite3#1271]
I'm not able to install sqlitte3@4.1.1. on Raspi

see log:

```
> pi@raspberrypi:~ $ cd ~
> pi@raspberrypi:~ $ mkdir sqlite_test
> pi@raspberrypi:~ $ cd sqlite_test
> pi@raspberrypi:~/sqlite_test $ nano package.json
> pi@raspberrypi:~/sqlite_test $ sudo npm install
> > sqlite3@4.1.1 install /home/pi/sqlite_test/node_modules/sqlite3
> > node-pre-gyp install --fallback-to-build
> node-pre-gyp WARN Using request for node-pre-gyp https download
> node-pre-gyp WARN Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.1.1/node-v57-linux-arm.tar.gz
> node-pre-gyp WARN Pre-built binaries not found for sqlite3@4.1.1 and node@8.16.0 (node-v57 ABI, glibc) (falling back to source compile with node-gyp)
> gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/8.16.0"
> gyp WARN EACCES attempting to reinstall using temporary dev dir "/tmp/.node-gyp"
> make: Entering directory '/home/pi/sqlite_test/node_modules/sqlite3/build'
>   ACTION deps_sqlite3_gyp_action_before_build_target_unpack_sqlite_dep Release/obj/gen/sqlite-autoconf-3300100/sqlite3.c
>   TOUCH Release/obj.target/deps/action_before_build.stamp
>   CC(target) Release/obj.target/sqlite3/gen/sqlite-autoconf-3300100/sqlite3.o
> cc: internal compiler error: Killed (program cc1)
> Please submit a full bug report,
> with preprocessed source if appropriate.
> See <file:///usr/share/doc/gcc-6/README.Bugs> for instructions.
> deps/sqlite3.target.mk:129: recipe for target 'Release/obj.target/sqlite3/gen/sqlite-autoconf-3300100/sqlite3.o' failed
> make: *** [Release/obj.target/sqlite3/gen/sqlite-autoconf-3300100/sqlite3.o] Error 4
> make: Leaving directory '/home/pi/sqlite_test/node_modules/sqlite3/build'
> gyp ERR! build error
> gyp ERR! stack Error: `make` failed with exit code: 2
> gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
> gyp ERR! stack     at emitTwo (events.js:126:13)
> gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
> gyp ERR! System Linux 4.14.98-v7+
> gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/pi/sqlite_test/node_modules/sqlite3/lib/binding/node-v57-linux-arm/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/home/pi/sqlite_test/node_modules/sqlite3/lib/binding/node-v57-linux-arm" "--napi_version=4" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v57"
> gyp ERR! cwd /home/pi/sqlite_test/node_modules/sqlite3
> gyp ERR! node -v v8.16.0
> gyp ERR! node-gyp -v v3.8.0
> gyp ERR! not ok
> node-pre-gyp ERR! build error
> node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/pi/sqlite_test/node_modules/sqlite3/lib/binding/node-v57-linux-arm/node_sqlite3.node --module_name=node_sqlite3 --module_path=/home/pi/sqlite_test/node_modules/sqlite3/lib/binding/node-v57-linux-arm --napi_version=4 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v57' (1)
> node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/pi/sqlite_test/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
> node-pre-gyp ERR! stack     at emitTwo (events.js:126:13)
> node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
> node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:915:16)
> node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
> node-pre-gyp ERR! System Linux 4.14.98-v7+
> node-pre-gyp ERR! command "/usr/bin/node" "/home/pi/sqlite_test/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
> node-pre-gyp ERR! cwd /home/pi/sqlite_test/node_modules/sqlite3
> node-pre-gyp ERR! node -v v8.16.0
> node-pre-gyp ERR! node-pre-gyp -v v0.11.0
> node-pre-gyp ERR! not ok
> Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/pi/sqlite_test/node_modules/sqlite3/lib/binding/node-v57-linux-arm/node_sqlite3.node --module_name=node_sqlite3 --module_path=/home/pi/sqlite_test/node_modules/sqlite3/lib/binding/node-v57-linux-arm --napi_version=4 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v57' (1)
> npm notice created a lockfile as package-lock.json. You should commit this file.
> npm WARN test@ No description
> npm WARN test@ No repository field.
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules/fsevents):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: sqlite3@4.1.1 (node_modules/sqlite3):
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: sqlite3@4.1.1 install: `node-pre-gyp install --fallback-to-build`
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
> added 405 packages from 735 contributors and audited 6882 packages in 907.574s
> found 0 vulnerabilities
```
and here is the content of package.json:
```

{
  "name": "test",
  "license": "MIT",
  "optionalDependencies": {
    "sqlite3": "^4.1.1"
  },
  "dependencies": {
    "mysql": "^2.17.1"
  },
  "devDependencies": {
    "gulp": "^4.0.0",
    "mocha": "^6.0.2",
    "chai": "^4.2.0"
  }
}
```

**Comment by bedwardly-down** [comment]
So my first question is why are you doing this as root? I've never tinkered with a Raspi system so please bear with me. It's saying that root doesn't have access to its own home folder, so there may be some permission issues there that need to be resolved. 

According to this [blog post](https://chrislea.com/2018/08/20/cross-compiling-node-js-for-arm-on-ubuntu/), you may need to cross compile from a different system to get node to work properly (since node is trying to build node-v57ABI from source and it doesn't seem to have an arm version available). Cross-compiling can be a nightmare at times, from my own experience, so good luck with that. Of course that link tells how to do it with a later version of nodejs than what is currently available on raspi, so you may also be in luck if you can get a newer version installed and working too. :D

**Comment by rg-engineering** [comment]
First of all: cross compilation is not an option. It must be compilable on the target platform.

second: the user does not matter. we have the some behaviar if we do it with local user (without root) and correct rights

The thing is we use your package in a bigger environment (iobroker[iobroker](https://iobroker.com/). Here we provide so called adapter. A couple of adapter are using your package. The system itself is able to run on windows and linux and on many different hardware. and so raspi and co are coming into the game. The end user should just select an adapter and during installation everything needed for that adapter should be installed. on Raspi and other linux arm based systems this makes us trouble. 
as a example here one of the end user expierence:
https://forum.iobroker.net/topic/5555/neuer-adapter-sma-wechselrichter-mit-sbfspot/105
and I get also tickets in github:
https://github.com/rg-engineering/ioBroker.sbfspot/issues/15

It would be great if you could support us with that package...

**Comment by bedwardly-down** [comment]
It's definitely not my app. I'm just a support volunteer here that knows quite a bit about Linux, so thanks for responding.

So, when you say cross compilation isn't an option, you mean you don't have another system you can build the module on for Arm since your current one is failing to build it, right? I'm making sure i and others will be able to understand you correctly. 

Root with mainline Linux is pretty much taboo to work under in most circumstances, so i was taken a bit aback by thus module being built under it. I'm sorry about that. That's why i was asking about that. And your error here is clearly showing that something funky is going on with your root's home permissions: 



>> gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/8.16.0"
 >> gyp WARN EACCES attempting to reinstall using temporary dev dir "/tmp/.node-gyp"

That's where i was a bit concerned. 

Hmmm. Let me think about this for a bit.

**Comment by rg-engineering** [comment]
> So, when you say cross compilation isn't an option, you mean you don't have another system you can build the module on for Arm since your current one is failing to build it, right?

correct. The end user (not me) has his own system (which could by at least any system) where he wants to install our application. To support all our features this end user needs to install sqlite3 and the end user is not a software developer.

**Comment by bedwardly-down** [comment]
That makes perfect sense. Thanks for the thorough explanation. What makes it worse is node 8 doesn't support using git directly as an option for getting release packages, iirc. If it did and you were able to build locally, you could have released arm builds on either here or a private git repo and then set a crontab on their end to check for updates every so often.

**Comment by bedwardly-down** [comment]
I wanted to check up on this issue. I'm not sure how useful this would be but the documentation shows how to build from source as long as an sqlite3 binary is installed. 

https://github.com/mapbox/node-sqlite3#source-install

**Comment by daniellockyer** [comment]
Please try with v5.0.3 and failing that, the library should compile locally now 🙂
