### ISSUE TITLE
"attach database" fails when file specified as URI

### ISSUE THREAD

**Issue by broofa** [TryGhost/node-sqlite3#1272]
I'm trying to attach an existing database in read-only mode, thus using [the URI form](https://www.sqlite.org/uri.html) of the filepath.  This works from the sqlite command line:
```
kieffer$ sqlite3 :memory:
SQLite version 3.24.0 2018-06-04 14:10:15
Enter ".help" for usage hints.
sqlite> attach database 'file:/tmp/foo.sqlite?mode=ro' as foo_db;
sqlite> select count(*) from foo_db.events;
17249
sqlite> detach database foo_db;
sqlite> ^D
```

... however when I `run()` the command from sqlite3, it fails:

```
kieffer$ node
Welcome to Node.js v12.10.0.
Type ".help" for more information.
> sqlite3 = require('sqlite3')
{
  ...
  VERSION: '3.30.1',
  SOURCE_ID: '2019-10-10 20:19:45 18db032d058f1436ce3dea84081f4ee5a0f2259ad97301d43c426bc7f3df1b0b',
  ...
}
> db = new sqlite3.Database(':memory:')
Database { open: false, filename: ':memory:', mode: 65542 }
> db.run(`attach database 'file:/tmp/foo.sqlite?mode=ro' as foo_db`, console.log)
Database { open: true, filename: ':memory:', mode: 65542 }
> [Error: SQLITE_CANTOPEN: unable to open database: file:/tmp/foo.sqlite?mode=ro] {
  errno: 14,
  code: 'SQLITE_CANTOPEN'
}
```

FWIW,  I see the same issue when running this command in the "[DB Browser for SQLite](https://sqlitebrowser.org/)" app.

**Comment by bedwardly-down** [comment]
I'm just getting into sqlite3 for another project I'm contributing to, but what happens if you set the URI as `file:/tmp/foo.sqlite` without the `?mode=ro`?

**Comment by fioleto** [comment]
I faced the same problem in my project.

In my case, it causes built-in sqlite 'SQLITE_USE_URI' had be disabled.
A solution is to re-build with `SQLITE_USE_URI` flags.

```
export CPPFLAGS="-DSQLITE_USE_URI=1"; npm rebuild sqlite3 --build-from-source
```

```
DB.get('PRAGMA compile_options;') -->

[
...
  { compile_options: 'USE_URI' }
]
```

**Comment by daniellockyer** [comment]
https://github.com/TryGhost/node-sqlite3/issues/1272#issuecomment-1030686397 is the valid fix for now. If there's sufficient demand, I'd accept a PR to add support for this 🙂
