### ISSUE TITLE
No document of `interrupt`

### ISSUE THREAD

**Issue by mtgto** [TryGhost/node-sqlite3#1276]
API document doesn't have `interrupt`. (#518, #631)
https://github.com/mapbox/node-sqlite3/wiki/API

Please add `interrupt` entry 🙏

----

I bring it from issue comment.
https://github.com/mapbox/node-sqlite3/issues/1205#issuecomment-559983976

**Comment by bedwardly-down** [comment]
@mtgto, do you know how it works well enough to start an API document for it? If so, I don't think anyone here would have an issue with you raising a PR for it. There currently aren't any in the works and any help given here is definitely appreciated. <3

**Comment by daniellockyer** [comment]
Done: https://github.com/TryGhost/node-sqlite3/wiki/API#interrupt
