### ISSUE TITLE
node sqlite3 package does not work on a simple angular 9 app

### ISSUE THREAD

**Issue by zuoshuluHTC** [TryGhost/node-sqlite3#1297]
https://stackoverflow.com/questions/60567717/node-sqlite3-package-does-not-work-on-a-simple-angular-9-app

I post my issues on stackoverflow above, I hope this is the better place to get a solution for angular sqlite support

**Comment by bedwardly-down** [comment]
So, after going to your link, I'm guessing a huge part of the issue has to do with type definitions not working properly? If that's the case, please see https://github.com/mapbox/node-sqlite3/issues/1224. The type definitions required to work with this module are very much a work in progress and seemingly not being maintained well enough to really be useful unless you're willing to  hack together your own like several projects I've seen do.

Also, depending on what you're trying to do, [better-sqlite3](https://github.com/JoshuaWise/better-sqlite3) might be your better option. I believe it has its own type definitions that were created by its maintainer for this reason, but I could be totally wrong.

**Comment by daniellockyer** [comment]
Closing in favor of https://github.com/TryGhost/node-sqlite3/issues/809 🙂
