### ISSUE TITLE
Implement Stale Bot To Help Clear Out Old Pull Requests and Bugs

### ISSUE THREAD

**Issue by bedwardly-down** [TryGhost/node-sqlite3#1298]
@kewde, since you're the main maintainer here and this repo has quite a few way out of date PRs and bugs that may not be relevant anymore, have you thought about implementing [this](https://probot.github.io/apps/stale/)? I've seen it used in other repos and it seems to be a great way to keep all of this from piling up.

**Comment by kewde** [comment]
Would be nice but I don't have the permissions :|
@springmeyer

**Comment by bedwardly-down** [comment]
Gotya.

**Comment by springmeyer** [comment]
@kewde can you try again now?

**Comment by kewde** [comment]
@springmeyer 
Thanks!

**Comment by kewde** [comment]
I will take a look at this, I think it will be a useful bot.
Some people might feel a bit hurt that a bot closes their pull request, but it's not a lost effort.

**Comment by bedwardly-down** [comment]
The less you gotta worry about in the immediate future the better, right? Until you get more help, you don't need anymore stress than what's necessary.

**Comment by springmeyer** [comment]
Thank you @kewde

**Comment by bedwardly-down** [comment]
While you get that setup, would you like me to go ahead and close this issue since it's not been acknowledged or wait until it's been implemented? I'm fine either way.

**Comment by daniellockyer** [comment]
This is definitely on my radar to do and I'm tracking this elsewhere so I'll close it for now 🙂
