### ISSUE TITLE
could I build it for nodejs-mobile runed by ios and android?

### ISSUE THREAD

**Issue by Txiaozhe** [TryGhost/node-sqlite3#1301]
nodejs-mobile: https://github.com/JaneaSystems/nodejs-mobile

**Comment by bedwardly-down** [comment]
Sorry for the late reply. Could you please provide more details on what you’re wanting to do?

I know this successfully builds for react-native mobile implementations, so there’s that, at least

**Comment by daniellockyer** [comment]
Closing as issue is stale 🙂
