### ISSUE TITLE
Event 'profile' does not return parameter binded sql.

### ISSUE THREAD

**Issue by ssassn12** [TryGhost/node-sqlite3#1305]
When I register to receive profile events, I get the SQL unbinded - containing not replaced parameters.
E.g., the result I get for the first parameter (sql) looks like:

```
SELECT x FROM y WHERE z=?

```

Am I doing something wrong - the query is executed correctly, bu the profile event emitted, contains it with unbounded value - this is not very useful when debugging. Thank you, for the help in advance!

**Comment by daniellockyer** [comment]
Unfortunately this is expected, as this is the result we are provided by SQLite 😕
