### ISSUE TITLE
Electron 10 & sqlite3

### ISSUE THREAD

**Issue by eviawriter** [TryGhost/node-sqlite3#1331]
Hi there,
First of all: thanks for your great work on node-sqlite3. I use it for my own electron-app and I love it! 

I was just wondering if there is support for Electron 10 planned for the future. In electron 9 we can still use app.allowRendererProcessReuse = false in main.js, but that will change in electron 10. See also: (https://github.com/electron/electron/issues/18397#issuecomment-583221969). 

Thx in advance for your reaction and keep up the good work!

**Comment by ChrisHSandN** [comment]
The module (I think) will be compatible once the v5 release launches as it has been converted to N-API.
https://github.com/mapbox/node-sqlite3/issues/1274

**Comment by jjhbw** [comment]
This should be fixed with today's 5.0 release.

**Comment by stevenroussey-privicy** [comment]
Are there pre-built versions for Electron 9 and 10?

**Comment by daniellockyer** [comment]
Please try with the latest version - v5.0.3 🙂 I've had reports Electron v18 is compatible with it
