### ISSUE TITLE
syntax for using encrypted database with sqlite3

### ISSUE THREAD

**Issue by Aryesh-M** [TryGhost/node-sqlite3#1332]
Hello, 
        I am generating an encrypted database using the procedure given in [this article](https://discuss.zetetic.net/t/how-to-encrypt-a-plaintext-sqlite-database-to-use-sqlcipher-and-avoid-file-is-encrypted-or-is-not-a-database-errors/868). I have successfully generated an encrypted database but do not know how to use that database with sqlite3 further on. I wanna know the syntax to make connection with password or PRAGMA KEY with sqlite3 syntax.

**Comment by daniellockyer** [comment]
Hey @Aryesh-M, you should be able to use `.run` to execute the PRAGMA statements

```js
db.run('PRAGMA key = \'passphrase\';');
```
