### ISSUE TITLE
CI: reduce publishing matrix

### ISSUE THREAD

**Issue by kewde** [TryGhost/node-sqlite3#1339]
N-API allows us to not chase the Node release cycle.
It is ABI stable, which means that if we build a version of node-sqlite3 for v5.0.0 with N-API v3 it will work for newer releases of Node v14, v15 etc.

This will be the case from v5.0.0.
However, our CI needs to be modified to not attempt publishing a build for every test job.

**Comment by daniellockyer** [comment]
This should be fixed - I've made it publish with Node 16 which is the latest LTS 🙂
