### ISSUE TITLE
Memory leak when running with Jest

### ISSUE THREAD

**Issue by pelotom** [TryGhost/node-sqlite3#1345]
When I simply try to require `sqlite3` from a Jest test with the `--detectLeaks` flag, it says there is a memory leak. Repro here: https://github.com/pelotom/sqlite3-jest-memory-leak.

As explained in [this article](https://chanind.github.io/javascript/2019/10/12/jest-tests-memory-leak.html) this may just be due to the way that Jest unloads and reloads modules to ensure isolation between runs. It doesn't look like much memory is being leaked; my main issue is that it prevents me from using `--detectLeaks` to find other worse leaks.

**Comment by daniellockyer** [comment]
Closing this for now as its not clear if this is a direct memory leak from node-sqlite3 or a quirk w/ Jest
