### ISSUE TITLE
gyp: Undefined variable napi_build_version in binding.gyp while trying to load binding.gyp

### ISSUE THREAD

**Issue by baobao12356** [TryGhost/node-sqlite3#1359]
执行
node-gyp rebuild --target=5.0.2 --arch=ia32 --target_platform=win32 --dist-url=https://atom.io/download/electron/ --module_name=node_sqlite3 --module_path=../lib/binding/electron-v5.0-win32-ia32
报错如下：

gyp: Undefined variable napi_build_version in binding.gyp while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\shzto\AppData\Roaming\npm\node_modules\node-gyp\lib\configure.js:350:16)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\shzto\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--target=7.1.2" "--arch=ia32" "--target_platform=win32" "--dist-url=https://atom.io/download/electron/" "--module_name=node_sqlite3" "--module_path=../lib/binding/electron-v7.1-win32-ia32"
gyp ERR! cwd D:\xaingmu\gitlab\im-web\im-desktop\node_modules\sqlite3
gyp ERR! node -v v11.4.0
gyp ERR! node-gyp -v v7.0.0
gyp ERR! not ok

![image](https://user-images.githubusercontent.com/22005273/87776556-8f98f780-c85a-11ea-9863-0e7867dbd96e.png)

**Comment by baobao12356** [comment]
各位大佬有遇到过得麻烦解答一下，谢谢

**Comment by zerooverture** [comment]
> 各位大佬有遇到过得麻烦解答一下，谢谢

你NODE版本太低了 看下readme

**Comment by marcosroriz** [comment]
I'm having the same issue. Anyone know how to fix this?

**Comment by soumen-saniel** [comment]
I was having the same issue in mac.
If you are on mac
Try upgrading to latest node version and latest npm version
And then run
npm i -g node-gyp@latest && npm config set node_gyp "/usr/local/lib/node_modules/node-gyp/bin/node-gyp.js"

**Comment by Niek** [comment]
Running `npm i node-gyp@latest` resolved the issue for me.

**Comment by hello-chenchen** [comment]
the same problem for me, when package electron app

**Comment by i-chaochen** [comment]
Same issue here.

electron cannot find sqlite3 module

tried many ways to rebuild sqlite3 but all failed

**Comment by joshuanathanson** [comment]
It looks like you need at least node `10.23.0` as noted in this issue: https://github.com/nodejs/node-gyp/issues/2224
In that issue, it mentions that the fix was never backported to node 10.x.  A little more digging indicates that node 10.23.0 was the version it was backported to, as seen in this PR: https://github.com/nodejs/node/pull/27835

**Comment by daniellockyer** [comment]
Would you be able to try with v5.0.3? 🙂

**Comment by w1i2n3d4** [comment]
请问如何解决这个问题，我最近也遇到了
