### ISSUE TITLE
Build on Windows for Raspberry Pi 4

### ISSUE THREAD

**Issue by projectje** [TryGhost/node-sqlite3#1363]
electron builder 22.4.1
electron 8.2.1
electron-updater 4.2.5
target: linux, armv7l (raspberry)
sqlite3: "^4.1.1",
    "build": "webpack --mode production && electron-builder --config .env.json",

I included https://github.com/mapbox/node-sqlite3 but this will want to build locally through node-gyp (in TeamCity). Which versions should I indicate to prevent manual local rebuild so that I can trigger the build from a Windows machine (so without rebuilds). Which binaries are available?

"win": {
"target" : [
{
"target": "nsis",
"arch": ["x64"]
}
]
},
"linux": {
"target" : [
{
"target": "AppImage",
"arch": ["armv7l"]
}

**Comment by daniellockyer** [comment]
Please try with the latest version and get back to me if you still have issues 🙂
