### ISSUE TITLE
Snyk reports about node-addon-api 2.0.0 vulnerability

### ISSUE THREAD

**Issue by yoavain** [TryGhost/node-sqlite3#1364]
https://snyk.io/vuln/SNYK-JS-NODEADDONAPI-571001

Should Update node-addon-api to 2.0.1.
Also, is there a reason this dependency version is fixed and not using ^2.0.0?

Thanks!

**Comment by yoavain** [comment]
Is this project abandoned?

**Comment by daniellockyer** [comment]
This should no longer be relevant in `sqlite3` v5+ 🙂
