### ISSUE TITLE
Prebuilt binaries for node 14?

### ISSUE THREAD

**Issue by tsondergaard** [TryGhost/node-sqlite3#1371]
It appears there are not prebuilt binaries for node 14 (14.8.0) on Windows. It would be great to have. If there are no immediate plans to add this, can you share when it might happen? Would it be before node 14 becomes LTS?

**Comment by wolfgangmeyers** [comment]
There also don't seem to be prebuilt binaries for Mac.

**Comment by vmp-mark** [comment]
I would also appreciate updated prebuilt binaries for node 14.8 on all platforms

**Comment by daniellockyer** [comment]
`node-sqlite` v5 switches to NAPI, so we're not particularly tied to particular Node versions any more. Windows x86 and x64 binaries exist for 5.0.2, and I'm going to publish a new version from `master` soon 🙂
