### ISSUE TITLE
Uncaught Error: A dynamic link library (DLL) initialization routine failed.

### ISSUE THREAD

**Issue by gxl199833** [TryGhost/node-sqlite3#1382]
Uncaught Error: A dynamic link library (DLL) initialization routine failed.
\\?\C:\Users\LJ-PC-LXL\Desktop\test\node_modules\sqlite3\lib\binding\napi-v3-win32-x64\node_sqlite3.node

？？ 卸载安装了好几次都是这样的，这是为什么呀？

**Comment by cnTrent** [comment]
请问你这个问题解决了么 我也一样

**Comment by daniellockyer** [comment]
Please try with the latest version - v5.0.3 🙂
