### ISSUE TITLE
Publish Node 15 version

### ISSUE THREAD

**Issue by kibertoad** [TryGhost/node-sqlite3#1393]
Our CI is currently failing when trying to use sqlite3 on Node 15 with `Error: Cannot find module 'sqlite3'`, I assume there is no prebuilt binary for this version.

**Comment by doyongid** [comment]
I am getting the same error in firebase function.

**Comment by Silve2611** [comment]
We would also need sqlite3 for Node 15. Is there any Roadmap when it will be updated?

**Comment by daniellockyer** [comment]
This is no longer required as we switched to N-API 🙂
