### ISSUE TITLE
how can i backup my sqlite3 database and dont close my api server？

### ISSUE THREAD

**Issue by radiorz** [TryGhost/node-sqlite3#1401]
i use fastify to build a database server，how can i backup my database ?

**Comment by Chechuck** [comment]
Hi!

Without more details about what are you trying to do, I suggest you try this: 
```js
db.run('VACUUM INTO $filename', { $filename: 'backup.sql' });
```

**Comment by radiorz** [comment]
i use sequelize to deal with my sqlite3 database. and i bind the model and sequelize to fastify instance. so i can use this.db.Users to createordelete my data in my users datatable.
are there any way to backup and restore database throw a api that my frontend can call it and download or upload the files?

**Comment by daniellockyer** [comment]
Closing as issue is stale 🙂
