### ISSUE TITLE
how can i export the data in my sqlite3 database to an excel file?

### ISSUE THREAD

**Issue by radiorz** [TryGhost/node-sqlite3#1402]
i use fastify nodejs and sequelize to build a database server，how can i backup my data?

**Comment by SinanGabel** [comment]
You can export .CSV files per table for example (possibly not the most elegant solution).

**Comment by radiorz** [comment]
thanks for your comment. i want to export my database to an excel file by my api server(). i found that "exceljs" npm module etc ... works. but if there are any good ways please tell me

**Comment by daniellockyer** [comment]
Closing as this issue is stale 🙂
