### ISSUE TITLE
Question about caching.

### ISSUE THREAD

**Issue by RomanBurunkov** [TryGhost/node-sqlite3#1412]
Hi there,

Could some one clarify how [caching feature](https://github.com/mapbox/node-sqlite3/wiki/Caching) works?

**Comment by TehShrike** [comment]
I am also curious how the caching works.  Specifically: is the cache in-memory, or does it somehow work across multiple processes/executions?

**Comment by daniellockyer** [comment]
Right now, it's a simple memory-based cache of the Database object so it doesn't need to be open + closed across instances: https://github.com/TryGhost/node-sqlite3/blob/e0542d5e7a33d0920d6ea6d08ea0de7b4d2050c5/lib/sqlite3.js#L29-L56
