### ISSUE TITLE
add extension-functions.c from http://www.sqlite.org/contrib

### ISSUE THREAD

**Issue by kaizhu256** [TryGhost/node-sqlite3#1414]
working on finance app using both node-sqlite3 and sql.js.  a sorely missed feature in node-sqlite3 (but present in sql.js) is `sqrt` for calculating stddev.

here's the [sql.js pr](https://github.com/sql-js/sql.js/pull/142/files#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52R42) that added `extension-functions.c` to their build-process.  can something similar be done in node-sqlite3?

**Comment by daniellockyer** [comment]
I think it's unlikely that we'll add this but we've enabled native math functions inv v5.0.3 so please give that a go 🙂
