### ISSUE TITLE
Linux arm installing issue 

### ISSUE THREAD

**Issue by StoneMcDev** [TryGhost/node-sqlite3#1417]
![image](https://user-images.githubusercontent.com/70589660/103256425-38ca4900-49c8-11eb-958f-46eccd52e8d0.png)
The debug log is bellow
https://pastebin.com/VUsth1XV

**Comment by daniellockyer** [comment]
Prebuilt Linux ARM64 binaries are coming in the next release.

Your problem looks unrelated to `node-sqlite3` so I'm going to close this 🙂
