### ISSUE TITLE
 SQLITE_ERROR: The specified module could not be found.

### ISSUE THREAD

**Issue by Masoud-kamali** [TryGhost/node-sqlite3#1418]
Hi guys,
I used loadExtension for add mod_spatialite exntesion. as you said, I add .dll file to my directory for windows 10 and after that i load this extension.
but it can not find this module.
actually I checked it with sqlite3.exe and mod_spatialite.dll in cmd and it works.

this is my code and './spatialite/mod_spatialite' is my path.
```
const sqlite3 = require('sqlite3').verbose();
const db = new sqlite3.Database(':memory:');

db.loadExtension('./spatialite/mod_spatialite.dll',(err)=>{
    console.log(err);
});

```

**Comment by bojanbizjak** [comment]
same issue.

**Comment by wangfenjin** [comment]
@zhengtulymGh I think we can follow the issue in here

**Comment by daniellockyer** [comment]
Would you be able to provide more details, including a link to build your library?

**Comment by wangfenjin** [comment]
I think the issue might be we shouldn't include the extension like '.dll' or '.so' when load the extention
