### ISSUE TITLE
Clarify documentation regarding multiple callback calls

### ISSUE THREAD

**Issue by rhansen** [TryGhost/node-sqlite3#1419]
The [API documentation for Database#run](https://github.com/mapbox/node-sqlite3/wiki/API#databaserunsql-param--callback) currently says:

> * `callback` *(optional)*: If given, it will be called when an error occurs during any step of the statement preparation or execution, *and* after the query was run.

Questions about that sentence:
* Is it still accurate? I couldn't find anywhere in the code where the callback could be called multiple times, but I could have missed something.
* Does that also apply to related functions such as Database#all and Database#get?

**Comment by daniellockyer** [comment]
This has been fixed, it does not get called multiple times 🙂
