### ISSUE TITLE
Database Is Always Locked

### ISSUE THREAD

**Issue by elfin8er** [TryGhost/node-sqlite3#1428]
Hello, for some reason, I am not able to write to a file. Everything works fine if I store the data in memory, but not in a file. I start with no db.sqlite file, and I'm able to see it getting created, but once db.run is called, I see a db.sqlite-journal file gets created and then I receive the error `SQLITE_BUSY: database is locked`.

```
var sqlite3 = require('sqlite3').verbose();
var db = new sqlite3.Database('./db.sqlite');

db.run("CREATE TABLE lorem (info TEXT)");
db.close();
```

Node is the only thing that would be using the file since it doesn't exist until the database is initialized. Am I doing something wrong?

Thanks!

**Comment by daniellockyer** [comment]
Hey @elfin8er 👋🏻 I can't seem to reproduce this on the latest version - would you be able to try with v5.0.3? 🙂
