### ISSUE TITLE
Date objects are stored in a non-usable format (milliseconds, not seconds or date strings)

### ISSUE THREAD

**Issue by tkalliom** [TryGhost/node-sqlite3#1431]
**Expected behavior**: the driver handles times such that writing `Date`s to `datetime` columns allows usage of time-related functions, and reading the date yields an equivalent `Date` object.

**Actual behavior**: `Date`s are written as millisecond numbers (the raw numeric value of Javascript `Date`s), which are not compatible with time-related functions (which assume seconds) and which deserialize to Javascript numbers.

A sample to illustrate this issue:
```javascript
const date = new Date("2021-01-01T12:00:00Z");

const sqlite3 = require("sqlite3").verbose();
const db = new sqlite3.Database(":memory:");

db.serialize(function () {
  db.run("CREATE TABLE tests (name STRING, timestamp DATETIME NOT NULL)");

  const statement = db.prepare("INSERT INTO tests VALUES (?, ?)");
  statement.run("Timestamp as Date", date);
  statement.run("Timestamp as number (milliseconds)", date.getTime() / 1000);
  statement.finalize();

  db.each("SELECT name, timestamp, DATE(timestamp) AS string_date, DATE(timestamp, 'unixepoch') AS epoch_date FROM tests", function (_err, row) {
    console.log(`${row.name}: ${row.timestamp}, ${row.string_date}, ${row.epoch_date}`);
  });
});

db.close();
```

Output:
```
Timestamp as Date: 1609502400000, null, null
Timestamp as number (milliseconds): 1609502400, null, 2021-01-01
```

To compare with other drivers, mysqljs and pg by default returns `Date`s but can be configured to return strings (`dateStrings`, `setTypeParser`).

**Comment by daniellockyer** [comment]
Whilst this is true, SQLite does not have a native storage type for date/time. You'd need to supply the columns to node-sqlite3 which are datetime so we can serialize them back to native JS Date objects, and I feel like that is going to bloat the API.

**Comment by tkalliom** [comment]
Fair enough on the read part, but this report was mainly about the write part. The user of the library will definitely have to handle the times manually on read due to it being unfeasible to automate for the reasons you stated. On the other hand, for writes the driver could well provide a behavior that is arguably more sane: writing the values as seconds. This way no extra steps would be needed by users of the library to get a storage format compatible with SQLite functions.

The new write behavior would obviously be a breaking change. It would need a new major version number and/or being opt-in via configuration.
