### ISSUE TITLE
How to compile sqlite3 with SQLITE_ENABLE_MATH_FUNCTIONS flag

### ISSUE THREAD

**Issue by trevorhreed** [TryGhost/node-sqlite3#1438]
I'm hoping to install sqlite3 via npm but with the math functions (cos, sin) enabled. According to the [sqlite3 website](https://www.sqlite.org/draft/lang_mathfunc.html), these math functions are only available if sqlite3 is compiled with the DSQLITE_ENABLE_MATH_FUNCTIONS flag. Despite reading [this](https://www.npmjs.com/package/sqlite3#user-content-custom-builds-and-electron) section of the node-sqlite3 instructions, I can't figure out how to pass this flag in to the build process.

**Comment by kewde** [comment]
Hi,

I expect this to land after 30th of march when a new version of SQLite3 is released upstream.

**Comment by Jeremy-Doneghue** [comment]
Any updates on this release?

**Comment by paridhi-agr** [comment]
Please release the node-gyp dependency fix. It is causing severe security vulnerabilities

**Comment by kollinmurphy** [comment]
Is anyone actively working on this? It'd be a very nice feature to have.

**Comment by paulfitz** [comment]
I think this happened in https://github.com/mapbox/node-sqlite3/pull/1507

**Comment by daniellockyer** [comment]
This is released in `sqlite3` v5.0.3 🙂
