### ISSUE TITLE
Rework build publishing matrix (NAPI v6)

### ISSUE THREAD

**Issue by kewde** [TryGhost/node-sqlite3#1444]
Builds for NAPI v6 are not published because the container with Node 11 does not support v6 and wins the race to publishing the builds (v3 only), causing subsequent build containers (Node 12 etc) to  fail because v3 already exists. This is a failure of node-pre-gyp.

The recent adoption of NAPI allows for only one container in the build matrix to be responisble for publishing the builds.

**Comment by daniellockyer** [comment]
This should be fixed/no longer relevant 🙂
