### ISSUE TITLE
Update to SQLite 3.35

### ISSUE THREAD

**Issue by kibertoad** [TryGhost/node-sqlite3#1453]
`returning` is finally supported in latest SQLite version, which makes it a highly desirable update: https://nalgeon.github.io/sqlite-3-35/

**Comment by kurttheviking** [comment]
Also `ALTER TABLE DROP COLUMN` :)

**Comment by daniellockyer** [comment]
`master` contains SQLite v3.38.2 - will be released soon 🙂
