### ISSUE TITLE
Error installing command failed

### ISSUE THREAD

**Issue by ApocalypseCalculator** [TryGhost/node-sqlite3#1456]
When I try to install the sqlite3 package on my Raspberry Pi (Ubuntu Server 20.10), I get the following error: 

![image](https://user-images.githubusercontent.com/59318806/112153077-51a65d00-8bb9-11eb-8b09-f3d6fddd8d40.png)

I've searched everywhere and nothing would solve this. 

I have gcc, python3, all the required dependencies

So far I've tried: 
- Using build from source
- Using unsafe perm
- Deleting package-lock.json
- Reinstalling node-gyp
- Nuking the cache
- configured npm python to python3 path
- Reinstalling node.js (v12.19)
- Creating symlink to /usr/bin/node

If it helps I installed node through snap

The complete log is here: 
[logs.txt](https://github.com/mapbox/node-sqlite3/files/6189932/logs.txt)

Any help would be greatly appreciated

**Comment by cmbartschat** [comment]
Seeing the same issue on Mac, Big Sur 11.2.3, Node 12.21.0, npm 7.6.3.

**Comment by lzyor** [comment]
same, see:
https://github.com/nodejs/node-gyp/issues/508
maybe help

**Comment by daniellockyer** [comment]
Would you be able to try with v5.0.3? 🙂

**Comment by ApocalypseCalculator** [comment]
Still errors, in fact it is the exact same error. Also the same issue on my other arm server
