### ISSUE TITLE
select in large tables

### ISSUE THREAD

**Issue by jadsongmatos** [TryGhost/node-sqlite3#1470]
Does anyone have any better suggestions for me to load all the data from a giant table ?
I was trying to do it with db.each but memory fills up too fast so I decided to load sequentially

```

var i = 0;
test(0);

function test(id){
  db.get("select * from cnpj where id > (?)",[id], (err, row) => {
    if (err) {
      throw err;
    }
    i++;
    console.log(i,row.id,row.razao_social);
    test(row.id)
  })
}

```

**Comment by daniellockyer** [comment]
Unfortunately the memory usage you'll experience will correlate with number of rows fetched. You could batch your fetching to try and limit the impact of this
