### ISSUE TITLE
CSV loadable extension

### ISSUE THREAD

**Issue by var-kar** [TryGhost/node-sqlite3#1480]
Hello everyone,

Thanks for the wonderful library, it has many use in my day-to-day life. 

I know that the  .mode type commands cannot be implemented on the JS version.

But how about adding this extension to provide CSV load support?

https://www.sqlite.org/csv.html

Can this be done easily? If so How?

Many thanks

**Comment by daniellockyer** [comment]
Closing as duplicate of https://github.com/TryGhost/node-sqlite3/issues/1330 🙂
