### ISSUE TITLE
npm ERR! ENOTEMPTY: directory not empty

### ISSUE THREAD

**Issue by velvizhi-palanisamy** [TryGhost/node-sqlite3#1489]
Getting the error on running npm install.

Using symlink to point to node_modules form previous build to avoid package installation everytime
ln -s /var/jenkins_home/softwares/angular/node_modules .

**Packages ad versions:**
_npm: 7.19.1_
_angular: 9_

_+ npm install
npm ERR! code ENOTEMPTY
npm ERR! syscall rename
npm ERR! path /var/jenkins_home/workspace/AmpliSeqUI-Dev2-Build-And-Deploy-Angular9_GitHub/code/amplisequi-angular/amplisequi-angular/node_modules/acorn
npm ERR! dest /var/jenkins_home/workspace/AmpliSeqUI-Dev2-Build-And-Deploy-Angular9_GitHub/code/amplisequi-angular/amplisequi-angular/node_modules/.acorn-ssxUwlor
npm ERR! errno -39
npm ERR! ENOTEMPTY: directory not empty, rename '/var/jenkins_home/workspace/<path>/node_modules/acorn' -> '/var/jenkins_home/workspace/<path>/node_modules/.acorn-ssxUwlor'_

FYI, This was working fine before

**Comment by velvizhi-palanisamy** [comment]
This error occurred while installing packages. .acorn-ssxUwlor was no where found in node_modules. Is this something not related to acorn?

npm ERR! path /var/jenkins_home/workspace/AmpliSeqUI-Dev2-Build-And-Deploy-Angular9_GitHub/code/amplisequi-angular/amplisequi-angular/node_modules/**acorn**
npm ERR! dest /var/jenkins_home/workspace/AmpliSeqUI-Dev2-Build-And-Deploy-Angular9_GitHub/code/amplisequi-angular/amplisequi-angular/node_modules/**.acorn-ssxUwlor**
npm ERR! errno -39
npm ERR! ENOTEMPTY: directory not empty, rename '/var/jenkins_home/workspace//node_modules/acorn' -> '/var/jenkins_home/workspace//node_modules/**.acorn-ssxUwlor'**

**Comment by gms1** [comment]
What makes you think this is in any way related to node-sqlite3?

**Comment by daniellockyer** [comment]
I'm not sure this is related to `node-sqlite3` but if you still suspect otherwise, please let me know 🙂
