### ISSUE TITLE
Access Denied for Pre-Compiled versions

### ISSUE THREAD

**Issue by ozdeadmeat** [TryGhost/node-sqlite3#1494]
I have an open source system that uses node-sqlite3 as a dependency. Rather than have my users download about 4GB of compiler applications for windows, is there a way to grant the general public access to the pre-compiled versions of this node?

**Comment by daniellockyer** [comment]
Prebuilt versions should be available for common platforms in v5.0.3, and more will be added in coming releases 🙂
