### ISSUE TITLE
TypeError: Cannot read property 'apply' of undefined

### ISSUE THREAD

**Issue by ChunJungChang** [TryGhost/node-sqlite3#1497]
Hi all, I am trying install sqlite3, however, it is failed. I think that the root cause is needle version, needle 2.9.0 is not working for node-pre-gyp.

node npm install sqlite3@^4.0.0

> sqlite3@4.2.0 install /home/william.chang/AAA/BBB/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using needle for node-pre-gyp https download
node-pre-gyp ERR! UNCAUGHT EXCEPTION
node-pre-gyp ERR! stack TypeError: Cannot read property 'apply' of undefined
node-pre-gyp ERR! stack     at ClientRequest.<anonymous> (/home/william.chang/AAA/BBB/node_modules/node-pre-gyp/node_modules/needle/lib/needle.js:618:20)
node-pre-gyp ERR! stack     at ClientRequest.g (events.js:291:16)
node-pre-gyp ERR! stack     at emitOne (events.js:96:13)
node-pre-gyp ERR! stack     at ClientRequest.emit (events.js:188:7)
node-pre-gyp ERR! stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:474:21)
node-pre-gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
node-pre-gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:363:20)
node-pre-gyp ERR! stack     at emitOne (events.js:96:13)
node-pre-gyp ERR! stack     at TLSSocket.emit (events.js:188:7)
node-pre-gyp ERR! stack     at readableAddChunk (_stream_readable.js:176:18)
node-pre-gyp ERR! System Linux 3.10.0-1160.el7.x86_64
node-pre-gyp ERR! command "/home/william.chang/AAA/tools/nodejs-v6/target/bin/node" "/home/william.chang/AAA/BBB/n
ode_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/william.chang/AAA/BBB/node_modules/sqlite3
node-pre-gyp ERR! node -v v6.10.0
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! This is a bug in `node-pre-gyp`.
node-pre-gyp ERR! Try to update node-pre-gyp and file an issue if it does not help:
node-pre-gyp ERR!     <https://github.com/mapbox/node-pre-gyp/issues>
npm WARN auth_server@1.0.0 No repository field.
npm ERR! Linux 3.10.0-1160.el7.x86_64
npm ERR! argv "/home/william.chang/AAA/tools/nodejs-v6/target/bin/node" "/home/william.chang/AAA/tools/nodejs-v6/target/bin/npm" "install" "sqlite3@^4.0.0"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! sqlite3@4.2.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 7
npm ERR!
npm ERR! Failed at the sqlite3@4.2.0 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sqlite3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sqlite3
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sqlite3
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/william.chang/AAA/BBB/npm-debug.log

**Comment by daniellockyer** [comment]
Would you be able to try with v5.0.3? 🙂
