### ISSUE TITLE
sqlite3_bind_blob in node js

### ISSUE THREAD

**Issue by RamatovInomjon** [TryGhost/node-sqlite3#1499]
Hi there 
which peace of code replace sqlite3_bind_blob this function in node js? (it's from c/c++) I need to store float array in a blob format

// this is in c/c++
//float* features; my variable 

ret = sqlite3_bind_blob(stmt, 3, features,  face_feature_lenght*sizeof(float), NULL);
    if (ret != SQLITE_OK) {
        fprintf(stderr, "db bind blob fail, errcode[%d], errmsg[%s]\n", ret, sqlite3_errmsg(db));
        sqlite3_close(db);
        return -1;
    }

**Comment by daniellockyer** [comment]
Would you be able to reopen the issue with a the new issue template? 🙂
