### ISSUE TITLE
sqlite@4.2.0 security vulnerabilities

### ISSUE THREAD

**Issue by sovithkothari7** [TryGhost/node-sqlite3#1502]
Hi,

I have some security vulnerability issues in whitesource with the sqlite3@5.0.2 version and the npm audit recommended to downgrade the sqlite3 to 4.2.0 to resolve the vulnerabilities. Most of them got resolved but now with this version too, the security vulnerability is still not resolved.

-- sqlite3@4.2.0
  -- node-pre-gyp@0.11.0
    -- tar@4.4.19

-- sqlite3@4.2.0
  -- node-pre-gyp@0.11.0
    -- npmlog@4.1.2
      -- gauge@2.7.4
        -- strip-ansi@3.0.1
          -- ansi-regex@2.1.1

Please help me resolve these whitesource security vulnerabilities

**Comment by blubaustin** [comment]
See https://github.com/mapbox/node-sqlite3/pull/1503 for a fix

**Comment by soryy708** [comment]
Is this a duplicate of https://github.com/mapbox/node-sqlite3/issues/1493 ?

**Comment by soryy708** [comment]
Looks like a duplicate of https://github.com/mapbox/node-sqlite3/issues/1483

**Comment by daniellockyer** [comment]
These should be resolved in v5.0.3 so please update 🙂
