### ISSUE TITLE
DevTools crashes when using Electron 14 with sqlite3

### ISSUE THREAD

**Issue by lazytyper** [TryGhost/node-sqlite3#1504]
When using `require('sqlite3')`, DevTools is crashing at about every 3rd reload.

DevTools is showing this message:

![image](https://user-images.githubusercontent.com/5507298/135655440-1c35d756-a9ec-4f7c-88ee-ff6d92aab448.png)

On the terminal, this message appears:

```
[294941:1001/182033.220438:ERROR:CONSOLE(1)] "Target crashed", source: devtools://devtools/bundled/core/sdk/sdk.js (1)
``` 

If I knew how, I would try to get a debug message with more details.

**Comment by chinaofmelon** [comment]
I also met for this problem. I modify project [electron-quick-start](https://github.com/electron/electron-quick-start) for test, just modify render.js. And update electron for electron 14.x.y or electron 15.x.y. Then I found that when execute db.run(sql), and the sql can not be execute, the error occure. 

Source code is:

```
const {ipcRenderer} = require('electron')

const sqlite3 = require('sqlite3');


window.addEventListener('DOMContentLoaded', () => {
    const replaceText = (selector, text) => {
      const element = document.getElementById(selector)
      if (element) element.innerText = text
    } 

    ipcRenderer.invoke('some-name').then((result) => {
        replaceText('request-check', result.status)
        replaceText('failed-reason', result.reason)
    })
    
  })

let path = require('path');

var db = new sqlite3.Database(path.join(__dirname, './test.sqlcipher'));

db.serialize(function() {
  db.run("CREATE VIRTUAL TABLE IF NOT EXISTS messages_fts USING FTS4(user VARCHAR, msg TEXT)");

  try {
    db.run("CREATE VIRTUAL TABLE messages_fts USING FTS4(user VARCHAR, msg TEXT)"); // when run at here, the error occured.
  } catch(e) {
    console.log(`this is error information for create table ${e}`); // never be reached.
  }
});
```

I don't know how to get more information for that, any idea?

**Comment by BinarySpike** [comment]
I am experiencing the same issue:
```javascript
// preload.js
var sqlite3 = require("sqlite3").verbose();
var db = new sqlite3.Database(":memory:");
```

**Comment by BinarySpike** [comment]
Moving my the `require` into a function seems to have fixed it:
```javascript
// preload.js
const api = {
  runQuery(query, callback) {
    let sqlite3 = require("sqlite3").verbose();
    let db = new sqlite3.Database("game.db");
    db.all(query, (err, rows) => {
      callback(err, rows)
    });
    db.close();
  },
};

window.api = api;
```

using it from the HTML like:
```javascript
window.api.runQuery('select 1', console.log)
```

**Comment by KillerCodeMonkey** [comment]
i am just curious. i would rather import and connect to sqlite in the main process and just provide an api via IPCMain/Renderer.

so you would load the sqlite database in the main process and only once.

Add some wrappers like `IpcMain.on('query', (....) => db.runQuery(...))` This is just pseudo code -> remember to reply to the event :).
and in your preload script 
```
  query = (query: string) => IpcRenderer.sendSync/send('query', query)
```

And in general i do not know if it is working, when the db file is part of the actual package.
I would expect that you need to configure the place of the db (outside your app package) to have no problems when reading and writing. So you could have a "default" database in your package, and copy it on appstart somewhere else

**Comment by chinaofmelon** [comment]
I found maybe this problem is like this issue。https://github.com/nodejs/node-addon-api/issues/1011

When I use `electron-rebuild` to rebuild sqlite3 with `electron-rebuild -f -w sqlite3`, I notice that a folder named `napi-v{napi_build_version}-win32-x64`, Which should named as `napi-v3-win32-x64`, was created at `node_modules\sqlite3\lib\binding\napi-v{napi_build_version}-win32-x64`.  I don't get what's happened.

But when I copy file named `node_sqlite3.node` at `napi-v{napi_build_version}-win32-x64` and replace in `napi-v3-win32-x64`, The issue disappeared.

I will figure out how electron-rebuild does in next step.

**Comment by mantzaris** [comment]
> 

Is it not possible to place the require for sqlite3 in a module without causing this issue? Why does it not cause a problem when being used in main.js but this problem in every other place?

**Comment by qidizi** [comment]
> Moving my the `require` into a function seems to have fixed it:
> 
> ```js
> // preload.js
> const api = {
>   runQuery(query, callback) {
>     let sqlite3 = require("sqlite3").verbose();
>     let db = new sqlite3.Database("database.db");
>     db.all(query, (err, rows) => {
>       callback(err, rows)
>     });
>     db.close();
>   },
> };
> 
> window.api = api;
> ```
> 
> using it from the HTML like:
> 
> ```js
> window.api.runQuery('select 1', console.log)
> ```
> 
> *Edit However, putting it in a `DOMContentLoaded` listener causes the issue to happen ~randomly~ every _other_ reload.
> 
> ```js
> // preload.js
> var sqlite3 = null;
> var localdb = null;
> 
> window.addEventListener("DOMContentLoaded", () => {
>   sqlite3 = require('sqlite3').verbose();
>   localdb = new sqlite3.Database("local.db");
> });
> ```

also crashes

---   

The steps to reproduce are as follows:   
1.  Open a blank html through "electron";    
1.  Execute the following code through the console `+function(){require('sqlite3')['verbose']();}();`;  
1.  Refresh  
1.  Execute the code through the console again:  
1.  It crashes   

--- 
env:   

```text
macos  12.3 (21E230)  Darwin Kernel Version 21.4.0   

node -v   === v16.14.0


 "devDependencies": {
    "@electron-forge/cli": "^6.0.0-beta.63",
    "@electron-forge/maker-zip": "^6.0.0-beta.63",
    "electron": "^17.1.0",
    "sqlite3": "^5.0.2"
  },

```

**Comment by daniellockyer** [comment]
Would you be able to try with the new version - v5.0.3? We ship with NAPI v6 support now 🙂

**Comment by jjhbw** [comment]
@daniellockyer this seems to solve the issue for me! I'm on electron `18.0.4`. Thanks for the good work! 🙏

**Comment by stormsson** [comment]
Thank you for the fix!
