### ISSUE TITLE
Sqlite3 is not working with node 

### ISSUE THREAD

**Issue by islamhanafi94** [TryGhost/node-sqlite3#1505]
**Environment**
- Node v14.17.6
- ubuntu 20
- npm v7.24.0

Whenever I make `npm i sqlite3` and manage to use it I got an error module not found 

error message 

```
Error: Cannot find module '.../node_modules/sqlite3/lib/binding/napi-v3-linux-x64/node_sqlite3.node'

```  
don't even understand what is going on and why this is missing ?

any help please

**Comment by secure12** [comment]
Try `npm rebuild`. Then run `npm install sqlite3` again.

**Comment by daniellockyer** [comment]
Would you be able to try on v5.0.3? 🙂
