### ISSUE TITLE
CI: move to different CI provider

### ISSUE THREAD

**Issue by kewde** [TryGhost/node-sqlite3#1508]
Hi,

The build system for sqlite3 has been affected by the decision of Travis CI to stop their free service.
I'm currently attempting to move everything to AppVeyor as a temporary solution but ideally we would move to Github Actions.

In the mean time, no new builds can be published as I do not have access to AWS S3 nor can I enable Github Actions.
The AppVeyor instance should have the required credentials to allow us to publish builds which is the only reason that I am going down that route right now.

cc @springmeyer

**Comment by WikiRik** [comment]
@kewde maybe a move to CircleCI is an option? Since that's also used for the mapbox-gl-js repo; https://github.com/mapbox/mapbox-gl-js/blob/main/.circleci/config.yml
It would be nice if this (and the S3 credential issue) is resolved quickly so the new build can be published.

**Comment by daniellockyer** [comment]
This should now be done 🙂
