### ISSUE TITLE
what is the compiled version of node-sqlite3?

### ISSUE THREAD

**Issue by zhengtulymGh** [TryGhost/node-sqlite3#1512]
loadExtensions: 
Note: Make sure that the extensions you load are compiled or linked against the same version as node-sqlite3 was compiled. Version mismatches can lead to unpredictable behavior.

so what is the compiled version of node-sqlite3?

**Comment by wangfenjin** [comment]
It use 3.36.0 as fallback if there is no sqlite3 in the system
https://github.com/mapbox/node-sqlite3/blob/master/deps/sqlite-autoconf-3360000.tar.gz

**Comment by daniellockyer** [comment]
The library uses the bundled version in the form of prebuilt binaries or compiled on your machine. You can also build from source as documented in the README 🙂
