### ISSUE TITLE
 Error: Cannot find module '/node_modules/sqlite3/lib/binding/napi-v3-darwin-arm64/node_sqlite3.node'

### ISSUE THREAD

**Issue by jialinghui** [TryGhost/node-sqlite3#1513]
Error: Cannot find module '/node_modules/sqlite3/lib/binding/napi-v3-darwin-arm64/node_sqlite3.node'
![image](https://user-images.githubusercontent.com/29021622/137676794-e5e0b282-ba3d-45f9-84de-f6383df173f2.png)

**Comment by chenpx976** [comment]
+1

**Comment by lmarcelocc** [comment]
@jialinghui did you got any solution for your issue ? Have exactly the same.

**Comment by jialinghui** [comment]
> @jialinghui did you got any solution for your issue ? Have exactly the same.
You can try
`npm install --target_arch=arm64`

**Comment by lmarcelocc** [comment]
Thanks @jialinghui 

After running `npm install --target_arch=arm64` I went with a new error:
`/node_modules/@mapbox/mbtiles/node_modules/sqlite3/lib/binding/napi-v3-darwin-x64/node_sqlite3.node" has bad ELF magic: cffaedfe`

Let me know if you had this one as well and found any solution :)

**Comment by bitbw** [comment]
I have the same problem in electron product
 
pageage.json
```json
{
"sqlite3": "^5.0.2",
"electron": "^12.0.2",
"vue-cli-plugin-electron-builder": "^2.1.1"
}
```

**Comment by tonytechio** [comment]
I have the same issue. :(

**Comment by MrTob** [comment]
same here

**Comment by chenpx976** [comment]
https://github.com/mapbox/node-sqlite3/issues/1538#issuecomment-1037839683

**Comment by conglp90** [comment]
Same issue, i think in last day it work. May be by mac os update?

**Comment by spamshaker** [comment]
Same here

**Comment by sc00** [comment]
Same issue in vue electron project

**Comment by daniellockyer** [comment]
Would you be able to try with `sqlite3` v5.0.3? It should fix a lot of the build issues 🙂
