### ISSUE TITLE
Compile node-sqlite3 with enabled ICU support in electron app on Windows

### ISSUE THREAD

**Issue by maximborisov** [TryGhost/node-sqlite3#1517]
Hello.

Please, help! Since 2013, when the last issues about the ICU were closed, this problem is still very relevant. But [#70](https://github.com/mapbox/node-sqlite3/issues/70) has a very short answer.

Help me figure out how to compile node-sqlite3 with ICU support in electron app on Windows.

Thank you in advance!

**Comment by daniellockyer** [comment]
To be honest, https://github.com/TryGhost/node-sqlite3/issues/70#issuecomment-25844364 is probably the best answer we can give. You'll need to find out how to build libsqlite3 with ICU support in their docs 🙂
