### ISSUE TITLE
Python3 support

### ISSUE THREAD

**Issue by jrj2211** [TryGhost/node-sqlite3#1520]
Does this module support python3 for compiling? I'm installing it on an armv7 and there are not prebuilt binaries for it. I've checked that im installing the latest 5.0.3 but am still getting an error that python cannot be found:

```
make: Entering directory '/var/chroot/www/home/app/node_modules/sqlite3/build'
  CC(target) Release/obj.target/nothing/node_modules/node-addon-api/nothing.o
  AR(target) Release/obj.target/node_modules/node-addon-api/nothing.a
  COPY Release/nothing.a
  ACTION deps_sqlite3_gyp_action_before_build_target_unpack_sqlite_dep Release/obj/gen/sqlite-autoconf-3340000/sqlite3.c
/bin/sh: 1: python: not found
make: *** [deps/action_before_build.target.mk:13: Release/obj/gen/sqlite-autoconf-3340000/sqlite3.c] Error 127
```

Considering python 2's end of life was January 2020, I think python 3.5 and higher would make sense to support. 

There was an issue a while back for python3 but the OP closed it and it didn't have any feedback.

**Comment by daniellockyer** [comment]
This should be fixed in `sqlite3` v5.0.3 - let me know if you still experience issues 🙂
