### ISSUE TITLE
Segmentation Fault - Electron + Sqlite3

### ISSUE THREAD

**Issue by akkitech** [TryGhost/node-sqlite3#1521]
Sqlite3 Version: 5.0.2
Electron Version: 15.3.0

Hi, SQLite3 is working absolutely fine with the Electron dev build but causing Segmentation Fault crash with the Electron Production build. Any known issue with electron + sqlite3?

Thanks.

**Comment by daniellockyer** [comment]
Would you be able to try with v5.0.3? 🙂
