### ISSUE TITLE
like condition get empty field when there is a column is empty

### ISSUE THREAD

**Issue by zhengtulymGh** [TryGhost/node-sqlite3#1524]
sqlite3 version："^5.0.2"

As you can see in table Note，there are three rows。And the row which id is 1 has a empty column contentNote, the row which id is 3 has a empty column tite

| id | title      | contentNote | 
| ---|  ---       |    ---      |
| 1  | test title |             |
| 3  |            | test content|

https://i.stack.imgur.com/24Flf.png

I can get my expected results in DB Browser(SQLite) with sql:
```
SELECT Note.guid, Note.deleted, Note.stickTop, Note.title, Note.updateTime, Note.contentNote as content, Tag.name as tagName
FROM Note LEFT JOIN Tag ON Tag.noteGuid =  Note.guid
WHERE ((title is not NULL AND title !="" AND title LIKE '%test%') OR (content is not NULL AND content !="" AND content LIKE '%test%'))
```

[search result in DB Browser(SQLite)][2]

However, I get a empty column title in my node code with node-sqlite3
```
const dbPath = ''
const sqlite3 = require('sqlite3').verbose()
const db = new sqlite3.Database(dbPath)
function all(sql: string) {
        return new Promise((resolve, reject) => {
            db.all(sql, (err: Error, data: any) => {
                if (err) {
                    reject(err)
                } else {
                    resolve(data)
                }
            })
        })
    }
const sql = `SELECT title, contentNote as content
FROM Note
WHERE ((title is not NULL AND title LIKE '%test%') OR (content is not NULL AND content !="" AND content LIKE '%test%'))
`
all(sql).then(res => console.log(res))

```
I get the result as follow
```
[{
  title: "",
  content: ""
}, {
  title: "",
  content: "test content"
}]
```

What I expect to get is
```
[{
  title: "test title",
  content: ""
}, {
  title: "",
  content: "test content"
}]
```

**Comment by avinashkrishna613** [comment]
Hi @zhengtulymGh any progress on this issue? I tried to replicate the same, but its working fine in my case. It will be helpful if you provide some additional details(for ex - node version etc). By the way are there any leading or trailing spaces in that column name ?

**Comment by daniellockyer** [comment]
Closing as the issue is stale but please post a reproduction case and I can reopen it 🙂
