### ISSUE TITLE
Error while Installing node-sqlite3 with Node 14

### ISSUE THREAD

**Issue by NileshVirkar** [TryGhost/node-sqlite3#1531]
I am using node-sqlite3 version 5.0.2 in my project. I need to build my project for cross-platform so when I am building my project on Windows for Linux platform I am using following command,
`./node_modules/.bin/node-pre-gyp install --directory=./node_modules/sqlite3 --target_platform=linux--target_arch=x64 --target=14.0.0`
then I am getting the following error,

node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.11.0
node-pre-gyp info using node@14.0.0 | win32 | x64
node-pre-gyp info chdir ./node_modules/sqlite3
node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp ERR! install error
node-pre-gyp ERR! stack Error: Unsupported target version: 14.0.0
node-pre-gyp ERR! stack     at get_runtime_abi (D:\project\node_modules\node-pre-gyp\lib\util\versioning.js:173:23)

**Comment by soryy708** [comment]
Sounds like an issue with `node-pre-gyp`, not `sqlite3`.

**Comment by vikrant0526** [comment]
> Sounds like an issue with `node-pre-gyp`, not `sqlite3`.

Thanks for pointing that out but could you please elaborate on how to solve the issue 
Also, there seems to a high severity vulnerability with node-pre-gyp and is an [active issue](https://github.com/mapbox/node-sqlite3/issues/1536) on the repo as well

**Comment by soryy708** [comment]
Try downgrading NodeJS version to before 14, or upgrading to 15 or 16.
Or, try updating node-pre-gyp.

**Comment by loxator** [comment]
Try this `This worked for me `yarn config set python your-python3-path-here` . It worked for me but I am on Ubuntu 21.10 @vikrant0526

**Comment by daniellockyer** [comment]
Would you be able to try with `sqlite3` v5.0.3? 🙂
