### ISSUE TITLE
TypeError: sqlite3.Database is not a constructor with ES6 imports

### ISSUE THREAD

**Issue by thecodechemist99** [TryGhost/node-sqlite3#1532]
When importing sqlite3 via ES6 import statement, I get the error mentioned in the title, running `node@17.2.0` with `sqlite3@4.2.0`.

Code:
```js
import * as sqlite3 from 'sqlite3';
const db = new sqlite3.Database(':memory:');
```

Error:
```
❯ node index.js    
file:///Users/#######/Repos/######/index.js:3
const db = new sqlite3.Database(':memory:');
           ^

TypeError: sqlite3.Database is not a constructor
    at file:///Users/#######/Repos/######/index.js:3:12
    at ModuleJob.run (node:internal/modules/esm/module_job:195:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:331:24)
    at async loadESM (node:internal/process/esm_loader:88:5)
    at async handleMainPromise (node:internal/modules/run_main:65:12)

Node.js v17.2.0
```

**Comment by Digicrat** [comment]
For it to work, change your import to;  import sqlite3 from 'sqlite3';

I came across this same issue a few days ago myself. The above solution came from an older issue that I found with some more digging myself:
https://github.com/mapbox/node-sqlite3/issues/1461

**Comment by avinashkrishna613** [comment]
Along with changing 
import * as sqlite3 from 'sqlite3' to,
import sqlite3 from 'sqlite3'
If you still get an error saying, import can't work outside of module. Try adding, "type":"module" in package.json file

**Comment by daniellockyer** [comment]
^^ This looks correct to me - closing 🙂
