### ISSUE TITLE
Berkeley DB Support

### ISSUE THREAD

**Issue by subhajitm1993** [TryGhost/node-sqlite3#1541]
Berkeley DB has compatibility with sqlite3 API. The same tools that work with sqlite3, works perfectly with Berkeley DB. A similar thing I guess can happen with this node module, where I can use this module to communicate with the Berkley DB.

Any pointers on how that can be achieved?

**Comment by daniellockyer** [comment]
Sounds interesting but this project specifically targets SQLite right now. You might get somewhere with custom compiling and linking to Berkeley DB
