### ISSUE TITLE
Install against an external v3.38.0 SQlite results in v3.36.0

### ISSUE THREAD

**Issue by rogerdielrton** [TryGhost/node-sqlite3#1545]
Hello.
I need to use the 3.38 version of SQlite.
I'm using Ubuntu 20.04.4 LTS operating system and NodeJS version 14.15.2.

I downloaded Precompiled Binaries for Linux:
  https://www.sqlite.org/2022/sqlite-tools-linux-x86-3380000.zip
unzipped and installed into
  /opt/sqlite-tools-linux-x86-3380000

I followed this instructions:
  https://github.com/mapbox/node-sqlite3#source-install
$ sudo apt install libsqlite3-dev
$ npm install --save --build-from-source --sqlite=/opt/sqlite-tools-linux-x86-3380000 --python=/usr/bin/python3.8

I tested it creating a database with Node and sqlite3.
But, the create database has 3.36.0 version.

**Comment by ErisDS** [comment]
Would you be able to try with sqlite3 v5.0.3? 🙂
