### ISSUE TITLE
Linux-Arm64 issue

### ISSUE THREAD

**Issue by programmin1** [TryGhost/node-sqlite3#1551]
I have had issues building this for Librem phone, as described here... do you know if this is yet a known issue? Not sure if this should just be appended to some arm64/M1 issue if that is similar.

https://github.com/ezra-bible-app/ezra-bible-app/discussions/644#discussioncomment-2362860

**Comment by daniellockyer** [comment]
Prebuilt binaries should be available in the next release 🙂 If you still have an issue with `node-sqlite3`, let me know 🙂
