### ISSUE TITLE
Missing some(electron, arm64) prebuilt binaries via node-pre-gyp

### ISSUE THREAD

**Issue by ipetrovic11** [TryGhost/node-sqlite3#1553]
We are using Sqlite3 with electron and building it both for x64 and arm64 platforms(universal).

We noticed recently that prebuilt binaries are missing and that we are getting 403 errors when downloading.

This is not available:
https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.1.1/electron-v16.0-darwin-arm64.tar.gz
https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.2.0/electron-v16.0-darwin-arm64.tar.gz
https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v5.0.2/napi-v3-darwin-arm64.tar.gz

But this is:
https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v5.0.2/napi-v3-darwin-x64.tar.gz

It worked last week without any issues.

**Comment by austinkloske22** [comment]
Is there a work-around or expected fix for this? My development is frozen because I have some pretty deep sqlite3 dependencies.

**Comment by ipetrovic11** [comment]
@austinkloske22 if you have everything properly set, it can be built from the source.

**Comment by daniellockyer** [comment]
Linux ARM64 binaries will be shipped in the next release. Unfortunately I haven't got a way of building macOS ARM64 binaries in CI right now 😕
