### ISSUE TITLE
"The sqlite3 module works with:  Node.js v11.x, v12.x, v13.x and v14.x." but current LTS is 16

### ISSUE THREAD

**Issue by Pomax** [TryGhost/node-sqlite3#1555]
Can the README.md be updated to explain which module should we use for Node v15, v16, v17, and (very soon) v18?

**Comment by lehni** [comment]
I was just wondering the same! And yet another unexpected place to meet you again @Pomax ;)

**Comment by garyburgmann** [comment]
try: https://github.com/TryGhost/node-sqlite3/issues/1556#issuecomment-1096124246

**Comment by Pomax** [comment]
this issue is for getting the actual docs updated, so that no one else needs to hit up `/issues` for this project.

**Comment by daniellockyer** [comment]
@Pomax Thanks for the note, I'm doing a big overhaul of the repo and docs so I'll be sure to do this too 🙂

**Comment by daniellockyer** [comment]
Docs have been updated - let me know if they're still ambiguous 🙂
