### ISSUE TITLE
PSA: Workaround for build errors on Node 16.14+ or ARM: try `@vscode/sqlite3`

### ISSUE THREAD

**Issue by timoxley** [TryGhost/node-sqlite3#1556]
Posting here for visibility until mapbox pops out a new `sqlite3` release.

Try using `@vscode/sqlite3` instead of `sqlite3`.

https://github.com/microsoft/vscode-node-sqlite3

Worked for me!

#### Possibly Related

* https://github.com/mapbox/node-sqlite3/issues/1538
* https://github.com/mapbox/node-sqlite3/issues/1552
* https://github.com/mapbox/node-sqlite3/issues/1553
* https://github.com/mapbox/node-sqlite3/issues/1551
* https://github.com/mapbox/node-sqlite3/issues/1540
* https://github.com/mapbox/node-sqlite3/issues/1554
* https://github.com/mapbox/node-sqlite3/issues/1537

**Comment by garyburgmann** [comment]
@timoxley I had success with Docker today

```
ARG base_image=node:16-alpine

# https://github.com/nodejs/docker-node/blob/main/docs/BestPractices.md#node-gyp-alpine
FROM $base_image as builder

## Install build toolchain, install node deps and compile native add-ons
RUN apk add --no-cache --update python3 make g++
# needed for build of sqlite with node-gyp
RUN ln -s $(which python3) /usr/local/bin/python
WORKDIR /builder
COPY . .
# install node_modules here due to node-gyp dependencies
RUN npm ci
...
```

**Comment by carlosfaria94** [comment]
Ghost team have taken the node-sqlite3 development! Great news for everyone! 🙏🚀

**Comment by daniellockyer** [comment]
This should be fixed in `sqlite3` v5.0.3 - let me know if you still experience issues 🙂

**Comment by jose-nunez** [comment]
I had problems with `v5.0.2`
`v5.0.3` worked for me on Mac M1 - Node v16

**Comment by daniellockyer** [comment]
FYI v5.1.1 now comes with prebuilt Darwin ARM64 binaries 🙂 https://github.com/TryGhost/node-sqlite3/releases/tag/v5.1.1
