### ISSUE TITLE
Query problem

### ISSUE THREAD

**Issue by dresende** [TryGhost/node-sqlite3#157]
I'm not sure how to categorize this but what happens is better shown in an example. I run some similar queries to this:

``` sql
SELECT `id`, `name`, `age` FROM `person`;
SELECT `id`, `name`, `age` FROM `person` LIMIT 9223372036854775807 OFFSET 0;
SELECT `id`, `name`, `age` FROM `person` LIMIT 9223372036854775807 OFFSET 1;
SELECT `id`, `name`, `age` FROM `person` LIMIT 9223372036854775807 OFFSET 2;
```

Knowing the first results, it's simple to know what to expect from the others. In my example, I get 3 results for the first query. So for the other queries I get 3, 2 and 1 respectively.

What is odd is that if I do...

``` sql
SELECT `id`, `name`, `age` FROM `person` ORDER BY `age`ASC LIMIT 9223372036854775807 OFFSET 2;
```

...I get nothing. Am I doing something stupid? I just asked for an order..

I use node node@0.8.x and node@0.10.x with sqlite3@2.1.10. Using 2.1.9 and 2.1.8 fail. 2.1.7 and 2.1.5 work fine.

Is it something about the limit !?

**Comment by daniellockyer** [comment]
I suspect this is no longer relevant/a problem 🙂
