### ISSUE TITLE
Prebuilt linux x86

### ISSUE THREAD

**Issue by xPaw** [TryGhost/node-sqlite3#1573]
Not sure if this is intentional, but it seems to be missing, it should be simple to add it in the gh action.

**Comment by daniellockyer** [comment]
Does Node.js provide x86 binaries for Linux? 🤔

**Comment by xPaw** [comment]
There's https://unofficial-builds.nodejs.org/ which does appear to provide them.

But if no one actually uses it, then there's probably no point in adding it.

**Comment by daniellockyer** [comment]
I would tend to agree 🙂 I don't think it's worth adding a build for it but if there's sufficient demand in the future, we can revisit it

**Comment by tmfksoft** [comment]
Of the back of this,
I'm actually trying to do exactly this with the following project:
https://github.com/AmyrAhmady/samp-node

This runs version 16.13.0 of Node in 32-Bit.
The arch is a limitation of SA-MP which the plugin is for.

I've been able to compile sqlite3 for x86/ia32 but when trying to use it I run in the following:

```
node:internal/modules/cjs/loader:1183
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: /media/server/node_modules/sqlite3/lib/binding/napi-v6-linux-glibc-ia32/node_sqlite3.node: undefined symbol: napi_create_error
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1183:18)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/media/server/node_modules/sqlite3/lib/sqlite3-binding.js:4:17)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
  code: 'ERR_DLOPEN_FAILED'
}
Thrown at:
    at Module._extensions..node (node:internal/modules/cjs/loader:1183:18)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at /media/server/node_modules/sqlite3/lib/sqlite3-binding.js:4:17
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Module._load (node:internal/modules/cjs/loader:822:12)```

I'm unsure if this is something that lies with that project or sqlite3.

Would I be able to get some pointers on this?

**Comment by heathen-pwn** [comment]
> [tmfksoft](/tmfksoft)

Having the same cross-platform installation issue; 

How to reproduce:

1. Be on a windows platform
2. npm i sqlite3
3. ./node_modules/.bin/node-pre-gyp install --directory=./node_modules/sqlite3 --target_platform=linux --target_arch=x64 -target_libc=glibc
4. ERROR 

`[ERROR] "server" package loading failed, exception stack:                                                                                                                                                                                    Error: /shared/node_modules/sqlite3/lib/binding/napi-v6-linux-glibc-x64/node_sqlite3.node: undefined symbol: napi_create_error                                                                                                                   at Object.Module._extensions..node (internal/modules/cjs/loader.js:1127:18)                                                                                                                                                                  at Module.load (internal/modules/cjs/loader.js:941:32)                                                                                                                                                                                       at Function.Module._load (internal/modules/cjs/loader.js:782:14)                                                                                                                                                                             at Module.require (internal/modules/cjs/loader.js:965:19)                                                                                                                                                                                    at require (internal/modules/cjs/helpers.js:88:18)                                                                                                                                                                                           at Object.<anonymous> (/shared/node_modules/sqlite3/lib/sqlite3-binding.js:4:17)                                                                                                                                                             at Module._compile (internal/modules/cjs/loader.js:1076:30)                                                                                                                                                                                  at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)                                                                                                                                                                    at Module.load (internal/modules/cjs/loader.js:941:32)                                                                                                                                                                                       at Function.Module._load (internal/modules/cjs/loader.js:782:14)          `
