### ISSUE TITLE
4.2.0 support

### ISSUE THREAD

**Issue by markmadlangbayan** [TryGhost/node-sqlite3#1583]
We'd like to use the latest version, but for now we are stuck with 4.2.0.  Recently we're not able to install 4.2.0 and it's complaining it's not available from the server.  I think it might have to do with the latest transition to the new maintainers.

Anyway I can get around this problem?

![image](https://user-images.githubusercontent.com/5464773/164283198-7d0c7107-e3ba-4c93-a915-ebc2e495baef.png)

**Comment by daniellockyer** [comment]
Hey @markmadlangbayan 👋🏻 We've been focussed on stabilising the v5.x build as it's the latest major. Unfortunately, the binaries I have available for v4.2.0 don't include `node-v83-darwin-x64`, so I'm lead to believe they don't exist for that version. It's very unlikely we're going to go back and generate binaries for it given the CI requirements.

Out of curiosity, how come you're stuck on 4.2.0? 🙂
