### ISSUE TITLE
API functions to check autocommit status, enable and disable autocommit

### ISSUE THREAD

**Issue by cshong87** [TryGhost/node-sqlite3#1603]
### Summary

[https://www.sqlite.org/c3ref/get_autocommit.html](https://www.sqlite.org/c3ref/get_autocommit.html)

As my programming exercise, and for learning purpose, I try to create an SQL client application that allow users to execute SQL queries.

By reading the documentation in above link, I understand that in SQLite, autocommit is enabled by default.

I also understand that I can disable autocommit by executing "BEGIN" statement, and enable autocommit by executing "COMMIT" or "ROLLBACK" statement. However, I cannot require my application users to manually execute these statements.

However, node-sqlite3 module does not provide an API to check autocommit status. My application need this feature.

### Proposed implementation

The native SQLite C/C++ library has a function called "sqlite3_get_autocommit()" to check the autocommit status.

So, I request the developers of node-sqlite3 module to implement the following API functions:

1. An API function to check whether autocommit has been enabled or not.
2. The API functions to enable/disable autocommit.
3. An event that will be emitted when the autocommit status change. This event should be emitted when executing statement "BEGIN", "COMMIT", "ROLLBACK", and when the API functions for enable/disable autocommit being called. 
4. An API function that allow application to subscribe to the event mentioned in no. 3 above. For example, something like the following:

Database.on('autocommit-status-change', callback(new_status))

**Comment by daniellockyer** [comment]
I'm going to close this for now as the request seems very niche. However, if there's more demand, and a PR, I will merge it 🙂
