### ISSUE TITLE
Asynchronous behaviour of query methods

### ISSUE THREAD

**Issue by OxNinja** [TryGhost/node-sqlite3#1611]
### Issue Summary

Same as #1408 but for the queries functions. Callbacks seems to be called asynchronously but the method itself returns before the callback.

```js
const sqlite = require("sqlite3").verbose();

class DB {
  constructor(path) {
    this.db = new sqlite.Database(path);
    this.result = null;
  }

  async query(sql) {
    this.db.all(sql, (err, rows) => {
      this.result = rows;
      console.log("a", this.result); // called after
    });
    console.log("b", this.result); // called first
  }
};

new DB("mydb.db").query("select * from mytable");
```
```node
b null
a [
  {
    // actual result
  }
]
```

I don't know if this is a bug, but it is not very handy to retrieve the result of a query.

### Steps to Reproduce

1. Run the script above

### Version

`3.38.4`

### Node.js Version

`16.15.0`

### How did you install the library?

`npm i --save "sqlite3"`

**Comment by daniellockyer** [comment]
Hey @OxNinja 👋🏻 This behavious seems expected to me? And of any asynchronous library. If you need to wait for the result before continuing, you need to use Promises 🙂
