### ISSUE TITLE
Binaries: Access denied

### ISSUE THREAD

**Issue by ormanlis** [TryGhost/node-sqlite3#1616]
### Issue Summary

node-pre-gyp http GET https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v5.0.2/napi-v3-darwin-arm64.tar.gz
node-pre-gyp http 403 https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v5.0.2/napi-v3-darwin-arm64.tar.gz
node-pre-gyp WARN Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v5.0.2/napi-v3-darwin-arm64.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for sqlite3@5.0.2 and node@17.4.0 (node-v102 ABI, unknown) (falling back to source compile with node-gyp) 

### Steps to Reproduce

yarn install

### Version

5.0.2

### Node.js Version

v17.4.0

### How did you install the library?

macOS m1

**Comment by daniellockyer** [comment]
Hey @ormanlis - there are no distributed binaries for ARM64 in v5.0.2, nor the latest at the time of writing. If you update to the latest version, you should be able to compile the library and use that

**Comment by slamdev** [comment]
@daniellockyer any particular reason to skip releasing Darwin ARM64 binaries? can we (community) help\contribute somehow?

**Comment by daniellockyer** [comment]
@slamdev No reason! I'd very much love to add them

I've got a branch here, but the binaries get the quarantine zatte flag when I download them - which clearly isn't ideal for end users 

https://github.com/TryGhost/node-sqlite3/pull/1594

**Comment by daniellockyer** [comment]
I'm going to open an issue detailing the problem 🙂
