### ISSUE TITLE
Is it possible to open with this library a sqlite database that has a password? ( I have the password)

### ISSUE THREAD

**Issue by RodrigoBJJ94** [TryGhost/node-sqlite3#1619]
### Summary

const sqlite3 = require('sqlite3');
const sqlite = require('sqlite');async function main() {
  try {
    const db = await sqlite.open({ filename: './LocalData.db', driver: sqlite3.Database });
    const rows = await db.all('SELECT * FROM ProductionData');
    console.log(rows);
    await db.close();
  } catch (error) {
    console.log(error);
  }
}
main();

### Proposed implementation

Is it possible to open with this library a sqlite database that has a password? ( I have the password)

**Comment by daniellockyer** [comment]
If you're using SQLCipher, there's a blog post here detailing how to use it: https://coolaj86.com/articles/building-sqlcipher-for-node-js-on-raspberry-pi-2/

Otherwise, this issue is not detailed enough for me to know your setup. Please re-open an issue if there's a bug or feature request 🙂
