### ISSUE TITLE
Test failure in test/async_calls.test.js with Mac intel binary

### ISSUE THREAD

**Issue by springmeyer** [TryGhost/node-sqlite3#1620]
### Issue Summary

I noticed that some tests fail with the default Mac binary on my system that do NOT fail with a source compile. The test in question I notice was added by @alexanderfloh in https://github.com/TryGhost/node-sqlite3/pull/1511. I don't have the time right now to debug deeply, but figured it would still be useful to report this.

The test failure is:

```

  async_hooks
    1) should support performance measuring with async hooks


  0 passing (7ms)
  1 failing

  1) async_hooks
       should support performance measuring with async hooks:

      Uncaught AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:

0 !== 14

      + expected - actual

      -0
      +14
      
      at /Users/danespringmeyer/projects/node-sqlite3-ghost/test/async_calls.test.js:28:20
      at Statement.errBack (lib/sqlite3.js:15:21)
```

### Steps to Reproduce

```
git clone git@github.com:TryGhost/node-sqlite3 node-sqlite3
cd node-sqlite3
npm install # which installs `lib/binding/napi-v6-darwin-unknown-x64/node_sqlite3.node`
npm test
```

This givens the above test failure. All tests pass however when I do:

```
npm install --build-from-source 
npm test
```

### Version

git clone from master at 1cd51ea6b68

### Node.js Version

v18.2.0

### How did you install the library?

macOS Monterey (12.4) 3.5 Ghz Dual-Core Intel Core i7

**Comment by Flarna** [comment]
I think the failing test was added on main after the last release (5.0.8 as of writing).

Are you using tests from tip of master together was a release here where the corresponding fix is not yet included?

**Comment by springmeyer** [comment]
@Flarna excellent, thanks for noticing that subtlety. That explains it! Closing then, as it seems like a pretty safe bet that binaries created from master (and distributed to others) are going to work with tests from master.
