### ISSUE TITLE
db.exec error when create in class 

### ISSUE THREAD

**Issue by joebnb** [TryGhost/node-sqlite3#1624]
### Issue Summary

use Class constructor to init a db,may got a error

### Steps to Reproduce

```
class Test{
    constructor(){ // this function can's use async
        this.init()
    }

   init(){
        this.db = sqlite3.database(options)
        this.db.exec('create table querys')  // this command may not finish ,need sync mode
   }

    doQuery(){
        this.db(query via orm)
    }
}
```

```
const db = new Test();
db.doQuery(); // error occur because table create may not finish in constructor
```

### Version

latest

### Node.js Version

latest

### How did you install the library?

via npm

**Comment by daniellockyer** [comment]
This library is asynchronous, so you need to use `.serialize` or use the callback within `exec`.

Closing as this is expected behaviour 🙂
