### ISSUE TITLE
Can not install sqlite3 on my Mac using Node v14.19.0

### ISSUE THREAD

**Issue by clifton311** [TryGhost/node-sqlite3#1629]
### Issue Summary

I am getting errors installing `sqlite3` on my Mac. I have been using `npm install sqlite3` and I am getting the error message below. I alternatively tried installing sqlite3@ 5.0.0 because I read elsewhere that installing the 5.0.0 version worked for others. However, I am still getting the same error.

### Relevant logs or output

node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp WARN Pre-built binaries not installable for sqlite3@5.0.11 and node@14.19.0 (node-v83 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Hit error connect ETIMEDOUT 140.82.114.4:443 
  CC(target) Release/obj.target/nothing/node_modules/node-addon-api/nothing.o
  LIBTOOL-STATIC Release/nothing.a
env: python: No such file or directory
make: *** [Release/nothing.a] Error 127
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:282:12)
gyp ERR! System Darwin 21.6.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/cxho3/Sandbox/service-virtualization-framework/node_modules/sqlite3/lib/binding/napi-v6-darwin-unknown-x64/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/Users/cxho3/Sandbox/service-virtualization-framework/node_modules/sqlite3/lib/binding/napi-v6-darwin-unknown-x64" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=6" "--node_napi_label=napi-v6"
gyp ERR! cwd /Users/cxho3/Sandbox/service-virtualization-framework/node_modules/sqlite3
gyp ERR! node -v v14.19.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/cxho3/Sandbox/service-virtualization-framework/node_modules/sqlite3/lib/binding/napi-v6-darwin-unknown-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/Users/cxho3/Sandbox/service-virtualization-framework/node_modules/sqlite3/lib/binding/napi-v6-darwin-unknown-x64 --napi_version=8 --node_abi_napi=napi --napi_build_version=6 --node_napi_label=napi-v6' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/cxho3/Sandbox/service-virtualization-framework/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1058:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5)
node-pre-gyp ERR! System Darwin 21.6.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/Users/cxho3/Sandbox/service-virtualization-framework/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/cxho3/Sandbox/service-virtualization-framework/node_modules/sqlite3
node-pre-gyp ERR! node -v v14.19.0
node-pre-gyp ERR! node-pre-gyp -v v0.17.0
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/cxho3/Sandbox/service-virtualization-framework/node_modules/sqlite3/lib/binding/napi-v6-darwin-unknown-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/Users/cxho3/Sandbox/service-virtualization-framework/node_modules/sqlite3/lib/binding/napi-v6-darwin-unknown-x64 --napi_version=8 --node_abi_napi=napi --napi_build_version=6 --node_napi_label=napi-v6' (1)
npm WARN @apidevtools/swagger-parser@10.1.0 requires a peer of openapi-types@>=7 but none is installed. You must install peer dependencies yourself.

### Version

5.0.3

### Node.js Version

v14.19.0

### How did you install the library?

maxOS Monterey Versions 12.5

**Comment by daniellockyer** [comment]
Hey @clifton311, do you have Python 3 installed?

**Comment by clifton311** [comment]
@daniellockyer Yes, I just checked and I have version Python 3.8.9 installed.

**Comment by daniellockyer** [comment]
` env: python: No such file or directory` indicates there's something wrong with your local env 🤔

**Comment by chee** [comment]
`python3` might not have a symlink at`python`. if you're using MacPorts you can set python3 to be your default `python` with `sudo port select --set python python310`.

otherwise you could symlink `python3` to `python` somewhere in your `PATH` and see what happes

**Comment by clifton311** [comment]
is python required to install sqlite3?

**Comment by daniellockyer** [comment]
It's not a direct dependency of this project, but it's used by node-gyp

**Comment by daniellockyer** [comment]
That being said, the prebuilt binaries for the latest versions exist for `napi-v6-darwin-unknown-x64`, so I'm surprised that's not working for you

**Comment by RajatDhupar** [comment]
i am getting this error too with knex.. any solutions?

**Comment by daniellockyer** [comment]
Closing this issue as I believe https://github.com/TryGhost/node-sqlite3/issues/1629#issuecomment-1205390514 solves the problem here 🙂
