### ISSUE TITLE
Cannot install sqlite3 in electron project - linux ubuntu 22

### ISSUE THREAD

**Issue by duendeee** [TryGhost/node-sqlite3#1634]
### Issue Summary

I can't install sqlite3 in an electron project. Apparently it's not a problem with python or NAPI version, after searching a lot I didn't find any problem like this.

The issue seems to happen at this moment:

ACTION deps_sqlite3_gyp_action_before_build_target_unpack_sqlite_dep Release/obj/gen/sqlite-autoconf-3390200/sqlite3.c
/bin/sh: 1: Syntax error: "(" unexpected

### Relevant logs or output

electron-rebuild assuming is prebuildify powered: lzma-native +0ms
  electron-rebuild Checking for prebuilds for "lzma-native" +0ms
  electron-rebuild Found prebuilt Node-API module in /home/duende/Downloads/my-new-app(1)/my-new-app/node_modules/lzma-native/prebuilds/linux-x64" +2ms
⠏ Building module: lzma-native, Completed: 1  electron-rebuild rebuilding sqlite3 with args [
  'node',
  'node-gyp',
  'rebuild',
  '--runtime=electron',
  '--target=20.1.1',
  '--arch=x64',
  '--dist-url=https://www.electronjs.org/headers',
  '--build-from-source',
  '--verbose',
  '--module_name=node_sqlite3',
  '--module_path=/home/duende/Downloads/my-new-app(1)/my-new-app/node_modules/sqlite3/lib/binding/napi-v{napi_build_version}-linux-glibc-x64',
  '--host=https://github.com/TryGhost/node-sqlite3/releases/download/',
  '--remote_path=v5.0.11',
  '--package_name=napi-v{napi_build_version}-linux-glibc-x64.tar.gz'
] +0ms
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
⠋ Building module: sqlite3, Completed: 1gyp verb command configure []
gyp verb download using dist-url https://www.electronjs.org/headers
gyp verb find Python checking Python explicitly set from command line or npm configuration
gyp verb find Python - "--python=" or "npm config get python" is "/usr/bin/python3"
gyp verb find Python - executing "/usr/bin/python3" to get executable path
gyp verb find Python - executable path is "/usr/bin/python3"
gyp verb find Python - executing "/usr/bin/python3" to get version
⠙ Building module: sqlite3, Completed: 1gyp verb find Python - version is "3.10.4"
gyp info find Python using Python version 3.10.4 found at "/usr/bin/python3"
gyp verb get node dir compiling against --target node version: 20.1.1
gyp verb command install [ '20.1.1' ]
gyp verb download using dist-url https://www.electronjs.org/headers
gyp verb install input version string "20.1.1"
gyp verb install installing version: 20.1.1
gyp verb install --ensure was passed, so won't reinstall if already installed
⠹ Building module: sqlite3, Completed: 1gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 20.1.1
gyp verb build dir attempting to create "build" dir: /home/duende/Downloads/my-new-app(1)/my-new-app/node_modules/sqlite3/build
gyp verb build dir "build" dir needed to be created? Yes
gyp verb python symlink creating symlink to "/usr/bin/python3" at "/home/duende/Downloads/my-new-app(1)/my-new-app/node_modules/sqlite3/build/node_gyp_bins/python3"
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: /home/duende/Downloads/my-new-app(1)/my-new-app/node_modules/sqlite3/build/config.gypi
gyp verb config.gypi checking for gypi file: /home/duende/Downloads/my-new-app(1)/my-new-app/node_modules/sqlite3/config.gypi
gyp verb common.gypi checking for gypi file: /home/duende/Downloads/my-new-app(1)/my-new-app/node_modules/sqlite3/common.gypi
gyp verb gyp gyp format was not specified; forcing "make"
gyp info spawn /usr/bin/python3
gyp info spawn args [
gyp info spawn args   '/home/duende/Downloads/my-new-app(1)/my-new-app/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/duende/Downloads/my-new-app(1)/my-new-app/node_modules/sqlite3/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/duende/Downloads/my-new-app(1)/my-new-app/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/duende/.electron-gyp/20.1.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/duende/.electron-gyp/20.1.1',
gyp info spawn args   '-Dnode_gyp_dir=/home/duende/Downloads/my-new-app(1)/my-new-app/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/duende/.electron-gyp/20.1.1/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/duende/Downloads/my-new-app(1)/my-new-app/node_modules/sqlite3',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
⠴ Building module: sqlite3, Completed: 1gyp verb command build []
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir /home/duende/.electron-gyp/20.1.1
gyp verb `which` succeeded for `make` /usr/bin/make
gyp verb bin symlinks adding symlinks (such as Python), at "/home/duende/Downloads/my-new-app(1)/my-new-app/node_modules/sqlite3/build/node_gyp_bins", to PATH
gyp info spawn make
gyp info spawn args [ 'V=1', 'BUILDTYPE=Release', '-C', 'build' ]
make: Entrando no diretório '/home/duende/Downloads/my-new-app(1)/my-new-app/node_modules/sqlite3/build'
  cc -o Release/obj.target/nothing/node_modules/node-addon-api/nothing.o ../node_modules/node-addon-api/nothing.c '-DNODE_GYP_MODULE_NAME=nothing' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-DV8_DEPRECATION_WARNINGS' '-DV8_IMMINENT_DEPRECATION_WARNINGS' '-D_GLIBCXX_USE_CXX11_ABI=1' '-DELECTRON_ENSURE_CONFIG_GYPI' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DUSING_ELECTRON_CONFIG_GYPI' '-DV8_COMPRESS_POINTERS' '-DV8_COMPRESS_POINTERS_IN_SHARED_CAGE' '-DV8_ENABLE_SANDBOX' '-DV8_SANDBOXED_POINTERS' '-DV8_31BIT_SMIS_ON_64BIT_ARCH' '-DV8_REVERSE_JSARGS' '-D__STDC_FORMAT_MACROS' '-DOPENSSL_NO_PINSHARED' '-DOPENSSL_THREADS' '-DOPENSSL_NO_ASM' -I/home/duende/.electron-gyp/20.1.1/include/node -I/home/duende/.electron-gyp/20.1.1/src -I/home/duende/.electron-gyp/20.1.1/deps/openssl/config -I/home/duende/.electron-gyp/20.1.1/deps/openssl/openssl/include -I/home/duende/.electron-gyp/20.1.1/deps/uv/include -I/home/duende/.electron-gyp/20.1.1/deps/zlib -I/home/duende/.electron-gyp/20.1.1/deps/v8/include  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -m64 -O3 -fno-omit-frame-pointer  -MMD -MF ./Release/.deps/Release/obj.target/nothing/node_modules/node-addon-api/nothing.o.d.raw   -c
⠦ Building module: sqlite3, Completed: 1  rm -f Release/obj.target/node_modules/node-addon-api/nothing.a && ar crs Release/obj.target/node_modules/node-addon-api/nothing.a Release/obj.target/nothing/node_modules/node-addon-api/nothing.o
  ln -f "Release/obj.target/node_modules/node-addon-api/nothing.a" "Release/nothing.a" 2>/dev/null || (rm -rf "Release/nothing.a" && cp -af "Release/obj.target/node_modules/node-addon-api/nothing.a" "Release/nothing.a")
  LD_LIBRARY_PATH=/home/duende/Downloads/my-new-app(1)/my-new-app/node_modules/sqlite3/build/Release/lib.host:/home/duende/Downloads/my-new-app(1)/my-new-app/node_modules/sqlite3/build/Release/lib.target:$LD_LIBRARY_PATH; export LD_LIBRARY_PATH; cd ../deps; mkdir -p /home/duende/Downloads/my-new-app(1)/my-new-app/node_modules/sqlite3/build/Release/obj/gen/sqlite-autoconf-3390200; node ./extract.js ./sqlite-autoconf-3390200.tar.gz "/home/duende/Downloads/my-new-app(1)/my-new-app/node_modules/sqlite3/build/Release/obj/gen"
/bin/sh: 1: Syntax error: "(" unexpected
make: *** [deps/action_before_build.target.mk:13: Release/obj/gen/sqlite-autoconf-3390200/sqlite3.c] Error 2
make: Exiting directory '/home/duende/Downloads/my-new-app(1)/my-new-app/node_modules/sqlite3/build'
✖ Rebuild Failed

An unhandled error occurred inside electron-rebuild
node-gyp failed to rebuild '/home/duende/Downloads/my-new-app(1)/my-new-app/node_modules/sqlite3'.
For more information, rerun with the DEBUG environment variable set to "electron-rebuild".

Error: `make` failed with exit code: 2

Error: node-gyp failed to rebuild '/home/duende/Downloads/my-new-app(1)/my-new-app/node_modules/sqlite3'.
For more information, rerun with the DEBUG environment variable set to "electron-rebuild".

Error: `make` failed with exit code: 2

    at NodeGyp.rebuildModule (/home/duende/Downloads/my-new-app(1)/my-new-app/node_modules/electron-rebuild/lib/src/module-type/node-gyp.js:120:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ModuleRebuilder.rebuildNodeGypModule (/home/duende/Downloads/my-new-app(1)/my-new-app/node_modules/electron-rebuild/lib/src/module-rebuilder.js:98:9)
    at async ModuleRebuilder.rebuild (/home/duende/Downloads/my-new-app(1)/my-new-app/node_modules/electron-rebuild/lib/src/module-rebuilder.js:128:14)
    at async Rebuilder.rebuildModuleAt (/home/duende/Downloads/my-new-app(1)/my-new-app/node_modules/electron-rebuild/lib/src/rebuild.js:149:13)
    at async Rebuilder.rebuild (/home/duende/Downloads/my-new-app(1)/my-new-app/node_modules/electron-rebuild/lib/src/rebuild.js:112:17)
    at async /home/duende/Downloads/my-new-app(1)/my-new-app/node_modules/electron-rebuild/lib/src/cli.js:158:9

### Running "npm start" on project ###

npm start

> my-new-app@1.0.0 start
> cross-env NODE_ENV=development electron-forge start

✔ Checking your system
✔ Locating Application
⠸ Preparing native dependencies: 0 / 1make: Entrando no diretório '/home/duende/Downloads/my-new-app(1)/my-new-app/node_modules/sqlite3/build'
  CC(target) Release/obj.target/nothing/node_modules/node-addon-api/nothing.o
  AR(target) Release/obj.target/node_modules/node-addon-api/nothing.a
⠼ Preparing native dependencies: 0 / 1  COPY Release/nothing.a
  ACTION deps_sqlite3_gyp_action_before_build_target_unpack_sqlite_dep Release/obj/gen/sqlite-autoconf-3390200/sqlite3.c
/bin/sh: 1: Syntax error: "(" unexpected
make: *** [deps/action_before_build.target.mk:13: Release/obj/gen/sqlite-autoconf-3390200/sqlite3.c] Erro 2
make: Saindo do diretório '/home/duende/Downloads/my-new-app(1)/my-new-app/node_modules/sqlite3/build'
✖ Preparing native dependencies: 0 / 1

An unhandled error has occurred inside Forge:
node-gyp failed to rebuild '/home/duende/Downloads/my-new-app(1)/my-new-app/node_modules/sqlite3'.
For more information, rerun with the DEBUG environment variable set to "electron-rebuild".

### Installing from --build-from-source
npm WARN deprecated core-js@2.6.12: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.
npm ERR! code 1
npm ERR! path /home/duende/Downloads/my-new-app(1)/my-new-app/node_modules/sqlite3
npm ERR! command failed
npm ERR! command sh /tmp/install-ac1adf2c.sh
npm ERR! make: Entrando no diretório '/home/duende/Downloads/my-new-app(1)/my-new-app/node_modules/sqlite3/build'
npm ERR!   CC(target) Release/obj.target/nothing/node_modules/node-addon-api/nothing.o
npm ERR!   AR(target) Release/obj.target/node_modules/node-addon-api/nothing.a
npm ERR!   COPY Release/nothing.a
npm ERR!   ACTION deps_sqlite3_gyp_action_before_build_target_unpack_sqlite_dep Release/obj/gen/sqlite-autoconf-3390200/sqlite3.c
npm ERR! make: Saindo do diretório '/home/duende/Downloads/my-new-app(1)/my-new-app/node_modules/sqlite3/build'
npm ERR! Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/duende/Downloads/my-new-app(1)/my-new-app/node_modules/sqlite3/lib/binding/napi-v6-linux-glibc-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/home/duende/Downloads/my-new-app(1)/my-new-app/node_modules/sqlite3/lib/binding/napi-v6-linux-glibc-x64 --napi_version=8 --node_abi_napi=napi --napi_build_version=6 --node_napi_label=napi-v6' (1)
npm ERR! node-pre-gyp info it worked if it ends with ok
npm ERR! node-pre-gyp info using node-pre-gyp@1.0.10
npm ERR! node-pre-gyp info using node@16.17.0 | linux | x64
npm ERR! node-pre-gyp info build requesting source compile
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.0.0
npm ERR! gyp info using node@16.17.0 | linux | x64
npm ERR! gyp info ok 
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.0.0
npm ERR! gyp info using node@16.17.0 | linux | x64
npm ERR! gyp info find Python using Python version 3.10.4 found at "/usr/bin/python3"
npm ERR! gyp info spawn /usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/duende/Downloads/my-new-app(1)/my-new-app/node_modules/sqlite3/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/duende/.cache/node-gyp/16.17.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/home/duende/.cache/node-gyp/16.17.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/home/duende/.cache/node-gyp/16.17.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/home/duende/Downloads/my-new-app(1)/my-new-app/node_modules/sqlite3',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info ok 
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.0.0
npm ERR! gyp info using node@16.17.0 | linux | x64
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! /bin/sh: 1: Syntax error: "(" unexpected
npm ERR! make: *** [deps/action_before_build.target.mk:13: Release/obj/gen/sqlite-autoconf-3390200/sqlite3.c] Erro 2
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
npm ERR! gyp ERR! System Linux 5.15.0-47-generic
npm ERR! gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/duende/Downloads/my-new-app(1)/my-new-app/node_modules/sqlite3/lib/binding/napi-v6-linux-glibc-x64/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/home/duende/Downloads/my-new-app(1)/my-new-app/node_modules/sqlite3/lib/binding/napi-v6-linux-glibc-x64" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=6" "--node_napi_label=napi-v6"
npm ERR! gyp ERR! cwd /home/duende/Downloads/my-new-app(1)/my-new-app/node_modules/sqlite3
npm ERR! gyp ERR! node -v v16.17.0
npm ERR! gyp ERR! node-gyp -v v9.0.0
npm ERR! gyp ERR! not ok 
npm ERR! node-pre-gyp ERR! build error 
npm ERR! node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/duende/Downloads/my-new-app(1)/my-new-app/node_modules/sqlite3/lib/binding/napi-v6-linux-glibc-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/home/duende/Downloads/my-new-app(1)/my-new-app/node_modules/sqlite3/lib/binding/napi-v6-linux-glibc-x64 --napi_version=8 --node_abi_napi=napi --napi_build_version=6 --node_napi_label=napi-v6' (1)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/duende/Downloads/my-new-app(1)/my-new-app/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1093:16)
npm ERR! node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
npm ERR! node-pre-gyp ERR! System Linux 5.15.0-47-generic
npm ERR! node-pre-gyp ERR! command "/usr/local/bin/node" "/home/duende/Downloads/my-new-app(1)/my-new-app/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
npm ERR! node-pre-gyp ERR! cwd /home/duende/Downloads/my-new-app(1)/my-new-app/node_modules/sqlite3
npm ERR! node-pre-gyp ERR! node -v v16.17.0
npm ERR! node-pre-gyp ERR! node-pre-gyp -v v1.0.10
npm ERR! node-pre-gyp ERR! not ok

### Version

"sqlite3": "^5.0.11",

### Node.js Version

v16.17.0

### How did you install the library?

npm install sqlite3 --save
** i using typeorm and reflect-metadata

**Comment by daniellockyer** [comment]
I think this is an issue with node-gyp and a folder in your path name: `my-new-app(1)`

Would you be able to try without the brackets?

**Comment by duendeee** [comment]
> I think this is an issue with node-gyp and a folder in your path name: `my-new-app(1)`
> 
> Would you be able to try without the brackets?

the problem really was the path name with ( )
thanks @daniellockyer
