### ISSUE TITLE
Version with promisses

### ISSUE THREAD

**Issue by SrStick** [TryGhost/node-sqlite3#1636]
### Summary

I think it would be interesting if there was a version of the database.run(), get() and all() methods that uses Promise instead of callback.
I can send a pull request with these changes, what do you think?

### Proposed implementation

the database.run(), get(), and all() methods should be implemented using Promisses

**Comment by daniellockyer** [comment]
Hey @SrStick 👋🏻 I would love to see a PR for this 🙂

**Comment by RinkAttendant6** [comment]
This appears to be a duplicate of https://github.com/TryGhost/node-sqlite3/issues/834

**Comment by daniellockyer** [comment]
Good point - closing as a duplicate of https://github.com/TryGhost/node-sqlite3/issues/834
