### ISSUE TITLE
64 int narrowing and other compile time type conversion issues

### ISSUE THREAD

**Issue by springmeyer** [TryGhost/node-sqlite3#164]
MSVS does a nice job of catching implicit conversions from int64 to int32 and double which we should either fix or make look intentional via `static_cast`:

![screen shot 2013-07-11 at 10 15 46 am](https://f.cloud.github.com/assets/20300/782070/a5078f2a-ea34-11e2-84c4-25c545d90bee.png)

**Comment by daniellockyer** [comment]
Closing as this is old and probably covered by https://github.com/TryGhost/node-sqlite3/pull/1689
