### ISSUE TITLE
switch to prebuild for better binary distribution and electron support

### ISSUE THREAD

**Issue by gpetrov** [TryGhost/node-sqlite3#1641]
### Summary

Currently node-sqlite3 uses node-pre-gyp for building and delivers only node compatible modules.

### Proposed implementation

To achieve wider binary distribution and to support electron prebuild binaries, a support for [prebuild ](https://github.com/prebuild/prebuild) is desired.

See https://nodejs.github.io/node-addon-examples/build-tools/prebuild/

**Comment by gpetrov** [comment]
Also node-pre-gyp is hitting a bit of a dead-end. See https://github.com/mapbox/node-pre-gyp/issues/657

**Comment by daniellockyer** [comment]
I'm also coming to the same conclusion 🙂 I'd like to serve `armv6` and `armv7` but I ran into a bug with node-pre-gyp: https://github.com/mapbox/node-pre-gyp/issues/348#issuecomment-1100938899

I'd welcome a PR to change over to prebuild. Else I can look at changing this but I have no ETA on that right now

**Comment by daniellockyer** [comment]
That being said, it doesn't look like it would solve my problem: https://github.com/prebuild/prebuild/issues/174

**Comment by nbransby** [comment]
> That being said, it doesn't look like it would solve my problem: [prebuild/prebuild#174](https://github.com/prebuild/prebuild/issues/174)

Time to switch to [prebuildify](https://github.com/prebuild/prebuildify)? https://github.com/prebuild/prebuild/issues/174#issuecomment-1019372077
