### ISSUE TITLE
"currently not implemented" warning mostly doesn't work under typescript

### ISSUE THREAD

**Issue by bkerin** [TryGhost/node-sqlite3#1660]
### Issue Summary

I'm looking back at my code after a time away from IIRC the gist is that the "currently not implemented" warning doesn't end up showing up under typescript.  I think it would show under plain JS because the arg would get ignored.  If his sort of hole is going to be reported at runtime it needs to work under TS.

Here's what I wrote to myself:

// FIXME: WORK POINT: uhhhh serialize is "currently not implemented"
// we learn when we call it with 0 args (rather than the callback
// it's suppsed to take, which typescript won't let us do)
// and we're supposed to use getDatabaseInstance().serialize()
// instead (as above).  The serialize interface is described here:
// https://github.com/tryghost/node-sqlite3/wiki/Control-Flow But maybe
// the fact that it isn't really implemented is why this doesn't work:
rawDb.serialize();
rawDb.run("CREATE TABLE other_lorem (other_info TEXT)")
rawDb.run("INSERT INTO  other_lorem (other_info) VALUES ('myOtherInfo')")
const other_result = rawDb.get("SELECT * FROM other_lorem")
console.log("WHY:")
console.log(other_result)

### Steps to Reproduce

import assert   from 'node:assert/strict';
import sqlite3  from 'sqlite3'
import { open } from 'sqlite'

const db = await open({ filename: ':memory:', driver: sqlite3.Database })
if (db === null) { throw "db still null" }
assert(db !== null)
console.log("db:")
console.log(db)
console.log()

await db.run("CREATE TABLE lorem (info TEXT)")

// This serializes correctly:
await db.run("INSERT INTO  lorem (info) VALUES ('myInfo')")
const result = await db.get("SELECT * FROM lorem")
console.log(result)
console.log()

const rawDb = db.getDatabaseInstance();

// FIXME: WORK POINT: uhhhh serialize is "currently not implemented"
// we learn when we call it with 0 args (rather than the callback
// it's suppsed to take, which typescript won't let us do)
// and we're supposed to use getDatabaseInstance().serialize()
// instead (as above).  The serialize interface is described here:
// https://github.com/tryghost/node-sqlite3/wiki/Control-Flow But maybe
// the fact that it isn't really implemented is why this doesn't work:
rawDb.serialize();
rawDb.run("CREATE TABLE other_lorem (other_info TEXT)")
rawDb.run("INSERT INTO  other_lorem (other_info) VALUES ('myOtherInfo')")
const other_result = rawDb.get("SELECT * FROM other_lorem")
console.log("WHY:")
console.log(other_result)

### Version

sqlite3@5.1.1   sqlite@4.1.2

### Node.js Version

v18.9.1

### How did you install the library?

npm -g

**Comment by daniellockyer** [comment]
@bkerin I'm not sure I understand the issue you've presented here. What error are you seeing? How is affecting your code?

Happy to re-open when I have more details 🙂
