### ISSUE TITLE
ERR! Completion callback never invoked 

### ISSUE THREAD

**Issue by luckdev01** [TryGhost/node-sqlite3#1662]
### Issue Summary

I encountered this issue when I install the sqlite3 package on mac.

![image](https://user-images.githubusercontent.com/40633197/206277470-d7e0c511-2940-4290-b30d-de11851687fb.png)

### Steps to Reproduce

```
mkdir TestSqlite3
cd TestSqlite3
npm init
yarn add sqlite3
```

### Version

5.1.2

### Node.js Version

16.17.0

### How did you install the library?

yarn add sqlite3

**Comment by daniellockyer** [comment]
It seems to be the same as https://github.com/mapbox/node-pre-gyp/issues/367, which is not a node-sqlite3 issue.

Have you tried https://github.com/mapbox/node-pre-gyp/issues/367#issuecomment-392770854?

**Comment by luckdev01** [comment]
@daniellockyer
[mapbox/node-pre-gyp#367](https://github.com/mapbox/node-pre-gyp/issues/367)
It is a node-sqlite3 issue.
![image](https://user-images.githubusercontent.com/40633197/207147943-d6a64441-ae52-4fed-8a96-252b16be427f.png)
And [mapbox/node-pre-gyp@367 (comment)](https://github.com/mapbox/node-pre-gyp/issues/367#issuecomment-392770854) is not working.

**Comment by daniellockyer** [comment]
@luckdev01 The majority of comments on that issue refer to the root cause being network or permissions issues
