### ISSUE TITLE
Remove `@mapbox/node-pre-gyp` runtime dependency

### ISSUE THREAD

**Issue by ncortines** [TryGhost/node-sqlite3#1668]
### Summary

Would be possible to remove the `@mapbox/node-pre-gyp` dependency from `lib/sqlite3-binding.js`?

It pulls a bunch of not needed dependencies into the final application build.

```
└─┬ sqlite3@5.0.10
  ├─┬ @mapbox/node-pre-gyp@1.0.10
  │ ├── detect-libc@2.0.1
  │ ├─┬ https-proxy-agent@5.0.1
  │ │ ├─┬ agent-base@6.0.2
  │ │ │ └── debug@4.3.4 deduped
  │ │ └─┬ debug@4.3.4
  │ │   └── ms@2.1.2
  │ ├─┬ make-dir@3.1.0
  │ │ └── semver@6.3.0
  │ ├─┬ node-fetch@2.6.7
  │ │ ├─┬ encoding@0.1.13
  │ │ │ └─┬ iconv-lite@0.6.3
  │ │ │   └── safer-buffer@2.1.2
  │ │ └─┬ whatwg-url@5.0.0
  │ │   ├── tr46@0.0.3
  │ │   └── webidl-conversions@3.0.1
  │ ├─┬ nopt@5.0.0
  │ │ └── abbrev@1.1.1
  │ ├─┬ npmlog@5.0.1
  │ │ ├─┬ are-we-there-yet@2.0.0
  │ │ │ ├── delegates@1.0.0
  │ │ │ └─┬ readable-stream@3.6.0
  │ │ │   ├── inherits@2.0.4 deduped
  │ │ │   ├─┬ string_decoder@1.1.1
  │ │ │   │ └── safe-buffer@5.1.2
  │ │ │   └── util-deprecate@1.0.2
  │ │ ├── console-control-strings@1.1.0
  │ │ ├─┬ gauge@3.0.2
  │ │ │ ├── aproba@2.0.0
  │ │ │ ├── color-support@1.1.3
  │ │ │ ├── console-control-strings@1.1.0 deduped
  │ │ │ ├── has-unicode@2.0.1
  │ │ │ ├── object-assign@4.1.1
  │ │ │ ├── signal-exit@3.0.7
  │ │ │ ├─┬ string-width@4.2.3
  │ │ │ │ ├── emoji-regex@8.0.0
  │ │ │ │ ├── is-fullwidth-code-point@3.0.0
  │ │ │ │ └── strip-ansi@6.0.1 deduped
  │ │ │ ├─┬ strip-ansi@6.0.1
  │ │ │ │ └── ansi-regex@5.0.1
  │ │ │ └─┬ wide-align@1.1.5
  │ │ │   └── string-width@4.2.3 deduped
  │ │ └── set-blocking@2.0.0
  │ ├─┬ rimraf@3.0.2
  │ │ └── glob@7.2.3 deduped
  │ ├─┬ semver@7.3.6
  │ │ └── lru-cache@7.7.3
  │ └── tar@6.1.11 deduped
```
### Proposed implementation

Something similar to this?

https://github.com/microsoft/vscode-node-sqlite3/blob/vscode/lib/sqlite3-binding.js

**Comment by ncortines** [comment]
Ok, I see that some of those dependencies are still needed to resolve the path. Bundling and tree-shaking should help with the rest of not needed dependencies.

**Comment by Vector-Green** [comment]
Seems it's still important probably in some cases
For example, I'm making embedded project and all script should be bundled into a single file + some .node files (including node_modules bundling)
currently errors are in @mapbox+node-pre-gyp@1.0.10 for example

ERROR in ./node_modules/.pnpm/node-gyp@8.4.1/node_modules/node-gyp/lib/Find-VisualStudio.cs 9:6       
Module parse failed: Unexpected token (9:6)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| // This script needs to be compatible with PowerShell v2 to run on Windows 2008R2 and 
> using System;

Can't resolve 'nock'
Can't resolve 'aws-sdk'
Can't resolve 'mock-aws-s3'
Can't resolve 'bluebird'
Can't resolve 'npm'

ERROR in ./node_modules/.pnpm/@mapbox+node-pre-gyp@1.0.10/node_modules/@mapbox/node-pre-gyp/lib/util/nw-pre-gyp/index.html 1:0
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> <!doctype html>

after installing pnpm i npm bluebird mock-aws-s3 aws-sdk nock --save-optional
permanent error occures like
./node_modules/.pnpm/npm@9.6.6/node_modules/npm/node_modules/qrcode-terminal/lib/main.js  
  1 | var QRCode = require('./../vendor/QRCode'),
  2 |     QRErrorCorrectLevel = require('./../vendor/QRCode/QRErrorCorrectLevel'),
> 3 |     black = "\033[40m  \033[0m",
and many others...
In general I cannot bundle sqlite properly including node_modules
is there any ways?
repo https://github.com/Vector-Green/sqlite-node_modules_bundling
