### ISSUE TITLE
Build failed due to s3 dependency

### ISSUE THREAD

**Issue by ayroblu** [TryGhost/node-sqlite3#1669]
### Issue Summary

When I install the latest version of sqlite3 (5.1.4), I get the following error message when I try to run my code: 

```
build failed (node_modules/@mapbox/node-pre-gyp/lib/util/s3_setup.js:43:28     const AWSMock = require('mock-aws-s3');): Could not resolve "mock-aws-s3"
```

It appears to pass this stage at 5.0.2, fails on 5.0.3

### Steps to Reproduce

1. Start a raycast project
2. Install sqlite3 with npm i sqlite3
3. Use sqlite3 somewhere in your imports
4. `npm run dev`

### Version

5.1.4

### Node.js Version

v19.2.0

### How did you install the library?

macOS Ventura, m1 (arm)

**Comment by daniellockyer** [comment]
Do you have anything else odd going on with your setup? That bit of code should only be run of `process.env.node_pre_gyp_mock_s3` is truthy

**Comment by Erchoc** [comment]
same to you.

**Comment by daniellockyer** [comment]
Closing as there was no response.

It might be the case you need to ignore the dependency, but it's a devDependency only used for developing this package.

**Comment by ayroblu** [comment]
Sorry I took so long to get back to you, I'm guessing raycast does a webpack thing, will debug and reopen if there's something to do here

**Comment by abury** [comment]
I'm seeing this as well. Installed in a standard cdk project and getting two errors:

```
✘ [ERROR] Could not resolve "mock-aws-s3"

    node_modules/@mapbox/node-pre-gyp/lib/util/s3_setup.js:43:28:
      43 │     const AWSMock = require('mock-aws-s3');
         ╵                             ~~~~~~~~~~~~~

  You can mark the path "mock-aws-s3" as external to exclude it from the bundle,
  which will remove this error. You can also surround this "require" call with a
  try/catch block to handle this failure at run-time instead of bundle-time.

✘ [ERROR] Could not resolve "nock"

    node_modules/@mapbox/node-pre-gyp/lib/util/s3_setup.js:112:23:
      112 │   const nock = require('nock');
          ╵                        ~~~~~~

  You can mark the path "nock" as external to exclude it from the bundle, which
  will remove this error. You can also surround this "require" call with a
  try/catch block to handle this failure at run-time instead of bundle-time.
```
