### ISSUE TITLE
can't install sqlite3 on windows with npm. 

### ISSUE THREAD

**Issue by octocat512** [TryGhost/node-sqlite3#1683]
### Issue Summary

npm: v9.5.0
python: v2.7.15
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.19044 N/A Build 19044
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 151 Stepping 2 GenuineIntel ~2100 Mhz
BIOS Version:              American Megatrends International, LLC. 5.24, 2/24/2022

can't install sqlite3 on my project. 

### Relevant logs or output

npm WARN deprecated @npmcli/move-file@1.1.2: This functionality has been moved to @npmcli/fs
npm ERR! code 6
npm ERR! path C:\Users\daniel li\AppData\Roaming\nvm\v18.14.1\node_modules\sqlite3
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node-pre-gyp install --fallback-to-build
npm ERR! node-pre-gyp info it worked if it ends with ok
npm ERR! node-pre-gyp info using node-pre-gyp@1.0.10
npm ERR! node-pre-gyp info using node@18.14.1 | win32 | x64
npm ERR! node-pre-gyp info check checked for "C:\Users\daniel li\AppData\Roaming\nvm\v18.14.1\node_modules\sqlite3\lib\binding\napi-v6-win32-unknown-x64\node_sqlite3.node" (not found)
npm ERR! node-pre-gyp http GET https://github.com/TryGhost/node-sqlite3/releases/download/v5.1.4/napi-v6-win32-unknown-x64.tar.gz
npm ERR! node-pre-gyp info install unpacking napi-v6-win32-unknown-x64/node_sqlite3.node
npm ERR! node-pre-gyp ERR! Completion callback never invoked!
npm ERR! node-pre-gyp ERR! System Windows_NT 10.0.19044
npm ERR! node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\daniel li\\AppData\\Roaming\\nvm\\v18.14.1\\node_modules\\sqlite3\\node_modules\\@mapbox\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
npm ERR! node-pre-gyp ERR! cwd C:\Users\daniel li\AppData\Roaming\nvm\v18.14.1\node_modules\sqlite3
npm ERR! node-pre-gyp ERR! node -v v18.14.1
npm ERR! node-pre-gyp ERR! node-pre-gyp -v v1.0.10

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\daniel li\AppData\Local\npm-cache\_logs\2023-02-18T14_47_52_425Z-debug-0.log

### Version

5.1.4

### Node.js Version

18.14.1

### How did you install the library?

I provide the details in the issue summary section.

**Comment by kewde** [comment]
Seems like you're failing to get https://github.com/TryGhost/node-sqlite3/releases/download/v5.1.4/napi-v6-win32-unknown-x64.tar.gz , I am able to download the file just fine here.

**Comment by daniellockyer** [comment]
Can you please try with the latest version? We removed node-pre-gyp so things should be a little smoother. Alternatively check your internet connection
