### ISSUE TITLE
no such column error

### ISSUE THREAD

**Issue by wangshixiang1984** [TryGhost/node-sqlite3#1688]
### Issue Summary

Error: SQLITE_ERROR: no such column: nameCount  

### Steps to Reproduce

1、SQL AS FOLLOW:
select  (length(A.name)-length(replace(A.name, ',', '')) + 1) as nameCount  ,id from tale_name as A left join tale_part as B on A.tale_part_id=B.id where nameCount  > ?

2、When run this sql, will throw error : 
```sqlite3.all(`select  (length(A.name)-length(replace(A.name, ',', '')) + 1) as nameCount  ,A.id from tale_name as A left join tale_part as B on A.tale_part_id=B.id where nameCount > ?`, [1])```

Error: SQLITE_ERROR: no such column: nameCount 

### Version

5.1.4

### Node.js Version

v14.20.1

### How did you install the library?

yarn add sqlite3, operating system: windows 10

**Comment by daniellockyer** [comment]
Can you provide a more detailed reproduction? I can't reproduce from this 🙂
