### ISSUE TITLE
Version 5.1.5 requires GLIBC 2.29 ?

### ISSUE THREAD

**Issue by chgeo** [TryGhost/node-sqlite3#1690]
### Issue Summary

With the new sqlite3 release v5.1.5, we get SQLite 3.41.1.  During installation a SLES12 SP5 CI machine, we get an error though, saying that GLIBC 2.29 is not found.

Can you confirm this is intended, i.e. that GLIBC 2.29 is now required?
- If yes, would be worth mentioning in the release notes
- If no, can you fix by lowering the GLIBC requirements?

### Relevant logs or output

`/lib64/libm.so.6: version 'GLIBC_2.29' not found (required by .../node_modules/sqlite3/lib/binding/napi-v6-linux-glibc-x64/node_sqlite3.node)`

### Version

5.1.5

### Node.js Version

16.13

### How did you install the library?

npm install on Linux SLES12 SP5

**Comment by ashfaqhaq** [comment]
facing the same issue on builds on AWS. My current node version is 14.

**Comment by daniellockyer** [comment]
@chgeo Apologies - it seems the latest build included a link to a newer version of `log2`. I'm working on releasing a fix now (and will come up with a test to prevent this in the future)

**Comment by chgeo** [comment]
@daniellockyer Appreciated, thanks

**Comment by daniellockyer** [comment]
Hey @chgeo + all, this should now be resolved in https://github.com/TryGhost/node-sqlite3/releases/tag/v5.1.6 🙂

**Comment by chgeo** [comment]
Can confirm the new version works.  Thanks!
