### ISSUE TITLE
@npmcli/move-file is deplicated

### ISSUE THREAD

**Issue by Harryk13** [TryGhost/node-sqlite3#1702]
### Issue Summary

 @npmcli/move-file@1.1.2: This functionality has been moved to @npmcli/fs

### Relevant logs or output

npm WARN deprecated @npmcli/move-file@1.1.2: This functionality has been moved to @npmcli/fs

### Version

5.1.6

### Node.js Version

18.16.0

### How did you install the library?

npm i

**Comment by GaneshKaparapu** [comment]
I too have the same issue, please let me know if we have any other solutions that we can try.

**Comment by daniellockyer** [comment]
This is only a warning, so it doesn't affect the functionality of the library 🙂
