### ISSUE TITLE
Segmentation fault due to syntax error

### ISSUE THREAD

**Issue by ioanclarke** [TryGhost/node-sqlite3#1708]
### Issue Summary

Running the following code while inside an Express server produces a segmentation fault on my system:
```typescript
 db.run(`
        INSERT INTO quiz ($id, $name, $author, $dateutc) 
        VALUES ($id, $name, $author, $dateutc)`,
        params
    )
```
I was attempting to use Postgres syntax, which I now realise is incorrect of course.

When the above code runs, my Express server exits, and the following message is displayed in my terminal:
 `zsh: segmentation fault  npm start`

### Steps to Reproduce

1. Run the above code while inside an Express server
2. The process exits with the message: `zsh: segmentation fault  npm start`

### Version

5.1.6

### Node.js Version

16.8.1

### How did you install the library?

`npm install sqlite3`

**Comment by daniellockyer** [comment]
I can't seem to reproduce this. Can you give a more concrete example and then I'd be happy to fix it 🙂
