### ISSUE TITLE
Raspberry Pi Zero - install

### ISSUE THREAD

**Issue by pawel54321** [TryGhost/node-sqlite3#1712]
### Issue Summary

Hello,

I development my application in node.js and working in my windows, but I have problem install to module sqlite3 in Raspberry Pi Zero. I try install a lot of time of spend :(. I always stop my install in 
"reify:node-gyp: timing reifyNode: node modules\sqlite3 Completed in "...ms""

Please help me with this problem. I readed and used: example: Source install method, command to install: apt get node-sqlite3, sqlite3. npm install and more:

export LDFLAGS="-L/usr/local/lib"
export CPPFLAGS="-I/usr/local/include -I/usr/local/include/sqlcipher"
export CXXFLAGS="$CPPFLAGS"
npm install sqlite3 --build-from-source --sqlite_libname=sqlcipher --sqlite=/usr/local --verbose

node -e 'require("sqlite3")'

npm test

sudo apt install node-sqlite3

https://github.com/TryGhost/node-sqlite3#source-install

sudo apt-get install libsqlite3-dev
npm install sqlite3 --build-from-source --sqlite=/usr

### Steps to Reproduce

install sqlite3 in cleary project (deleted node_modules)

### Version

newest (now I tried previous too bugs)

### Node.js Version

newest (now I tried previous too bugs)

### How did you install the library?

Raspberry Pi Zero

**Comment by daniellockyer** [comment]
Please reopen the issue with details on the actual error you see 🙂
