### ISSUE TITLE
Why use `node-pre-gyp` instead of `node-gyp`?

### ISSUE THREAD

**Issue by AsteriskZuo** [TryGhost/node-sqlite3#1714]
### Summary

Why use `node-pre-gyp` instead of `node-gyp`? The `node-pre-gyp` uses the BSD license.

### Proposed implementation

We need to carefully consider products under the BSD license.

**Comment by NoahAndrews** [comment]
What's wrong with the BSD license? This repository uses the BSD license as well.

**Comment by fcanela** [comment]
The problem shouldn't be the license, but that `node-pre-gyp` has no maintainer [1] and it is causing install problems to electron users that want to install this library [2]

[1] https://github.com/mapbox/node-pre-gyp/issues/657
[2] https://github.com/mapbox/node-pre-gyp/issues/661

**Comment by mdjaman** [comment]
@fcanela Totally agree. 3 days still looking for a workaround
