### ISSUE TITLE
node-pre-gyp is no longer maintained and is bugged for electron users

### ISSUE THREAD

**Issue by fcanela** [TryGhost/node-sqlite3#1721]
### Issue Summary

`node-sqlite3` depends on `node-pre-gyp` (an unmaintained library [1]).  That library does some conditional requiring of dependencies (`aws-sdk` and `mock-aws-s2`) that are places in "devDependencies", not "dependencies" ([2]) and this is causing troubles with `electron`+`sqlite3` (among other users).

This is related with the issues #1704, #1700 and #1691

[1] https://github.com/mapbox/node-pre-gyp/issues/657
[2] https://github.com/mapbox/node-pre-gyp/issues/661

### Steps to Reproduce

1. Install electron, vite and sqlite3
2. Require/import sqlite3

### Version

5.1.6

### Node.js Version

20

### How did you install the library?

Kubuntu 22.04, amd64

**Comment by daniellockyer** [comment]
I'm looking into this :)

**Comment by fcanela** [comment]
@daniellockyer thank you very much for the resolution!
