### ISSUE TITLE
Troubleshooting Module Loading Issues in Latest Electron Versions with node-sqlite3 Compilation Success

### ISSUE THREAD

**Issue by pmanup** [TryGhost/node-sqlite3#1729]
### Issue Summary

It works well in Electron version 15, but in the latest versions, the module does not load. node-sqlite3 compiles correctly.

### Steps to Reproduce

npm install sqlite3
electron .
error: sqlite3 module not foun

### Version

last

### Node.js Version

18.15.0

### How did you install the library?

npm

**Comment by daniellockyer** [comment]
Please file a more detailed feature with reproduction steps 🙂
