### ISSUE TITLE
Error: /lib64/libm.so.6: version `GLIBC_2.29' not found 

### ISSUE THREAD

**Issue by huashaoxu** [TryGhost/node-sqlite3#1730]
### Issue Summary

Run the program in the Kylin v10 sp2 system and report an error at startup. Error message:
Error: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by /data/soft/geoops-sever/node_modules/sqlite3/lib/binding/napi-v6-linux-glibc-arm64/node_sqlite3.node)

glibc version: 
ldd (GNU libc) 2.28
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.

### Steps to Reproduce

yarn add sqlite , import it , new sqlite() , running program 

### Version

5.1.6

### Node.js Version

16.20.1

### How did you install the library?

kylin v10 sp2 , arm

**Comment by alex-inflexible** [comment]
```
node:internal/modules/cjs/loader:1210
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^
Error: /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /var/www/.../node_modules/sqlite3/lib/binding/napi-v6-linux-glibc-x64/node_sqlite3.node)
```

Any solutions?
