### ISSUE TITLE
API for inserting multiple rows fast

### ISSUE THREAD

**Issue by kkaefer** [TryGhost/node-sqlite3#2]

**Comment by RobertSasak** [comment]
I recommend adding following. It has speed up inserting in order of magnitude. Source: http://blog.quibb.org/2010/08/fast-bulk-inserts-into-sqlite/
```js
db.run('PRAGMA synchronous=OFF')
db.run('PRAGMA count_changes=OFF')
db.run('PRAGMA journal_mode=MEMORY')
db.run('PRAGMA temp_store=MEMORY')
```

**Comment by cekvenich** [comment]
What RobertSasak said plus begin/commit. I get ~ 30K rows/sec.

**Comment by daniellockyer** [comment]
I like the PRAGMA suggestions in this thread, so I don't think we explicitly need a specific API right now 🙂
