### ISSUE TITLE
Bindings for the SQLite backup API

### ISSUE THREAD

**Issue by AlexAtNet** [TryGhost/node-sqlite3#266]
Does the node-sqlite3 contain bindings for the SQLite Backup API - http://www.sqlite.org/backup.html ?

If not, do you have any idea on how complex it will be to add bindings for these methods: `sqlite3_backup_init`, `sqlite3_backup_step`, `sqlite3_backup_finish` ?

Thanks.

**Comment by l0calh05t** [comment]
+1 on this feature request.

**Comment by spanitz** [comment]
+1

**Comment by kelleydv** [comment]
+1

**Comment by shovemedia** [comment]
+1 and a $200 bounty

**Comment by rswamy** [comment]
+1

**Comment by frankMazzarella** [comment]
+1

**Comment by coleGillespie** [comment]
+1 also lol @shovemedia

**Comment by nornagon** [comment]
looks like #883 adds the functionality

**Comment by daniellockyer** [comment]
I believe this has been implemented 🙂
