### ISSUE TITLE
Migrate binaries from "node-sqlite3" bucket to "mapbox-node-binary" bucket

### ISSUE THREAD

**Issue by springmeyer** [TryGhost/node-sqlite3#268]
The current batch of binaries are hosted under my personal aws account, but these should be migrated to a Mapbox account so other committers on this project can have admin access to the bucket.

To do this I will:
- [x] - Point `package.json` `binary/host` value at `mapbox-node-binary`
- [x] - Re-encode the node-pre-gyp publishing keys in .travis.yml with new keys that work to publish to this new location
- [ ] - In a few months (after the v2.2.5 release is well established) I'll delete the `node-sqlite3` bucket.

**Comment by ErisDS** [comment]
It would be good to update the wiki page here: https://github.com/mapbox/node-sqlite3/wiki/Binaries#available-binaries with the new URL and then I believe the old bucket can now be deleted?

**Comment by daniellockyer** [comment]
We've since switched to GitHub Releases so this can be closed 🙂
