### ISSUE TITLE
Inserting in parallel is very slow on freebsd 64

### ISSUE THREAD

**Issue by springmeyer** [TryGhost/node-sqlite3#270]
My setup was: https://gist.github.com/springmeyer/fabd05d5535e086d5d51

Notably:

```
✓ should insert in parallel (22301ms)
```

Is very slow for reasons unknown, compared to OS X which is:

```
✓ should insert in parallel (488ms)
```

This ticket is not actionable, but stands to document this issue and hopefully someone out there might be interested in debugging further.

**Comment by daniellockyer** [comment]
I'm going to close this as the issue has gone stale but happy to re-open if it's still an issue 🙂
