### ISSUE TITLE
db.run - either api documentation is wrong, or the implementation is

### ISSUE THREAD

**Issue by dangibson** [TryGhost/node-sqlite3#275]
The api documentation for db.run says:
callback (optional): If given, it will be called when an error occurs during any step of the statement preparation or execution, _and_ after the query was run.

This doesn't seem to be the case. I'm executing a UPDATE... that fails. I get the call with error non-null, but I don't receive the call after the query is run with error null.

I suspect it is because of this code:

```
void Statement::Work_AfterRun(uv_work_t* req) {
HandleScope scope;
STATEMENT_INIT(RunBaton);

if (stmt->status != SQLITE_ROW && stmt->status != SQLITE_DONE) {
    Error(baton);
}
else {
    // Fire callbacks.
```

I'm guessing that Error(baton) is the call I'm getting, but the else clause prevents it from firing the second call.

I'm not sure what is wrong - should it call the callback twice (once with error non-null then again with it null) or is the api documentation wrong?

**Comment by daniellockyer** [comment]
Fixed 🙂
