### ISSUE TITLE
ARM binary for v2.2.3: node_sqlite3-v2.2.3-node-v11-linux-arm

### ISSUE THREAD

**Issue by sweetpi** [TryGhost/node-sqlite3#298]
Could you include [this binary](https://github.com/sweetpi/node-sqlite3-arm/releases/tag/node_sqlite3-v2.2.3-node-v11-linux-arm) for the arm?

It was built and tested on the Raspberry. It would be nice if you could include it, so I can use it in my next release of [pimatic](https://github.com/pimatic/pimatic/issues/161).

**Comment by daniellockyer** [comment]
Closing as this is related to a very old version. Prebuilt ARM binaries should be coming in coming releases 🙂
