### ISSUE TITLE
Is It Possible to Retrieve the Database Name from a Statment Object

### ISSUE THREAD

**Issue by BenLin1** [TryGhost/node-sqlite3#303]
According to the code, I can retrieve the database name ( or filename ) from a Database object by Database.filename. So I'm wondering, is there a similar way for us to retrieve the database name ( or filename ) from a Statment object? If not, how about retrieving the database object from the statment object?

Thanks a lot!
BR//Ben

**Comment by daniellockyer** [comment]
Hey @BenLin1 👋🏻 It's not currently possible and it's unlikely we'll add support for this right now. If there's further demand on this issue, maybe it's something to re-assess in the future 🙂
