### ISSUE TITLE
Feature request: Serialize / Deserialize from disk to memory & vice versa

### ISSUE THREAD

**Issue by jasonbrice** [TryGhost/node-sqlite3#305]
A nice feature would be to load an entire database from disk into memory, perform operations on it in memory without the overhead of disk reads/writes, then at some point save the in-memory database back to disk.

This is possible now as a manual process, but it risks the code and the database getting out of sync, other types of programmer error, etc.

**Comment by daniellockyer** [comment]
Closing as this issue is old and there isn't demand for it. We can reopen if it's still desired
