### ISSUE TITLE
Parameters Not Binding

### ISSUE THREAD

**Issue by JarrettB42** [TryGhost/node-sqlite3#330]
Just trying to bind some parameters.

var gameName = "Example Game Name";
db.run("INSERT INTO GameList VALUES (?)", gameName, onEnd);
// works
db.run("CREATE TABLE ? (Channel TEXT)", gameName, onEnd);
//{ [Error: SQLITE_ERROR: near "?": syntax error] errno: 1, code: 'SQLITE_ERROR' }
db.run("CREATE TABLE '" + gameName + "' (Channel TEXT)", onEnd);
// works

Reading through the API, I saw no stated limitations of what could be bound or where. I see they don't work for PRAGMA statements, but this is just a simple CREATE. Am I missing something here?

Using Node v0.10.26 and the latest node-sqlite3

**Comment by daniellockyer** [comment]
Thanks for the note - added to the docs

> Parameters may not be used for column or table names.
