### ISSUE TITLE
Coredump when using prepared statements

### ISSUE THREAD

**Issue by Kasalehlia** [TryGhost/node-sqlite3#353]
When using the Function.prototype.call or Function.prototype.apply functions on the run/get/all/each function of a preapred statement, not submitting the statement as `this` argument results in the message shown below:

```
node: /home/travis/.node-gyp/0.10.29/src/node_object_wrap.h:61: static T* node::ObjectWrap::Unwrap(v8::Handle<v8::Object>) [with T = node_sqlite3::Statement]: Assertion `handle->InternalFieldCount() > 0' failed.
```

I am using sqlite3@3.0.2 and node v0.10.32.
Example code to trigger this issue:

```
var sqlite3 = require('sqlite3');
db = new sqlite3.Database(':memory:', function () {
    statement = db.prepare('CREATE TABLE a (id TEXT);');
    statement.run.call(null);
});
```

Using the same code on the run function of the database itself triggers an exception: `TypeError: Database object expected` which I suppose is the correct behaviour in that case.

**Comment by daniellockyer** [comment]
This no longer crashes and instead throws an `Illegal invocation error`
