### ISSUE TITLE
Failed to build on XP

### ISSUE THREAD

**Issue by rss181919** [TryGhost/node-sqlite3#382]
C:\NETSHARE\data\devprojects\nw\DBUtil>npm install sqlite3 --build-from-source --runtime="node-webki
t" --target_arch="ia32" --target="0.11.5"
npm WARN package.json DBUtil@ No description
npm WARN package.json DBUtil@ No repository field.
npm WARN package.json DBUtil@ No README data
\

> sqlite3@3.0.4 install C:\NETSHARE\data\devprojects\nw\DBUtil\node_modules\sqlite3
> node-pre-gyp install --fallback-to-build

  unpack_sqlite_dep
  sqlite3.c
  sqlite3.vcxproj -> C:\NETSHARE\data\devprojects\nw\DBUtil\node_modules\sqlite3\build\Release\sql
  ite3.lib
  database.cc
..\src\database.cc(134): error C2661: 'v8::Object::Set' : no overloaded function takes 3 arguments
[C:\NETSHARE\data\devprojects\nw\DBUtil\node_modules\sqlite3\build\node_sqlite3.vcxproj]
..\src\database.cc(135): error C2661: 'v8::Object::Set' : no overloaded function takes 3 arguments
[C:\NETSHARE\data\devprojects\nw\DBUtil\node_modules\sqlite3\build\node_sqlite3.vcxproj]
  node_sqlite3.cc
..\src\node_sqlite3.cc(23): error C2661: 'v8::Object::Set' : no overloaded function takes 3 argumen
ts [C:\NETSHARE\data\devprojects\nw\DBUtil\node_modules\sqlite3\build\node_sqlite3.vcxproj]
..\src\node_sqlite3.cc(24): error C2661: 'v8::Object::Set' : no overloaded function takes 3 argumen
ts [C:\NETSHARE\data\devprojects\nw\DBUtil\node_modules\sqlite3\build\node_sqlite3.vcxproj]
..\src\node_sqlite3.cc(25): error C2661: 'v8::Object::Set' : no overloaded function takes 3 argumen
ts [C:\NETSHARE\data\devprojects\nw\DBUtil\node_modules\sqlite3\build\node_sqlite3.vcxproj]
..\src\node_sqlite3.cc(26): error C2661: 'v8::Object::Set' : no overloaded function takes 3 argumen
ts [C:\NETSHARE\data\devprojects\nw\DBUtil\node_modules\sqlite3\build\node_sqlite3.vcxproj]
..\src\node_sqlite3.cc(28): error C2661: 'v8::Object::Set' : no overloaded function takes 3 argumen
ts [C:\NETSHARE\data\devprojects\nw\DBUtil\node_modules\sqlite3\build\node_sqlite3.vcxproj]
..\src\node_sqlite3.cc(30): error C2661: 'v8::Object::Set' : no overloaded function takes 3 argumen
ts [C:\NETSHARE\data\devprojects\nw\DBUtil\node_modules\sqlite3\build\node_sqlite3.vcxproj]
..\src\node_sqlite3.cc(32): error C2661: 'v8::Object::Set' : no overloaded function takes 3 argumen
ts [C:\NETSHARE\data\devprojects\nw\DBUtil\node_modules\sqlite3\build\node_sqlite3.vcxproj]
..\src\node_sqlite3.cc(33): error C2661: 'v8::Object::Set' : no overloaded function takes 3 argumen
ts [C:\NETSHARE\data\devprojects\nw\DBUtil\node_modules\sqlite3\build\node_sqlite3.vcxproj]
..\src\node_sqlite3.cc(34): error C2661: 'v8::Object::Set' : no overloaded function takes 3 argumen
ts [C:\NETSHARE\data\devprojects\nw\DBUtil\node_modules\sqlite3\build\node_sqlite3.vcxproj]
..\src\node_sqlite3.cc(35): error C2661: 'v8::Object::Set' : no overloaded function takes 3 argumen
ts [C:\NETSHARE\data\devprojects\nw\DBUtil\node_modules\sqlite3\build\node_sqlite3.vcxproj]
..\src\node_sqlite3.cc(36): error C2661: 'v8::Object::Set' : no overloaded function takes 3 argumen
ts [C:\NETSHARE\data\devprojects\nw\DBUtil\node_modules\sqlite3\build\node_sqlite3.vcxproj]
..\src\node_sqlite3.cc(37): error C2661: 'v8::Object::Set' : no overloaded function takes 3 argumen
ts [C:\NETSHARE\data\devprojects\nw\DBUtil\node_modules\sqlite3\build\node_sqlite3.vcxproj]
..\src\node_sqlite3.cc(38): error C2661: 'v8::Object::Set' : no overloaded function takes 3 argumen
ts [C:\NETSHARE\data\devprojects\nw\DBUtil\node_modules\sqlite3\build\node_sqlite3.vcxproj]
..\src\node_sqlite3.cc(39): error C2661: 'v8::Object::Set' : no overloaded function takes 3 argumen
ts [C:\NETSHARE\data\devprojects\nw\DBUtil\node_modules\sqlite3\build\node_sqlite3.vcxproj]
..\src\node_sqlite3.cc(40): error C2661: 'v8::Object::Set' : no overloaded function takes 3 argumen
ts [C:\NETSHARE\data\devprojects\nw\DBUtil\node_modules\sqlite3\build\node_sqlite3.vcxproj]
..\src\node_sqlite3.cc(41): error C2661: 'v8::Object::Set' : no overloaded function takes 3 argumen
ts [C:\NETSHARE\data\devprojects\nw\DBUtil\node_modules\sqlite3\build\node_sqlite3.vcxproj]
..\src\node_sqlite3.cc(42): error C2661: 'v8::Object::Set' : no overloaded function takes 3 argumen
ts [C:\NETSHARE\data\devprojects\nw\DBUtil\node_modules\sqlite3\build\node_sqlite3.vcxproj]
..\src\node_sqlite3.cc(43): error C2661: 'v8::Object::Set' : no overloaded function takes 3 argumen
ts [C:\NETSHARE\data\devprojects\nw\DBUtil\node_modules\sqlite3\build\node_sqlite3.vcxproj]
..\src\node_sqlite3.cc(44): error C2661: 'v8::Object::Set' : no overloaded function takes 3 argumen
ts [C:\NETSHARE\data\devprojects\nw\DBUtil\node_modules\sqlite3\build\node_sqlite3.vcxproj]
..\src\node_sqlite3.cc(45): error C2661: 'v8::Object::Set' : no overloaded function takes 3 argumen
ts [C:\NETSHARE\data\devprojects\nw\DBUtil\node_modules\sqlite3\build\node_sqlite3.vcxproj]
..\src\node_sqlite3.cc(46): error C2661: 'v8::Object::Set' : no overloaded function takes 3 argumen
ts [C:\NETSHARE\data\devprojects\nw\DBUtil\node_modules\sqlite3\build\node_sqlite3.vcxproj]
..\src\node_sqlite3.cc(47): error C2661: 'v8::Object::Set' : no overloaded function takes 3 argumen
ts [C:\NETSHARE\data\devprojects\nw\DBUtil\node_modules\sqlite3\build\node_sqlite3.vcxproj]
..\src\node_sqlite3.cc(48): error C2661: 'v8::Object::Set' : no overloaded function takes 3 argumen
ts [C:\NETSHARE\data\devprojects\nw\DBUtil\node_modules\sqlite3\build\node_sqlite3.vcxproj]
..\src\node_sqlite3.cc(49): error C2661: 'v8::Object::Set' : no overloaded function takes 3 argumen
ts [C:\NETSHARE\data\devprojects\nw\DBUtil\node_modules\sqlite3\build\node_sqlite3.vcxproj]
..\src\node_sqlite3.cc(50): error C2661: 'v8::Object::Set' : no overloaded function takes 3 argumen
ts [C:\NETSHARE\data\devprojects\nw\DBUtil\node_modules\sqlite3\build\node_sqlite3.vcxproj]
..\src\node_sqlite3.cc(51): error C2661: 'v8::Object::Set' : no overloaded function takes 3 argumen
ts [C:\NETSHARE\data\devprojects\nw\DBUtil\node_modules\sqlite3\build\node_sqlite3.vcxproj]
..\src\node_sqlite3.cc(52): error C2661: 'v8::Object::Set' : no overloaded function takes 3 argumen
ts [C:\NETSHARE\data\devprojects\nw\DBUtil\node_modules\sqlite3\build\node_sqlite3.vcxproj]
..\src\node_sqlite3.cc(53): error C2661: 'v8::Object::Set' : no overloaded function takes 3 argumen
ts [C:\NETSHARE\data\devprojects\nw\DBUtil\node_modules\sqlite3\build\node_sqlite3.vcxproj]
..\src\node_sqlite3.cc(54): error C2661: 'v8::Object::Set' : no overloaded function takes 3 argumen
ts [C:\NETSHARE\data\devprojects\nw\DBUtil\node_modules\sqlite3\build\node_sqlite3.vcxproj]
..\src\node_sqlite3.cc(55): error C2661: 'v8::Object::Set' : no overloaded function takes 3 argumen
ts [C:\NETSHARE\data\devprojects\nw\DBUtil\node_modules\sqlite3\build\node_sqlite3.vcxproj]
..\src\node_sqlite3.cc(56): error C2661: 'v8::Object::Set' : no overloaded function takes 3 argumen
ts [C:\NETSHARE\data\devprojects\nw\DBUtil\node_modules\sqlite3\build\node_sqlite3.vcxproj]
..\src\node_sqlite3.cc(57): error C2661: 'v8::Object::Set' : no overloaded function takes 3 argumen
ts [C:\NETSHARE\data\devprojects\nw\DBUtil\node_modules\sqlite3\build\node_sqlite3.vcxproj]
..\src\node_sqlite3.cc(58): error C2661: 'v8::Object::Set' : no overloaded function takes 3 argumen
ts [C:\NETSHARE\data\devprojects\nw\DBUtil\node_modules\sqlite3\build\node_sqlite3.vcxproj]
  statement.cc
..\src\statement.cc(105): error C2661: 'v8::Object::Set' : no overloaded function takes 3 arguments
 [C:\NETSHARE\data\devprojects\nw\DBUtil\node_modules\sqlite3\build\node_sqlite3.vcxproj]
..\src\statement.cc(278): warning C4244: 'argument' : conversion from 'int64_t' to 'int', possible
loss of data [C:\NETSHARE\data\devprojects\nw\DBUtil\node_modules\sqlite3\build\node_sqlite3.vcxpro
j]
gyp ERR! build error
gyp ERR! stack Error: `c:\WINDOWS\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit c
ode: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Documents and Settings\admin\Application Data\npm\node
_modules\nw-gyp\lib\build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:810:12)
gyp ERR! System Windows_NT 5.1.2600
gyp ERR! command "node" "C:\Documents and Settings\admin\Application Data\npm\node_modules\nw-
gyp\bin\nw-gyp.js" "rebuild" "--name=sqlite3" "--configuration=Release" "--module_name=node_sqlite
3" "--version=3.0.4" "--major=3" "--patch=4" "--runtime=node-webkit" "--node_abi=node-webkit-v0.11.5
" "--target=0.11.5" "--platform=win32" "--target_platform=win32" "--arch=ia32" "--target_arch=ia32"
"--module_main=./lib/sqlite3" "--host=https://mapbox-node-binary.s3.amazonaws.com/" "--module_path=C
:\NETSHARE\data\devprojects\nw\DBUtil\node_modules\sqlite3\lib\binding\node-webkit-v0.11.5
-win32-ia32" "--module=C:\NETSHARE\data\devprojects\nw\DBUtil\node_modules\sqlite3\lib\bind
ing\node-webkit-v0.11.5-win32-ia32\node_sqlite3.node" "--remote_path=./sqlite3/v3.0.4/" "--package
_name=node-webkit-v0.11.5-win32-ia32.tar.gz" "--staged_tarball=build\stage\sqlite3\v3.0.4\node-w
ebkit-v0.11.5-win32-ia32.tar.gz" "--hosted_path=https://mapbox-node-binary.s3.amazonaws.com/sqlite3/
v3.0.4/" "--hosted_tarball=https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.0.4/node-webkit-v0
.11.5-win32-ia32.tar.gz"
gyp ERR! cwd C:\NETSHARE\data\devprojects\nw\DBUtil\node_modules\sqlite3
gyp ERR! node -v v0.10.33
gyp ERR! nw-gyp -v v0.12.4
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'nw-gyp.cmd rebuild --name=sqlite3 --configuration=
Release --module_name=node_sqlite3 --version=3.0.4 --major=3 --patch=4 --runtime=node-webkit --node_
abi=node-webkit-v0.11.5 --target=0.11.5 --platform=win32 --target_platform=win32 --arch=ia32 --targe
t_arch=ia32 --module_main=./lib/sqlite3 --host=https://mapbox-node-binary.s3.amazonaws.com/ --module
_path=C:\NETSHARE\data\devprojects\nw\DBUtil\node_modules\sqlite3\lib\binding\node-webkit-v0.11.5-wi
n32-ia32 --module=C:\NETSHARE\data\devprojects\nw\DBUtil\node_modules\sqlite3\lib\binding\node-webki
t-v0.11.5-win32-ia32\node_sqlite3.node --remote_path=./sqlite3/v3.0.4/ --package_name=node-webkit-v0
.11.5-win32-ia32.tar.gz --staged_tarball=build\stage\sqlite3\v3.0.4\node-webkit-v0.11.5-win32-ia32.t
ar.gz --hosted_path=https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.0.4/ --hosted_tarball=htt
ps://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.0.4/node-webkit-v0.11.5-win32-ia32.tar.gz' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\NETSHARE\data\devprojects\nw\DBUtil\node
_modules\sqlite3\node_modules\node-pre-gyp\lib\util\compile.js:76:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
node-pre-gyp ERR! stack     at maybeClose (child_process.js:756:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:823:5)
node-pre-gyp ERR! System Windows_NT 5.1.2600
node-pre-gyp ERR! command "node" "C:\NETSHARE\data\devprojects\nw\DBUtil\node_modules\sqlite3
\node_modules\node-pre-gyp\bin\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\NETSHARE\data\devprojects\nw\DBUtil\node_modules\sqlite3
node-pre-gyp ERR! node -v v0.10.33
node-pre-gyp ERR! node-pre-gyp -v v0.6.1
node-pre-gyp ERR! not ok
Failed to execute 'nw-gyp.cmd rebuild --name=sqlite3 --configuration=Release --module_name=node_sqli
te3 --version=3.0.4 --major=3 --patch=4 --runtime=node-webkit --node_abi=node-webkit-v0.11.5 --targe
t=0.11.5 --platform=win32 --target_platform=win32 --arch=ia32 --target_arch=ia32 --module_main=./lib
/sqlite3 --host=https://mapbox-node-binary.s3.amazonaws.com/ --module_path=C:\NETSHARE\data\devproje
cts\nw\DBUtil\node_modules\sqlite3\lib\binding\node-webkit-v0.11.5-win32-ia32 --module=C:\NETSHARE\d
ata\devprojects\nw\DBUtil\node_modules\sqlite3\lib\binding\node-webkit-v0.11.5-win32-ia32\node_sqlit
e3.node --remote_path=./sqlite3/v3.0.4/ --package_name=node-webkit-v0.11.5-win32-ia32.tar.gz --stage
d_tarball=build\stage\sqlite3\v3.0.4\node-webkit-v0.11.5-win32-ia32.tar.gz --hosted_path=https://map
box-node-binary.s3.amazonaws.com/sqlite3/v3.0.4/ --hosted_tarball=https://mapbox-node-binary.s3.amaz
onaws.com/sqlite3/v3.0.4/node-webkit-v0.11.5-win32-ia32.tar.gz' (1)

npm ERR! sqlite3@3.0.4 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sqlite3@3.0.4 install script.
npm ERR! This is most likely a problem with the sqlite3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls sqlite3
npm ERR! There is likely additional logging output above.
npm ERR! System Windows_NT 5.1.2600
npm ERR! command "C:\Program Files\nodejs\\node.exe" "C:\Program Files\nodejs\node_modules\n
pm\bin\npm-cli.js" "install" "sqlite3" "--build-from-source" "--runtime=node-webkit" "--target_arc
h=ia32" "--target=0.11.5"
npm ERR! cwd C:\NETSHARE\data\devprojects\nw\DBUtil
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0

C:\NETSHARE\data\devprojects\nw\DBUtil>

**Comment by rss181919** [comment]
I found that I have to go all the way back to node-webkit target 0.10.5 to get an sqlite3 webkit npm install that doesn't completely fail. Problem is, node-webkit 0.10.5 doesn't come with a build onsite so I have to try to build it myself using MS VStudio 2013 community version.  I will see how that goes and provide another update. Sadly, even if it works, I will have to downgrade node-webkit which means I will lose all the fixes between 0.10.5 and 0.11.5

**Comment by Mithgol** [comment]
See also https://github.com/mapbox/node-sqlite3/issues/328#issuecomment-68789614

**Comment by daniellockyer** [comment]
Would you be able to try with v5.0.3? 🙂
