### ISSUE TITLE
node-webkit compile error

### ISSUE THREAD

**Issue by springmeyer** [TryGhost/node-sqlite3#387]
Impacts node-webkit 0.10.5 and 0.11.5 with latest nan@1.5.0 (https://travis-ci.org/mapbox/node-sqlite3/builds/47189404)

```
  CXX(target) Release/obj.target/node_sqlite3/src/database.o
In file included from ../src/database.h:11:0,
                 from ../src/database.cc:5:
../node_modules/nan/nan.h: In constructor ‘NanAsyncProgressWorker::NanAsyncProgressWorker(NanCallback*)’:
../node_modules/nan/nan.h:1471:5: error: invalid conversion from ‘void (*)(uv_async_t*) {aka void (*)(uv_async_s*)}’ to ‘uv_async_cb {aka void (*)(uv_async_s*, int)}’ [-fpermissive]
/home/travis/.nw-gyp/0.11.5/src/../deps/uv/include/uv.h:1360:15: error:   initializing argument 3 of ‘int uv_async_init(uv_loop_t*, uv_async_t*, uv_async_cb)’ [-fpermissive]
```

**Comment by kkoopa** [comment]
Looks like it is because of the old uv upgrade where they removed the status argument. Doing a typecast to `uv_async_cb` is the best solution. https://github.com/rvagg/nan/issues/97

**Comment by springmeyer** [comment]
Thank you @kkoopa - I replicated the compile error on OS X as well and confirmed that a typecast fixes it (only reinterpret_cast was allowed by compiler, not static_cast). So, created a pull at https://github.com/rvagg/nan/pull/239

**Comment by daniellockyer** [comment]
Closing as this relates to an old version of `node-sqlite3` and should be irrelevant with Node-API 🙂
