### ISSUE TITLE
Failing appveyor runs

### ISSUE THREAD

**Issue by springmeyer** [TryGhost/node-sqlite3#388]
two appveyor targets are failing: https://ci.appveyor.com/project/Mapbox/node-sqlite3/build/1.0.240

```
gyp ERR! stack Error: node.lib local sha1 a0a1d313a37d58a5ed56fd0bd801b4fd4b8c5268 not match remote 7999caa1359645cae722b03b38ebdfdd5b1972c0
```

This looks like a matrix gone wrong... that is building too much.

**Comment by springmeyer** [comment]
oh right, these failing matrix jobs are odd:

```
    - nodejs_version: 0.11.13
      nw_version: 0.11.5
      platform: x64
      msvs_toolset: 12
      BUILD_ARGS: --target=0.11.14
```

They are workarounds for the fact that appveyor's custom `os: Visual Studio 2014 CTP4` we need to use for vs2014 builds does not have node v0.11.14 and so we need to target v0.11.14 using the v0.11.3 binary. Not surprising some hiccup is breaking this....

**Comment by fengmk2** [comment]
https://ci.appveyor.com/project/Mapbox/node-sqlite3/build/1.0.280/job/ug67olqgrtqaawt6#L380

iojs build still fails `Error: Module did not self-register.`

**Comment by daniellockyer** [comment]
This should no longer be relevant 🙂
