### ISSUE TITLE
db.parallelize() needs to run queries in parallel

### ISSUE THREAD

**Issue by JohnLonginotto** [TryGhost/node-sqlite3#394]
Hello all!

SQLite allows parallel read requests from different connections/threads but not from the same connection/thread. This is a limitation of SQLite3 which SQLite4 is hoping to address. You can still send multiple requests in one connection, but they will be executed in series.

It would appear that, since Node is single-threaded, that although calling db.all(..) is non-blocking, it is still only using 1 connection, so all requests are being carried out in series.

Here is the code:
http://paste.ofcode.org/AGBTgSkUbFdkDCBBdaaxq8

Here is the result:
http://paste.ofcode.org/PdqKswqYXQyE7DpAQi9h8C

If I run all of these queries in parallel from the command line (by putting all the requests in a shell script and adding & to the end) it takes as long as the First Query does to return (for all queries).
If i remove the & so they are run in series, it takes as long as Node.js does.

All the best,
John

**Comment by JohnLonginotto** [comment]
I should note, that adding a db.parallelize() and db.serialize() around those five queries has the following effect:

With db. parallelize() :
First Query Start:1421706478057 - End: 1421706491705 -- Duration: 13648ms
Second Query Start:1421706478058 - End: 1421706540996 -- Duration: 62938ms
Third Query Start:1421706478058 - End: 1421706541004 -- Duration: 62946ms
Fourth Query Start:1421706478058 - End: 1421706541004 -- Duration: 62946ms
Fifth Query Start:1421706478058 - End: 1421706541005 -- Duration: 62947ms
Whole request took 62949ms

With db. serialize() :
First Query Start:1421706594382 - End: 1421706608062 -- Duration: 13680ms
Second Query Start:1421706594383 - End: 1421706620543 -- Duration: 26160ms
Third Query Start:1421706594383 - End: 1421706630624 -- Duration: 36241ms
Fourth Query Start:1421706594383 - End: 1421706644102 -- Duration: 49719ms
Fifth Query Start:1421706594383 - End: 1421706657623 -- Duration: 63240ms
Whole request took 63243ms

**Comment by daniellockyer** [comment]
Closing as this issue is stale 🙂
