### ISSUE TITLE
Statement#run and maybe other methods of Statement tend to forget previously bound parameters when called with an undefined or null callback

### ISSUE THREAD

**Issue by silkentrance** [TryGhost/node-sqlite3#397]
Considering the following code snipped (OTOH)

``` js
var sqlCreateTable = 'CREATE TABLE kv (key TEXT PRIMARY KEY, value TEXT NULL)';
db.run(sqlCreateTable);
var sqlInsert = 'INSERT INTO kv (key, value) VALUES ($key, $value)';
var prepared = db.prepare(sqlInsert);
prepared.bind({$key:'will', $value : 'not work'});
var callback;
prepared.run(callback);
```

The prepared statement will forget about the previously bound parameters and instead will insert a row into the table that has both a null key and a null value.

Either, the C++ Bind<?> method must throw an error that not all parameters could have been bound or it should simply ignore a single null/undefined parameter.

In either case, I would expect the API to honor the previously bound parameters instead of replacing them altogether with an invalid parameterization.

**Comment by daniellockyer** [comment]
I can't seem to reproduce this so I'm going to close the issue 🙂
