### ISSUE TITLE
Split appveyor to test node-webkit and node.js separately

### ISSUE THREAD

**Issue by springmeyer** [TryGhost/node-sqlite3#409]
@Mithgol - currently the appveyor scripts test both node.js and node-webkit at the same time, correct? I think we should only test node-webkit or node.js per matrix item. This will make it much easier to see quickly whether the failure is due to both failing or just one of the runtimes. Do you agree? This is the way the .travis.yml works currently.

**Comment by Mithgol** [comment]
I agree.

**Comment by Mithgol** [comment]
If you have such matrix ready in your mind, commit it to the `nwjs` branch.

If you don't, I might commit something like that (but not before [tomorrow](https://en.wikipedia.org/wiki/Moscow_Time)).

**Comment by springmeyer** [comment]
I don't have anything in mind, just logging the idea. If you have time to consider breaking apart the matrix tomorrow that would be amazing.

**Comment by daniellockyer** [comment]
Closing as we no longer use Appveyor 🙂
