### ISSUE TITLE
Separate npm for sqlcipher?

### ISSUE THREAD

**Issue by coolaj86** [TryGhost/node-sqlite3#417]
Should we have a separate npm package for sqlcipher?

To me it seems different enough to deserve it's own package and its own pre-built bins. What do you think?

**Related Note**: #418

**Comment by nisargjhaveri** [comment]
I agree with you.

I think, someone tried to do something on these lines, but it is not maintained anymore. https://github.com/delaballe/node-sqlcipher

If you or someone can create and maintain a separate package for sqlcipher, it would be of great help.
Thanks :)

**Comment by fritx** [comment]
Hello there
Ive just created a package https://github.com/fritx/cross-sqlcipher
which was a built on top of node-sqlite3.

Current it works with node and cross-platform.
And I will make it work with nwjs and electron soon.

**Comment by fritx** [comment]
cross-sqlcipher contains just scripts that help you land things, without any sqlite logic.
So there is no duplication or over-design.

**Comment by daniellockyer** [comment]
It's possibly a good idea but out of scope for this project and the issue is stale, so I'm going to close it 🙂
