### ISSUE TITLE
Notification callbacks

### ISSUE THREAD

**Issue by toomim** [TryGhost/node-sqlite3#419]
Sqlite features [data-change notification callbacks](https://www.sqlite.org/c3ref/update_hook.html) that tell you when a particular table has been modified. This is super useful for writing realtime, reactive web servers, that notify all connected clients when data has changed. But there's no support for this notification API in node-sqlite3.

Would bindings for this be easy to add to node-sqlite3? I understand that sqlite runs in a different thread, so I imagine that the thread would need to communicate with the v8 thread, to call a notification method, and just pass it these parameters:
- A string `"insert"`, `"delete"`, or `"update"` describing the type of change
- The database
- The table name
- The `rowid` of the row

**Comment by carbureted** [comment]
+1, this should be great to have. Polling my db way too much right now..

**Comment by JohnKossa** [comment]
+1, for those of us using sqlite for a program inter-op layer, the ability to get notifications on change would be incredibly helpful

**Comment by JohnKossa** [comment]
Already added in commit https://github.com/mapbox/node-sqlite3/commit/b8f718c7ab416864518ba3460b15595fbcdf1eba.

That being said, this doesn't appear to be anywhere in the [README](https://github.com/mapbox/node-sqlite3/blob/master/README.md) or the [API](https://github.com/mapbox/node-sqlite3/wiki/API).

**Comment by carbureted** [comment]
Huh, cool. I can't test right now, but it looks like it would be used something like the following?

var db = new sqlite3.Database(file, ['sqlite3.OPEN_READONLY']);

db.on('insert', function() {
  console.log('inserted!')
})

**Comment by kingcheez** [comment]
That commit is missing a corresponding change in `Database::Configure` as far as I can tell.

**Comment by devlesedi** [comment]
Is there a solution for this? On my web app I want to listen to data changes.

**Comment by samiralajmovic** [comment]
This feature would be really nice to have.

**Comment by ushalin** [comment]
Any update on this feature?

**Comment by natew** [comment]
Would be awesome to see!

**Comment by bpasero** [comment]
I am able to get the events working (with this change: https://github.com/bpasero/node-sqlite3/commit/1f1e2c863328cfd40e43fd1c672564eeead0de86). However, this event does NOT work when multiple connections are used across multiple processes. I believe they only work for a single connection.

**Comment by vishnuprasad-95** [comment]
Any update on this?

**Comment by pwner4once** [comment]
Any update on this feature? It seens rather useful to have but why is this fallen on silent ears?

**Comment by daniellockyer** [comment]
There is an open PR to fix the implementation here: https://github.com/TryGhost/node-sqlite3/pull/1267

**Comment by maxpert** [comment]
Merge it please 😢  I desperately need it!

**Comment by daniellockyer** [comment]
The PR is merged and will be released shortly 🙂

**Comment by maxpert** [comment]
🥳
