### ISSUE TITLE
loadExtension on Windows 8.1 throws error

### ISSUE THREAD

**Issue by elgarf** [TryGhost/node-sqlite3#432]
I tried to load some extensions, that works in sqlite3 cli, but they are not worked at server with

SQLITE_ERROR: %1 is not valid Win32 application.

Extensions works good on Ubuntu Server 14.

**Comment by springmeyer** [comment]
How did you build the extension and what is it exactly?

**Comment by elgarf** [comment]
I built it by MSVSC or GCC, it's ICU extension from sources of sqlite3. Simple test extension also doesn't work.

**Comment by daniellockyer** [comment]
Closing as issue is stale 🙂
