### ISSUE TITLE
Crash on 0.10.38 finalizing a statement while aborting an https request

### ISSUE THREAD

**Issue by briangreenery** [TryGhost/node-sqlite3#439]
I'm seeing a node.js assertion failure that causes node to crash if I `abort()` an https request and `finalize()` a statement during the https `'response'` event.

Node crashes with:

```
node: ../src/node_http_parser.cc:459: static v8::Handle<v8::Value> node::Parser::Finish(const v8::Arguments&): Assertion `!current_buffer' failed.
```

Here's code that causes the crash:

https://gist.github.com/briangreenery/bbb917b470e958626167

I've reproduced this on node 0.10.38 on Ubuntu 14.04 and Mac.
I have not been able to reproduce this on 0.12.2 or io.js 1.7.1. I also have not been able to reproduce this on 0.10.38 on Windows.

It seems like a work-around is to defer calling `finalize()` until `process.nextTick`.

**Comment by springmeyer** [comment]
This crash is happening in node.js itself and not node-sqlite3. Have you considered filing a ticket upstream at node?

**Comment by briangreenery** [comment]
I didn't. I'm not familiar enough with this module to know whether it's a bug in node itself. I wonder if it's related to https://github.com/iojs/nan/issues/284 though.

**Comment by springmeyer** [comment]
k, looks like at least one other similiar report at https://github.com/joyent/node/issues/1574

**Comment by daniellockyer** [comment]
Closing as it doesn't seem related to `node-sqlite3` 🙂
