### ISSUE TITLE
Expose sqlite3.OPEN_FULLMUTEX

### ISSUE THREAD

**Issue by briangreenery** [TryGhost/node-sqlite3#450]
This can be used as an integer, but it'd be nice if there was a property for it.

**Comment by fritx** [comment]
+1

As in (https://github.com/mapbox/node-sqlite3/blob/d5b59c3133f22fd9eefd74c6bd7f702b65601a00/src/node_sqlite3.cc#L21-L23), `OPEN_FULLMUTEX` is not exposed.

However, in (https://github.com/mapbox/node-sqlite3/blob/d5b59c3133f22fd9eefd74c6bd7f702b65601a00/src/database.cc#L121), default mode is `OPEN_READWRITE | OPEN_CREATE | OPEN_FULLMUTEX`.

How can I `new Database('xx.db', OPEN_READWRITE | OPEN_CREATE | OPEN_FULLMUTEX)` in JavaScript side?

**Comment by fritx** [comment]
```plain
OPEN_READONLY: 1
OPEN_READWRITE: 2
OPEN_CREATE: 4
```

I guess value of `OPEN_FULLMUTEX ` is 8. So we have the workaround. ;)

**Comment by fritx** [comment]
This is also missing in [wiki](https://github.com/mapbox/node-sqlite3/wiki/API#new-sqlite3databasefilename-mode-callback).

**Comment by daniellockyer** [comment]
This is now exposed [here](https://github.com/TryGhost/node-sqlite3/blob/73da4108b9aceb447669e050d172e31ec229bbe1/src/node_sqlite3.cc#L27) and the wiki has been updated 🙂
