### ISSUE TITLE
Bulk insert

### ISSUE THREAD

**Issue by pixelmanya** [TryGhost/node-sqlite3#467]
Hey people,

I wrote a script which creates dynamically a database with some tables in it. Afterwards I want to insert ca. 70 datasets into one table. But every time I get the message "Segmentation Fault: 11". The script exits when trying to iterate (and inserting) over those datasets. If you need the complete script, let me know. 

Basically my question is: Am I doing something wrong? :(

```
            // create table `thermische_eigenschaften`
            db.serialize(function(){
                var 
                    fieldsCount = 2 + thermicProperties.length,
                    query = 'CREATE TABLE `' + tableName + '` (`id` INTEGER PRIMARY KEY AUTOINCREMENT, `polymer_id` INTEGER, ' + function(){ 
                        var str = '';

                        thermicProperties.forEach(function(item){
                            str += '`' + item.field + '` TEXT,';
                        });

                        return str.substr(0, str.length - 1);
                    }() + ')';

                // create table
                db.run(query);

                // insert values
                var stmt = db.prepare('INSERT INTO `' + tableName + '` VALUES (?, ?, ' + function(){
                    var str = '';

                    thermicProperties.forEach(function(){
                        str += '?, ';
                    });

                    return str.substr(0, str.length - 2);
                }() +')');

                stmt.finalize(function(){
                    console.log('Database created!');
                    db.close();
                });

                polymer.forEach(function(polymerItem, polymerIndex){
                    var args = getFieldValues(polymerItem, (polymerIndex+1));
                    stmt.run.apply(null, args);
                });
            });
```

**Comment by pixelmanya** [comment]
Okay, I think the problem is this snippet:

```
...
stmt.run.apply(null, args);
...
```

If I pass the arguments not "dynamically", then it works. Like this:

```
				polymer.forEach(function(polymerItem, polymerIndex){
					stmt.run(null, polymerItem.id, '', '', '', '', '', '', '', '', '', '', '', '', '', function(){
						console.log('Dataset created');
					});
				});
```

Any idea why I can't use stmt.run.apply here?

**Comment by kkaefer** [comment]
Glad you figured out out. However, there should not be a segfault in the first place since the API should be safe whatever you do.

**Comment by kkaefer** [comment]
Also, please don't pass user-provided input into SQLite as a stringified query. Instead, you should use placeholders.

**Comment by pixelmanya** [comment]
Hey kkaefer,

Thanks for your response. This solved my problem:

```
stmt.run.apply(stmt, args);
```

instead of passing null as first parameter. Took me some time to figure it out ;)

**Comment by springmeyer** [comment]
> there should not be a segfault in the first place since the API should be safe whatever you do.

@pixelmanya can you please reduce a testcase for that crash?

**Comment by zengzutao** [comment]
@kkaefer @pixelmanya 
Hi, everyone：
      I wrote a method of inserting data in batches, but this method is unstable, the number of data inserted is wrong, and data loss occurs!
Could you tell me where I was wrong? Thanks very much！
The following is a batch insertion method I wrote：
1:var sqlite3 = require('sqlite3').verbose();
var path = require("path");
var dbName = "sqlite3.db";
var db = null;

db= function() {
    if (db == null) {
        db = new sqlite3.Database(path.resolve() + '\/' + dbName);
    }
    return db;
};

2: function(dataList, cb) {
    db.run("delete from tb_article_price");
    var stmt = db.prepare("insert into tb_article_price values($id, $unit_ids, $name, $price, $fans_price, $article_id, $stock_working_day, $stock_weekend," +
        " $current_working_stock, $shop_detail_id, $sort, $empty_remark)");
    dataList.map(function(entity) {
        stmt.run({
            $id: entity.id,
            $unit_ids: entity.unitIds,
            $name: entity.name,
            $price: entity.price,
            $fans_price: entity.fansPrice,
            $article_id: entity.articleId,
            $stock_working_day: entity.stockWorkingDay,
            $stock_weekend: entity.stockWeekend,
            $current_working_stock: entity.currentWorkingStock,
            $shop_detail_id: httpClientConfig.shopId,
            $sort: entity.sort,
            $empty_remark: entity.emptyRemark,
        });
    });
    stmt.finalize();
    cb && cb();
};

**Comment by daniellockyer** [comment]
Closing because issue is stale 🙂
