### ISSUE TITLE
node-pre-gyp install --fallback-to-build

### ISSUE THREAD

**Issue by topoluc** [TryGhost/node-sqlite3#481]
https://github.com/mapbox/node-sqlite3/issues/478

Sorry but it doesn´t work for me.
I am getting the same problem.

**Comment by springmeyer** [comment]
@topoluc please provide as much detail as you can. Your issue is likely different. share the entire output from your terminal and details of your platform and how you installed node.

**Comment by topoluc** [comment]
Sorry.

I am a Windows Vista user. I installed node version 0.12.7 with the windows installer package from https://nodejs.org.

I also have installed visual c++ 2010 and python 2.7.3 as explained in https://github.com/mapbox/node-sqlite3/wiki/Building-on-Windows

Here is the entire output from my terminal:

> sqlite3@3.0.9 install C:\mis_proyectos\quiz\node_modules\sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! install error
node-pre-gyp ERR! stack Error: quiz package.json is not node-pre-gyp ready:
node-pre-gyp ERR! stack package.json must declare these properties:
node-pre-gyp ERR! stack main
node-pre-gyp ERR! stack binary.module_name
node-pre-gyp ERR! stack binary.module_path
node-pre-gyp ERR! stack binary.host
node-pre-gyp ERR! stack     at validate_config (C:\mis_proyectos\quiz\node_modul
es\sqlite3\node_modules\node-pre-gyp\lib\util\versioning.js:187:15)
node-pre-gyp ERR! stack     at Object.module.exports.evaluate (C:\mis_proyectos\
quiz\node_modules\sqlite3\node_modules\node-pre-gyp\lib\util\versioning.js:233:5
)
node-pre-gyp ERR! stack     at install (C:\mis_proyectos\quiz\node_modules\sqlit
e3\node_modules\node-pre-gyp\lib\install.js:138:31)
node-pre-gyp ERR! stack     at Object.self.commands.(anonymous function) [as ins
tall] (C:\mis_proyectos\quiz\node_modules\sqlite3\node_modules\node-pre-gyp\lib\
node-pre-gyp.js:48:37)
node-pre-gyp ERR! stack     at run (C:\mis_proyectos\quiz\node_modules\sqlite3\n
ode_modules\node-pre-gyp\bin\node-pre-gyp:79:30)
node-pre-gyp ERR! stack     at Object.<anonymous> (C:\mis_proyectos\quiz\node_mo
dules\sqlite3\node_modules\node-pre-gyp\bin\node-pre-gyp:131:1)
node-pre-gyp ERR! stack     at Module._compile (module.js:460:26)
node-pre-gyp ERR! stack     at Object.Module._extensions..js (module.js:478:10)
node-pre-gyp ERR! stack     at Module.load (module.js:355:32)
node-pre-gyp ERR! stack     at Function.Module._load (module.js:310:12)
node-pre-gyp ERR! System Windows_NT 6.0.6002
node-pre-gyp ERR! command "node" "C:\\mis_proyectos\\quiz\\node_modules\\sqlite3
\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"

node-pre-gyp ERR! cwd C:\mis_proyectos\quiz
node-pre-gyp ERR! node -v v0.12.7
node-pre-gyp ERR! node-pre-gyp -v v0.6.8
node-pre-gyp ERR! not ok
quiz package.json is not node-pre-gyp ready:
package.json must declare these properties:
main
binary.module_name
binary.module_path
binary.host
npm ERR! Windows_NT 6.0.6002
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs
\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save" "sqlite3"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE

npm ERR! sqlite3@3.0.9 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sqlite3@3.0.9 install script 'node-pre-gyp install --fall
back-to-build'.
npm ERR! This is most likely a problem with the sqlite3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls sqlite3
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\mis_proyectos\quiz\npm-debug.log

**Comment by springmeyer** [comment]
the problem appears to be with the current working directory when installing. What is happening is that `node-pre-gyp` (the tool used internally by `node-sqlite3` to install binaries) thinks it is inside the `C:\mis_proyectos\quiz\` directory rather than `C:\mis_proyectos\quiz\node_modules\sqlite3` during the install. So this seems like some kind of mis-configuration in your node.js install.

BTW, you do not need visual studio 2010 and python to install node-sqlite3 (since node-sqlite3 will install via binaries).

**Comment by immershy** [comment]
cd into the package dir, execute:
nw-gyp rebuild --target=0.12.3
change the target param to your node version
worked for me

**Comment by dfsq1311** [comment]
try to use '--directory=node_modules/your-build-modules' and make sure the package.json format is write

**Comment by IgnacioYanjari** [comment]
@godvein 
Sorry but it doesn´t work for me.
I am getting the same problem.

**Comment by IgnacioYanjari** [comment]
try to updgrade to bcrypt v2.0.0

**Comment by Dane456** [comment]
@springmeyer led me in the right direction, it was using `node-pre-gyp` from `node_modules` within my specific node version within my `~/.nvm/versions/node` directory

**Comment by muralithiyagarajan** [comment]
> nw-gyp rebuild --target=0.12.3

node-pre-gyp" "rebuild" "--target=10.15.3"
node-pre-gyp ERR! cwd C:\Users\Administrator\Documents\GitHub\boda\bts-ce-lite\node_modules\node-gyp
node-pre-gyp ERR! node -v v10.15.3
node-pre-gyp ERR! node-pre-gyp -v v0.13.0
node-pre-gyp ERR! This is a bug in `node-pre-gyp`.
node-pre-gyp ERR! Try to update node-pre-gyp and file an issue if it does not help:
node-pre-gyp ERR!     <https://github.com/mapbox/node-pre-gyp/issues>

**Comment by daniellockyer** [comment]
Would you be able to try with v5.0.3? 🙂
