### ISSUE TITLE
Unable to build sqlite3 for nwjs (node-webkit)

### ISSUE THREAD

**Issue by prasanthkodali** [TryGhost/node-sqlite3#497]
Hi,

I am trying to install sqlite3 for nwjs v0.12.3. I followed the instructions to build for nwjs using nw-gyp. But when I do that, the build fails. The following is the exact command I used and the output of the command:
# 

sudo npm install -g sqlite3 --build-from-source --runtime=node-webkit --target_arch=x64 --target="0.12.3"
/

> sqlite3@3.0.10 install /usr/local/lib/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

child_process: customFds option is deprecated, use stdio instead.
child_process: customFds option is deprecated, use stdio instead.
ACTION deps_sqlite3_gyp_action_before_build_target_unpack_sqlite_dep Release/obj/gen/sqlite-autoconf-3081101/sqlite3.c
TOUCH Release/obj.target/deps/action_before_build.stamp
CC(target) Release/obj.target/sqlite3/gen/sqlite-autoconf-3081101/sqlite3.o
Release/obj/gen/sqlite-autoconf-3081101/sqlite3.c:9117:26: warning: unused variable 'sqlite3one' [-Wunused-const-variable]
SQLITE_PRIVATE const int sqlite3one = 1;
^
1 warning generated.
LIBTOOL-STATIC Release/sqlite3.a
CXX(target) Release/obj.target/node_sqlite3/src/database.o
In file included from ../src/database.cc:2:
/Users/User1/.nw-gyp/0.12.3/src/node.h:55:10: fatal error: 'v8.h' file not found
# include "v8.h"  // NOLINT(build/include_order)

^
1 error generated.
make: **\* [Release/obj.target/node_sqlite3/src/database.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/nw-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Darwin 14.4.0
gyp ERR! command "node" "/usr/local/bin/nw-gyp" "build" "--fallback-to-build" "--module=/usr/local/lib/node_modules/sqlite3/lib/binding/node-webkit-v0.12.3-darwin-x64/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/usr/local/lib/node_modules/sqlite3/lib/binding/node-webkit-v0.12.3-darwin-x64"
gyp ERR! cwd /usr/local/lib/node_modules/sqlite3
gyp ERR! node -v v0.12.7
gyp ERR! nw-gyp -v v0.12.4
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'nw-gyp build --fallback-to-build --module=/usr/local/lib/node_modules/sqlite3/lib/binding/node-webkit-v0.12.3-darwin-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/usr/local/lib/node_modules/sqlite3/lib/binding/node-webkit-v0.12.3-darwin-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/sqlite3/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
node-pre-gyp ERR! stack     at maybeClose (child_process.js:1015:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
node-pre-gyp ERR! System Darwin 14.4.0
node-pre-gyp ERR! command "node" "/usr/local/lib/node_modules/sqlite3/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/local/lib/node_modules/sqlite3
node-pre-gyp ERR! node -v v0.12.7
node-pre-gyp ERR! node-pre-gyp -v v0.6.9
node-pre-gyp ERR! not ok
Failed to execute 'nw-gyp build --fallback-to-build --module=/usr/local/lib/node_modules/sqlite3/lib/binding/node-webkit-v0.12.3-darwin-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/usr/local/lib/node_modules/sqlite3/lib/binding/node-webkit-v0.12.3-darwin-x64' (1)
npm ERR! Darwin 14.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "sqlite3" "--build-from-source" "--runtime=node-webkit" "--target_arch=x64" "--target=0.12.3"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE

npm ERR! sqlite3@3.0.10 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sqlite3@3.0.10 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the sqlite3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls sqlite3
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
# npm ERR!     /Users/User1/npm-debug.log

I have node version 0.12.7 and nwjs version 0.12.3 installed in Mac OS X Yosemite. 

Any help with respect to resolving the above issue will of great help.

Thanks in advance,
- Prasanth.

**Comment by springmeyer** [comment]
nwjs 0.12.x is not supported at this time. Only 0.10.x and 0.8.x /cc @Mithgol

**Comment by hems** [comment]
I just managed to install and use it with nwjs 0.12.3 and it worked ( :

**Comment by hems** [comment]
In my case i build for the OSX 32 bits, so after npm install i also ran:
````
npm install sqlite3 --build-from-source --runtime=node-webkit --target_arch=ia32 --target=0.12.3
````

i got a couple of errors here and there when updating to the new nwjs, but eventually it runs and works.

**Comment by jonataswalker** [comment]
In my case was a python (v2, v3) issue so:

```shell
$ mkdir ~/bin
$ ln -s /usr/bin/python2 ~/bin/python
$ ln -s /usr/bin/python2-config ~/bin/python-config
```

**Comment by premalatha-bv** [comment]
Did anyone get it working for nwjs version 0.39.0  in Mac/windows machine? Could you please share your thoughts here.

**Comment by daniellockyer** [comment]
Would you be able to try with v5.0.3? 🙂
