### ISSUE TITLE
unable to install on FreeBSD 9.3-STABLE

### ISSUE THREAD

**Issue by ghost** [TryGhost/node-sqlite3#499]
npm, node, sqlite3 installed from ports

All available cases tried from Installation section https://github.com/mapbox/node-sqlite3

It is the same result in any cases as pointed bellow:

[ root@example.org /usr/www/vhosts/example.org ] # npm install https://github.com/mapbox/node-sqlite3/tarball/master
npm WARN installMany node-pre-gyp was bundled with sqlite3@3.0.10, but bundled package wasn't found in unpacked tree

> sqlite3@3.0.10 install /usr/www/vhosts/example.org/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/0.12.7"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/www/vhosts/example.org/node_modules/sqlite3/.node-gyp"
gmake: Entering directory '/usr/www/vhosts/example.org/node_modules/sqlite3/build'
gmake: **\* No rule to make target '../.node-gyp/0.12.7/common.gypi', needed by 'Makefile'.  Stop.
gmake: Leaving directory '/usr/www/vhosts/example.org/node_modules/sqlite3/build'
gyp ERR! build error
gyp ERR! stack Error: `gmake` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System FreeBSD 9.3-STABLE
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/usr/www/vhosts/example.org/node_modules/sqlite3/lib/binding/node-v14-freebsd-x64/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/usr/www/vhosts/example.org/node_modules/sqlite3/lib/binding/node-v14-freebsd-x64"
gyp ERR! cwd /usr/www/vhosts/example.org/node_modules/sqlite3
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/usr/www/vhosts/example.org/node_modules/sqlite3/lib/binding/node-v14-freebsd-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/usr/www/vhosts/example.org/node_modules/sqlite3/lib/binding/node-v14-freebsd-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/www/vhosts/example.org/node_modules/sqlite3/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
node-pre-gyp ERR! stack     at maybeClose (child_process.js:1015:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
node-pre-gyp ERR! System FreeBSD 9.3-STABLE
node-pre-gyp ERR! command "node" "/usr/www/vhosts/example.org/node_modules/sqlite3/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/www/vhosts/example.org/node_modules/sqlite3
node-pre-gyp ERR! node -v v0.12.7
node-pre-gyp ERR! node-pre-gyp -v v0.6.9
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/usr/www/vhosts/example.org/node_modules/sqlite3/lib/binding/node-v14-freebsd-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/usr/www/vhosts/example.org/node_modules/sqlite3/lib/binding/node-v14-freebsd-x64' (1)
npm ERR! FreeBSD 9.3-STABLE
npm ERR! argv "node" "/usr/local/bin/npm" "install" "https://github.com/mapbox/node-sqlite3/tarball/master"
npm ERR! node v0.12.7
npm ERR! npm  v2.13.5
npm ERR! code ELIFECYCLE

npm ERR! sqlite3@3.0.10 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sqlite3@3.0.10 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the sqlite3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls sqlite3
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/www/vhosts/example.org/npm-debug.log

**Comment by cocsosoft** [comment]
Unable to attach npm-debug.log. I can send you by e-mail if you need.

**Comment by springmeyer** [comment]
please do not install as the root user. Install as a normal user.
