### ISSUE TITLE
Add Spatialite Extensions

### ISSUE THREAD

**Issue by hallahan** [TryGhost/node-sqlite3#526]
Has anybody considered packaging up SQLite with Spatialite in the gyp build? How hard would this be?

**Comment by springmeyer** [comment]
It should be doable if you compile libspatialite as a dynamic library and link it against the same version of libsqlite3 that is bundled. See https://github.com/mapbox/node-sqlite3/blob/ad7596709ba80ee3f3b60cbdb663bafa1ebaa2f9/test/extension.test.js for an example of how to load the extension.

**Comment by hallahan** [comment]
Would this work the same with a .so? I'd need this working on Linux as well as OS X. Thanks Dane!

**Comment by springmeyer** [comment]
> Would this work the same with a .so?

Yes, should. Ideally we could re-enable that test to be run on travis again and to detect the platform in order to choose `dylib` vs `so`. Interested in trying to get that test running again?

To avoid the pitfall/crash I mention in https://github.com/mapbox/node-sqlite3/commit/dabc937f4564e1af064b6cec41ba528e61789258 we could potentially build the `libspatialite.dylib|so` dynamically on travis and pull it in for the tests as needed (rather than hardcoding the `/usr/...` path which never worked.

**Comment by hallahan** [comment]
Sure. I'm having an issue with the current mocha test setup. I'm just doing a simple install via `npm install`. Then I run `make test`, and for each test, I get

```
1 failing

  1) each "before all" hook:
     Error: SQLITE_CANTOPEN: unable to open database file
      at Error (native)
```

Perhaps I am installing incorrectly? I'm not exactly clear with the [source install](https://github.com/mapbox/node-sqlite3#source-install) instructions.

**Comment by shenzhuxi** [comment]
I found that mod_spatialite can be loaded but can't be used. 
The behaviour is very similar to better-sqlite3, https://github.com/JoshuaWise/better-sqlite3/issues/520#issuecomment-1024265223. 
After loadExtension, it will fail at "InitSpatialMetaData". I guess https://github.com/mapbox/node-sqlite3/blob/593c9d498be2510d286349134537e3bf89401c4a/test/extension.test.js only did the the load test. 

I wonder if anyone has really **USE** spatialite successfully here.

**Comment by daniellockyer** [comment]
I'm going to close this for now but please feel free to open a new issue if there's a request or bug here 🙂

**Comment by shenzhuxi** [comment]
better-sqlite3 fixed it by adding SQLITE_OMIT_GET_TABLE to the compile-time options.

https://github.com/WiseLibs/better-sqlite3/pull/1137/files
