### ISSUE TITLE
"File Not Found" loading on Linux ARM platform

### ISSUE THREAD

**Issue by bpmcnutt** [TryGhost/node-sqlite3#528]
I am encountering the following issue when attempting to load a Web app on an Atmel Cortex-A5 system:
# node ./bin/www

random: nonblocking pool is initialized

module.js:356
  Module._extensions[extension](this, filename);
                               ^
Error: File not found
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/MMCC2/node_modules/sqlite3/lib/sqlite3.js:4:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
# 

This occurs after placing the ARM binary (node-v11-linux-arm) under the binding path. The version of node is 0.10.40 provided with the latest stable build of Buildroot. Attempts to use npm rebuild also fail with the following result: 
# npm rebuild

> sqlite3@3.1.0 install /MMCC2/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: getaddrinfo ENOTFOUND
gyp ERR! stack     at errnoException (dns.js:37:11)
gyp ERR! stack     at Object.onanswer [as oncomplete](dns.js:124:16)
gyp ERR! System Linux 3.18.8
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/MMCC2/node_modules/sqlite3/lib/binding/node-v11-linux-arm/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/MMCC2/node_modules/sqlite3/lib/binding/node-v11-linux-arm"
gyp ERR! cwd /MMCC2/node_modules/sqlite3
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/MMCC2/node_modules/sqlite3/lib/binding/node-v11-linux-arm/node_sqlite3.node --module_name=node_sqlite3 --module_path=/MMCC2/node_modules/sqlite3/lib/binding/node-v11-linux-arm' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/MMCC2/node_modules/sqlite3/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
node-pre-gyp ERR! stack     at maybeClose (child_process.js:766:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:833:5)
node-pre-gyp ERR! System Linux 3.18.8
node-pre-gyp ERR! command "node" "/MMCC2/node_modules/sqlite3/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /MMCC2/node_modules/sqlite3
node-pre-gyp ERR! node -v v0.10.40
node-pre-gyp ERR! node-pre-gyp -v v0.6.10
node-pre-gyp ERR! not ok 
Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/MMCC2/node_modules/sqlite3/lib/binding/node-v11-linux-arm/node_sqlite3.node --module_name=node_sqlite3 --module_path=/MMCC2/node_modules/sqlite3/lib/binding/node-v11-linux-arm' (1)

npm ERR! sqlite3@3.1.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sqlite3@3.1.0 install script.
npm ERR! This is most likely a problem with the sqlite3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls sqlite3
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.18.8
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "rebuild"
npm ERR! cwd /MMCC2
npm ERR! node -v v0.10.40
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /MMCC2/npm-debug.log
npm ERR! not ok code 0
#

**Comment by daniellockyer** [comment]
Would you be able to try with v5.0.3? 🙂
