### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by xrisk** [TryGhost/node-sqlite3#551]
Here’s the output from `npm install sqlite3 --loglevel=verbose`. 

https://gist.github.com/xrisk/1721eaecc689248279a7

And npm-debug.log: https://gist.github.com/93d59eda8339187d158d

I’m running v5.0.0 of node.

**Comment by ErisDS** [comment]
Support for node v5.0.0 was addd in [sqlite3 v3.1.1](https://github.com/mapbox/node-sqlite3/blob/master/CHANGELOG.md#311). You're trying to install v3.0.8 so the node version and sqlite3 version are not compatible.
