### ISSUE TITLE
TypeError on ECMAScript 6 arrow function as a callback for db#run()

### ISSUE THREAD

**Issue by iolo** [TryGhost/node-sqlite3#560]
I know, this is not a bug ;)

the code below:

```
db.run(..., (err) => { ... });
```

throws error:

```
     Uncaught TypeError: Cannot read property 'changes' of undefined
      at Statement.<anonymous> (src/plugins/sqlite.js:75:56)
  --> in Statement#run([Function])
      at Database.<anonymous> (node_modules/sqlite3/lib/sqlite3.js:74:19)
      at Database.<anonymous> (node_modules/sqlite3/lib/sqlite3.js:21:19)
      at src/plugins/sqlite.js:70:16
      at set (src/plugins/sqlite.js:66:16)
      at Statement.<anonymous> (src/plugins/sqlite.js:56:17)
```

this works fine:

``` js
db.run(..., function (err) { ... });
```

by the node-sqlite3 document `db.run()` `callback` is bound with `statement`:
https://github.com/mapbox/node-sqlite3/wiki/API#databaserunsql-param--callback

but ES6 arrow function is already bound with lexical `this`:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions

I don't know how to allow ES6 arrow function as callback, without API breakage. :S

**Comment by dgollub** [comment]
Yeah, I am running into the same problem and it would be nice if there was a solution other than falling back to using ES5 syntax.

Could you add the implicit "this" as 2nd callback parameter instead, it the callback would/could be ```(err, stmt) => {})``` instead? That would be helpful here.

**Comment by rnewman** [comment]
You might be interested in https://github.com/mozilla/promise-sqlite, which wraps most of the sharp edges of the API.
