### ISSUE TITLE
npm install sqlite3 with python3.4.2

### ISSUE THREAD

**Issue by slb1958** [TryGhost/node-sqlite3#569]
I can not install sqlite3 with python 3.4.2 because it is not supported by gyp. I can not install Python 2.7 on my system, so I wondered if there is an alternative to have the sqlite3 installed with this version of Python?
thanjs

**Comment by ErisDS** [comment]
You shouldn't need Python at all unless you're on quite an obscure system. Please read this: https://github.com/mapbox/node-sqlite3/wiki/Binaries.

**Comment by slb1958** [comment]
Thanks ErisDS,
I am not in an obscure system, but it is a special installation and very recent installation of nodejs, I am talking about an IBM I with an operating system (OS400) and a relational database (DB2), and open source packages are installed via (PASE - PASE for i is an integrated runtime for porting selected applications from AIX and other UNIX operating systems). Recently I understand there are some issues with some packages installation, and the fixes are on the way,  hopefully soon this is solved.
