### ISSUE TITLE
Problem with sync of operations

### ISSUE THREAD

**Issue by VinobaGungabissoon** [TryGhost/node-sqlite3#570]
When I run this JS file through Run in Webstorm IDE, I get a strange order of operations

``` javascript
var records = [];

console.log('hello start');

var sqlite3 = require('sqlite3').verbose();
var db = new sqlite3.Database(':memory:');

db.serialize(function() {
  db.run("CREATE TABLE lorem (info TEXT)");

  var stmt = db.prepare("INSERT INTO lorem VALUES (?)");
  for (var i = 0; i < 10; i++) {
    stmt.run("Ipsum " + i);
  }
  stmt.finalize();


  db.each("SELECT rowid AS id, info FROM lorem",
      function(err, row) {
        console.log('in for each loop: ',row.id, row.info);
        records.push({"rowid": row.id, "rowinfo": row.info});
      }, function(err, noOfRows) {
        console.log('completed each, rows:'+noOfRows);
      }
  );
});

console.log('before db close');
db.close();

console.log('hello end');
```

Here is the console output:

"C:\Program Files (x86)\JetBrains\WebStorm 11.0.1\bin\runnerw.exe" "C:\Program Files (x86)\Nodist\bin\node.exe" test.js
hello start
before db close
hello end
in for each loop:  1 Ipsum 0
in for each loop:  2 Ipsum 1
in for each loop:  3 Ipsum 2
in for each loop:  4 Ipsum 3
in for each loop:  5 Ipsum 4
in for each loop:  6 Ipsum 5
in for each loop:  7 Ipsum 6
in for each loop:  8 Ipsum 7
in for each loop:  9 Ipsum 8
in for each loop:  10 Ipsum 9
completed each, rows:10

Process finished with exit code 0

So the problem is that I have "hello end" before my "in for loop" logs which is just incomprehensible. Is the operations running in parallel or is there something wrong with my code? I would appreciate any help on this matter.

**Comment by Suminzhang** [comment]
。。。poor English.. node runs asynchronous.and there is an event quene...I donnot know how to explain.feeling powerless to help.

**Comment by ErisDS** [comment]
The API documentation can be found here: https://github.com/mapbox/node-sqlite3/wiki/API

The problem lies with your code, if you wanted something to execute after calling `db.close()` you would pass a callback:

```
db.close(function () {
 console.log('hello end');
});
```

Most of node works with callbacks that take an error as the first argument, and the response/result of your operation as the second.

**Comment by talkingtab** [comment]
Asynchronous events are like saying to a friend "call me when you get  
back." You have no idea when they will get back AND you are not going to  
wait for them. The code inside db.serialize() is the part about call me  
when you get back. The world doesn't stop while your friend is gone  and  
your program doesn't either. It continues to execute what it can - and  
that is why the "hello end" gets printed.

If you search for "javascript event loop explained" there are some  
articles about this.

It is hard to explain even for native English speakers. :-)

**Comment by Risto-Stevcev** [comment]
This should be documented in the API. The callbacks in the legacy API are optional which implies (to me at least) that leaving them out should make it run synchronously..

**Comment by daniellockyer** [comment]
This is now documented in the Wiki 🙂
