### ISSUE TITLE
Fail to install at the osx

### ISSUE THREAD

**Issue by yoonjechoi** [TryGhost/node-sqlite3#572]
Hi, I try to install with npm. It fails with the messages below.

In the logs, it tried to download the file, node_sqlite3-v2.1.a-node-v46-darwin-x64.tar.gz from the aws but it doesn't exists.  ([sqlite3]: http://node-sqlite3.s3.amazonaws.com/Release/node_sqlite3-v2.1.a-node-v46-darwin-x64.tar.gz not found, falling back to source compile (Error: Server returned 404) )

Is this cause the installation failure?

I use osx 10.10.5 yosemite and osx built-in sqlite3.
Thanks

---

choeyunje-ui-MacBook-Pro:quanx yoonjechoi$ npm install sqlite3
npm WARN package.json quanx@0.0.0 No repository field.
npm WARN package.json quanx@0.0.0 No README data
npm WARN package.json quanx@0.0.0 No license field.
npm WARN engine sqlite3@2.1.19: wanted: {"node":">= 0.6.13 < 0.11.0"} (current: {"node":"4.2.1","npm":"2.14.7"})
npm WARN installMany mkdirp was bundled with sqlite3@2.1.19, but bundled package wasn't found in unpacked tree
npm WARN installMany tar.gz was bundled with sqlite3@2.1.19, but bundled package wasn't found in unpacked tree
npm WARN installMany progress was bundled with sqlite3@2.1.19, but bundled package wasn't found in unpacked tree
|

> sqlite3@2.1.19 install /Users/yoonjechoi/workspace/quanx/node_modules/sqlite3
> node build.js

[sqlite3]: Checking for http://node-sqlite3.s3.amazonaws.com/Release/node_sqlite3-v2.1.a-node-v46-darwin-x64.tar.gz
[sqlite3]: http://node-sqlite3.s3.amazonaws.com/Release/node_sqlite3-v2.1.a-node-v46-darwin-x64.tar.gz not found, falling back to source compile (Error: Server returned 404)
(node) child_process: options.customFds option is deprecated. Use options.stdio instead.
gyp: sqlite3 not found (cwd: /Users/yoonjechoi/workspace/quanx/node_modules/sqlite3) while trying to load sqlite3
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:355:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "sqlite3"
gyp ERR! cwd /Users/yoonjechoi/workspace/quanx/node_modules/sqlite3
gyp ERR! node -v v4.2.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
[sqlite3]: Error: Failed to execute 'node-gyp rebuild sqlite3' (1)
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "sqlite3"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE

npm ERR! sqlite3@2.1.19 install: `node build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sqlite3@2.1.19 install script 'node build.js'.
npm ERR! This is most likely a problem with the sqlite3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls sqlite3
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/yoonjechoi/workspace/quanx/npm-debug.log

**Comment by doamatto** [comment]
If you haven't already, install Xcode's command-line tools (`xcode-select --install`)

If you already have, you could try reinstalling them:
```sh
xcode-select --print-ath

sudo rm -r -f /Library/Developer/CommandLineTools

xcode-select --install
```

**Comment by daniellockyer** [comment]
Would you be able to try with the latest version? There might be prebuilt binaries for your platform, and building should work now 🙂
