### ISSUE TITLE
Open existing SQLite DB In Memory

### ISSUE THREAD

**Issue by zeeshanjan82** [TryGhost/node-sqlite3#574]
Is there a way through which I could open an existing SQLite Db file into memory instead of creating a new one always using the :memory: option. The example in the Readme creates a new SQLite db in memory everytime a new connection is made, however I would like to open an existing SQLite db file in memory.

**Comment by jedateach** [comment]
I'm also wondering if you could write an in-memory Db to disk.

**Comment by jamiesonbecker** [comment]
@jedateach yes, https://www.mail-archive.com/sqlite-users@mailinglists.sqlite.org/msg15905.html

@zeeshanjan82 the previous link shows how to do this by essentially writing it to desk and then reading it into a new memory DB.

This is obviously sub-optimal; if it's already in memory (ie pulled over network), you should be able to open it without hitting the disk.

It's worth investigating a RAM-backed virtual file in your language, like: https://docs.python.org/3/library/tempfile.html#tempfile.SpooledTemporaryFile, but it appears that sqlite doesn't currently have support for opening a database in memory without reading from the disk first.

**Comment by daniellockyer** [comment]
I welcome a PR for this but the issue has been open for 7 years so I'm closing it until there's sufficient demand 🙂
