### ISSUE TITLE
nan header errors when building for Node Webkit v0.8.6

### ISSUE THREAD

**Issue by jpcharlesworth** [TryGhost/node-sqlite3#575]
I have been building sqlite3 for different combinations of versions of Node and Node Webkit

I am running Windows 10 and using Visual Studio Express 2013. In order to get the builds to run I had to work from the developer console of the Visual Studio 2013 Tools

Using Node versions 0.12.9 or 4.2.3, I have been able to build for Node Webkit v0.12.3 with only two warnings and no errors.

However, if I try to build for Node Webkit v0.8.6 using Node versions 0.10.26 or 0.10.41, I always get three compile errors arising from the file nan_implementation_pre_12_inl.h. It appears that successful builds do not use this header, using nan_implementation_12_inl.h instead.

Since my intention is to migrate from Node Webkit v0.8.6 to v0.12.3 this outcome is satisfactory but I thought it worth reporting the problem, for the record. I will also report it as an issue on nodejs/nan.
Detail of the errors is shown in the attached file.
[nan_errors.txt](https://github.com/mapbox/node-sqlite3/files/62425/nan_errors.txt)

**Comment by daniellockyer** [comment]
We no longer use NAN in v5+ so I'm going to close this 🙂
