### ISSUE TITLE
cannot attach second database

### ISSUE THREAD

**Issue by thasmin** [TryGhost/node-sqlite3#578]
Sqlite has a feature where you can attach another database for use as a separate schema. This is useful for joining data in separate files or using a temporary memory db to collate data. It works in the command line but when I try it in node, I get the below error. There's a different error when the file is missing, so it seems to be at least partially working.
Error: SQLITE_CANTOPEN: unable to open database: file:external.db
    at Error (native)

Here is the sqlite doc on the attach command: https://www.sqlite.org/lang_attach.html

**Comment by jorfermo** [comment]
Did you manage to get it working?

I'm stuck in the same place. However I don't get any error even if the attached db doesn't exist.

**Comment by thasmin** [comment]
No, I don't think I did. I'm pretty sure I worked around the problem and did something like combine the two databases so I only needed to open one.

**Comment by besquared** [comment]
+1

**Comment by daniellockyer** [comment]
This seems to work for me as of the current version so I'm going to close this

```js
const sqlite3 = require('./').verbose();
const db = new sqlite3.Database(':memory:');

db.serialize(() => {
    db.run('ATTACH DATABASE \'./second.db\' AS ghost', console.log);
    db.all("PRAGMA database_list", console.log);
});
```

Output:
```
null
null [
  { seq: 0, name: 'main', file: '' },
  {
    seq: 2,
    name: 'ghost',
    file: '/xxx/second.db'
  }
]
```
