### ISSUE TITLE
Building from source fails on FreeBSD 10

### ISSUE THREAD

**Issue by attilagyorffy** [TryGhost/node-sqlite3#584]
I'm trying to install `sqlite3` on a FreeBSD 10 box and am running into issues. First of all as far as I'm concerned (and based on the log output) you currently do not provide pre-built binaries for this platform and the install falls back to trying to build from source. This eventually fails with the following;

```
python: not found
```

I have a standard python2.7 install and have configured `npm` according to the [node-gyp README](https://github.com/nodejs/node-gyp#installation):

```
$ npm config get python
/usr/local/bin/python2.7
```

Now I am not sure what actually happens (and this is merely a guess!) but having seen the `action_before_build` target in the build dependencies I wonder: Could it be that the pre-build step does not respect the npm config variable and tries to invoke the `python` command directly?

See [this](https://github.com/mapbox/node-sqlite3/blob/master/deps/sqlite3.gyp#L58).

Either way, I'm using the following configuration:

```
$ npm config get python
/usr/local/bin/python2.7
$ node --version
v4.2.3
$ npm --version
3.5.2
$ uname -a
FreeBSD vagrant 10.2-RELEASE FreeBSD 10.2-RELEASE #0 r286666: Wed Aug 12 15:26:37 UTC 2015
```

Logs attached here:
[npm-debug.log.zip](https://github.com/mapbox/node-sqlite3/files/76791/npm-debug.log.zip)

Any help would be really appreciated. Thank you.

**Comment by liquid** [comment]
I think I'm right in thinking that the hardcoded interpreter `python` in action in the `action_before_build` target in https://github.com/mapbox/node-sqlite3/blob/master/deps/sqlite3.gyp#L58 is the issue.

Whilst I could get the npm package to manually install, I'd consider the symlink to be a hack and would not consider using this approach during package building for example.

Whilst I'm not familiar with node-gyp, as far as I understand it should be able to use the right python interpreter (see my link to the README above).

**Comment by charlienewey** [comment]
Hi, not sure if you found a solution yet, but two things helped me;

* ensure `gmake` installed
* `CXX="c++" npm install sqlite3 --sqlite=/usr/local/bin # wherever sqlite3 is installed`

**Comment by liquid** [comment]
i've got gmake installed on the system, as well as sqlite3 form packages. However the solution above doesn't seem to work:

```
npm ERR! sqlite3@3.1.1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 126
```

**Comment by charlienewey** [comment]
From [here](https://www.gnu.org/software/bash/manual/html_node/Exit-Status.html), exit status 126 seems to suggest that "the command is found but is not executable". Maybe some permissions need fixing? Check permissions on `node-pre-gyp` executable, perhaps. Good luck!

**Comment by liquid** [comment]
@charlienewey i guess i should bring this up in the node-gyp repo as I don't think I have a `node-pre-gyp` executable. node-gyp is a dependency of sqlite3 and so i'd expect npm to download and execute it during install.

**Comment by lapo-luchini** [comment]
I also worked this around by (temporarily) adding a symlink from `python` to `python2.7` but I agree that this should probably avoid hardcoding the command name and use the global setting as suggested in the node-gyp README.

**Comment by daniellockyer** [comment]
Would you be able to try with v5.0.3? 🙂
