### ISSUE TITLE
Run failed on window 10 iot

### ISSUE THREAD

**Issue by ngminhduong** [TryGhost/node-sqlite3#586]
I try to build webserver on Windown 10 iot with Rasperry pi2 using Nodejs.

And i use sqlite as a database.

I try to import sqlite3 to Nodejs project by using this command:

npm install sqlite3 --build-from-source --target_arch=arm --target_platform=win32
Everything is ok. But when i try to deploy it on Rasperry Pi 2. Server is auto stop working when i try to create database.

var sqlite3 = require('sqlite3').verbose();
var db = new sqlite3.Database(':memory:');

db.serialize(function() {
  db.run("CREATE TABLE lorem (info TEXT)");

  var stmt = db.prepare("INSERT INTO lorem VALUES (?)");
  for (var i = 0; i < 10; i++) {
      stmt.run("Ipsum " + i);
  }
  stmt.finalize();

  db.each("SELECT rowid AS id, info FROM lorem", function(err, row) {
      console.log(row.id + ": " + row.info);
  });
});

db.close();
Error : The program '[2084] backgroundTaskHost.exe' has exited with code 1 (0x1).

**Comment by sidinwillis** [comment]
Same problem for me :(
did you find a solution?

**Comment by ngminhduong** [comment]
Still not found any solution.
Current i use Nosql until this problem solved. :)

**Comment by daniellockyer** [comment]
Would you be able to try with the latest version - v5.0.3? 🙂
