### ISSUE TITLE
npm ERR! sqlite3@3.0.10 install: `node-pre-gyp install --fallback-to-build`

### ISSUE THREAD

**Issue by Troyciv** [TryGhost/node-sqlite3#594]
I tried to install Mapbox Studio Classic and the install failed while trying to install sqlite3. Here are my specs:
- `Ubuntu 15.10`
- `node v4.2.4` installed
- `npm 3.5.2` installed
- `sqlit3@3.0.10` tried to install

Terminal error output is [here](http://pastebin.com/69bxGeKu)

**Comment by pcuinty** [comment]
updated node.js to v4.2.6 and npm to v3.5.3, still fails to install sqlite3.

I tried `npm install` as well as `npm install --build-from-source`

**Comment by daniellockyer** [comment]
Would you be able to try with v5.0.3? 🙂
