### ISSUE TITLE
Unable to install node-sqlite3 on Windows 7

### ISSUE THREAD

**Issue by inventriz** [TryGhost/node-sqlite3#598]
terminal logs of failed install (best from running npm install sqlite3 --loglevel=info): 
[npm-debug.log.txt](https://github.com/mapbox/node-sqlite3/files/124395/npm-debug.log.txt)

node-sqlite3 version: 3.1.1
node version: 1.3.21
OS: Windows 7 64 bit

**Comment by Pomax** [comment]
there was never a 1.3.21 of nodejs, are you using io.js? If so, io.js and node.js merged back into one thing, and the current LTS version of node is 4.3, with the current stable 5.6

**Comment by daniellockyer** [comment]
Would you be able to try with the latest version - v5.0.3? 🙂
