### ISSUE TITLE
How to enable Shared Cache Mode in sqlite3

### ISSUE THREAD

**Issue by suchitpuri** [TryGhost/node-sqlite3#599]
Hi Guys,

We are using sqlite3 as an analytics backend for our service, as a result we have very heavy writes on to the database. Now since sqlite3 has a database level locks. This is preventing us from utilizing the full write throughput of the sqlite3.

On some research i found out that sqlite3 has Shared Cache Support , ref:https://www.sqlite.org/sharedcache.html

This enables us to have more fine grained locking. I am unable to find the support for similar enable_shared_cache option while loading the database in node-sqlite3.

 Can someone please let me know if its possible to enable the shared cache support in node-sqlite3 ?

**Comment by papakai** [comment]
+1

**Comment by SamuelBrucksch** [comment]
Any update on this? I saw PRs that are open for a very long time already and are not beeing looked at, so i do not want to waste my time opening a PR that is not merged anyways...

**Comment by daniellockyer** [comment]
Hey! I'm definitely open to reviewing a PR for this 🙂

**Comment by daniellockyer** [comment]
Upon review, it seems we already support this via the open flags:

> Individual database connections created using [sqlite3_open_v2()](https://www.sqlite.org/c3ref/open.html) can choose to participate or not participate in shared cache mode by using the [SQLITE_OPEN_SHAREDCACHE](https://www.sqlite.org/c3ref/c_open_autoproxy.html) or [SQLITE_OPEN_PRIVATECACHE](https://www.sqlite.org/c3ref/c_open_autoproxy.html) flags the third parameter. The use of either of these flags overrides the global shared cache mode setting established by [sqlite3_enable_shared_cache()](https://www.sqlite.org/c3ref/enable_shared_cache.html). No more than one of the flags should be used; if both SQLITE_OPEN_SHAREDCACHE and SQLITE_OPEN_PRIVATECACHE flags are used in the third argument to [sqlite3_open_v2()](https://www.sqlite.org/c3ref/open.html) then the behavior is undefined.

- https://www.sqlite.org/sharedcache.html#enabling_shared_cache_mode
