### ISSUE TITLE
DLL initialization routine failed

### ISSUE THREAD

**Issue by erikdung** [TryGhost/node-sqlite3#604]
Hi,
I tried to use sqlite3 with Electron. When I run npm install sqlite3, it created in lib/binding/node_v46_win32_ia32 folder with sqlite3.node. When I would like to start Electron App, I got Electron cannot find node_v47_win32_ia32. So I tried to rename node_v46_win32_ia32 to node_v47_win32_ia32. When I tried to start Electron again I got error: 
DLL initialization routine failed. 
Please help

**Comment by daniellockyer** [comment]
Would you be able to try with v5.0.3? 🙂
