### ISSUE TITLE
CentOS 6.7 Error: sqlite3@3.1.1 install: `node-pre-gyp install --fallback-to-build`

### ISSUE THREAD

**Issue by mmetting** [TryGhost/node-sqlite3#611]
Hi sqlite3 team, 
our installation of sqlite3@3.1.1 is failing on CentOS 6.7 - 32bit.
- CentOS 6.7
- 32bit
- node 4.3.2
- npm 3.8.0
- sqlite 3.1.1

We tried the following:
- npm install sqlite3 (as root user)
- npm install sqlite3 (as non-root user or --unsafe-per)
- pre installing node-gyp and node-pre-gyp (locally and globally)
- Build from source (even though we don't need sqlcipher):

```
export LDFLAGS="-L/usr/local/lib"
export CPPFLAGS="-I/usr/local/include -I/usr/local/include/sqlcipher"
export CXXFLAGS="$CPPFLAGS"
npm install sqlite3 --build-from-source --sqlite_libname=sqlcipher --sqlite=/usr/local --verbose

node -e 'require("sqlite3")'
```

Attached, you'll find our debug log:
[npm-debug.txt](https://github.com/mapbox/node-sqlite3/files/164707/npm-debug.txt)

Please help!

**Comment by mmetting** [comment]
Also trying to install as non-root user or --unsafe-per doesn't help.

**Comment by plugn** [comment]
having the same problem.

**Comment by daniellockyer** [comment]
Would you be able to try with the latest version - v5.0.4? 🙂
