### ISSUE TITLE
v3.1.2 fails to build on Travis using iojs-3.3.1

### ISSUE THREAD

**Issue by MrSimonEmms** [TryGhost/node-sqlite3#617]
This is a weird one. When I run the tests using v3.1.2 on iojs-3.3.1 on Travis, it fails to build the `node-pre-gyp`.

I've had to drop back down to v3.1.1 to pass these tests.

Weirdly, it works on every other major version of NodeJS >= 0.10-5.x.x.

Failed example - https://travis-ci.org/riggerthegeek/steeplejack/jobs/118070111
Proof it's v3.1.2. This is exactly the same software, only difference between above test is the version of sqlite3.  https://travis-ci.org/riggerthegeek/steeplejack/jobs/118073491

**Comment by riggerthegeek** [comment]
This is still an issue in v3.1.3 https://travis-ci.org/riggerthegeek/steeplejack/jobs/120268571
