### ISSUE TITLE
DLL initalization routine failed

### ISSUE THREAD

**Issue by barbalex** [TryGhost/node-sqlite3#621]
I am trying to use sqlite3 on electron.

This is similar to https://github.com/mapbox/node-sqlite3/issues/604 but `node_modules\sqlite3\lib\binding\node-v47-win32-x64\node_sqlite3.node` was created.

Also similar to newest comments on https://github.com/mapbox/node-sqlite3/issues/498.

The complete error is:

```
ATOM_SHELL_ASAR.js:157 Uncaught Error: A dynamic link library (DLL) initialization routine failed.
\\?\C:\Users\alex\kapla\node_modules\sqlite3\lib\binding\node-v47-win32-x64\node_sqlite3.node
```

Some information:
- Windows 10 and Mac OsX newest (error occurs on both)
- node 5.9.1
- sqlite3 3.1.2
- using https://github.com/chentsulin/electron-react-boilerplate
- sqlite3 declared external so webpack does not build it (https://github.com/chentsulin/electron-react-boilerplate#externals)

**Comment by barbalex** [comment]
After spending hours I found this solution to work for me: http://verysimple.com/2015/05/30/using-node_sqlite3-with-electron

**Comment by Jarmahent** [comment]
@barbalex I am having issues with this, the link is not working, what fixed it?

Thankyou

**Comment by barbalex** [comment]
I don't remember that.

I wish I did because I can't get native modules to work when using electron with create-react-app.

What definitely works is using electron-react-boilerplate and adding native modules to the second package.json file inside the app folder.

**Comment by Jarmahent** [comment]
@barbalex 

Thats ok I fixed the issue by installing `electron-rebuild` and running:

`node_modules/.bin/electron-rebuild -f -w better-sqlite3`

And it worked like a charm!

**Comment by daniellockyer** [comment]
If this is still a problem, can you please try with v5.0.4? 🙂
