### ISSUE TITLE
error when trying to configure "sqlite3" module on "nw 0.13.0" in combination with the "ref", "ffi" and "ref-struct" module

### ISSUE THREAD

**Issue by RohitSharma27** [TryGhost/node-sqlite3#624]
I am trying to run sqlite3 module on nw 0.13.0 and for that I am using node v5.9.0 to build my native modules. I was successfully able to configure and build "ref", "ffi" and "ref-struct" module (Although they have stated that "The current version is tested to run on node v0.6, v0.8, v0.9 and v0.10" on node-ffi's github page https://github.com/node-ffi/node-ffi. But somehow it all went fine. ) Now, when i am trying to configure node-sqlite3 module, I am getting the following error.
gyp info it worked if it ends with ok gyp info using node-gyp@3.3.1 gyp info using node@5.9.0 | darwin | x64 gyp info spawn /usr/bin/python gyp info spawn args [ '/usr/local/lib/node_modules/node-gyp/gyp/gyp_main.py', gyp info spawn args 'binding.gyp', gyp info spawn args '-f', gyp info spawn args 'make', gyp info spawn args '-I', gyp info spawn args '/Users/rohit/node-webkit-html5-desktop/app-html5-nodeWebkit/versioned_modules/v_0.13.0/node_modules/sqlite3/build/config.gypi', gyp info spawn args '-I', gyp info spawn args '/usr/local/lib/node_modules/node-gyp/addon.gypi', gyp info spawn args '-I', gyp info spawn args '/Users/rohit/.node-gyp/5.9.0/include/node/common.gypi', gyp info spawn args '-Dlibrary=shared_library', gyp info spawn args '-Dvisibility=default', gyp info spawn args '-Dnode_root_dir=/Users/rohit/.node-gyp/5.9.0', gyp info spawn args '-Dnode_gyp_dir=/usr/local/lib/node_modules/node-gyp', gyp info spawn args '-Dnode_lib_file=node.lib', gyp info spawn args '-Dmodule_root_dir=/Users/rohit/node-webkit-html5-desktop/app-html5-nodeWebkit/versioned_modules/v_0.13.0/node_modules/sqlite3', gyp info spawn args '--depth=.', gyp info spawn args '--no-parallel', gyp info spawn args '--generator-output', gyp info spawn args 'build', gyp info spawn args '-Goutput_dir=.' ] gyp: Undefined variable module_name in binding.gyp while trying to load binding.gyp gyp ERR! configure error gyp ERR! stack Error:gypfailed with exit code: 1 gyp ERR! stack at ChildProcess.onCpExit (/usr/local/lib/node_modules/node-gyp/lib/configure.js:305:16) gyp ERR! stack at emitTwo (events.js:100:13) gyp ERR! stack at ChildProcess.emit (events.js:185:7) gyp ERR! stack at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12) gyp ERR! System Darwin 15.2.0 gyp ERR! command "/usr/local/bin/node" "/usr/local/bin/node-gyp" "configure" gyp ERR! cwd /Users/rohit/node-webkit-html5-desktop/app-html5-nodeWebkit/versioned_modules/v_0.13.0/node_modules/sqlite3 gyp ERR! node -v v5.9.0 gyp ERR! node-gyp -v v3.3.1 gyp ERR! not ok

I have used

sudo npm install sqlite3@3.1.0
to install the node module and then after getting inside the sqlite3 folder, I am running

node-gyp configure
This is when i get the above stated error. Is there something wrong with the sqlite3 module or the combination of these 4?

And, even if I use this below command to install sqlite3 module 

> sudo npm install sqlite3@3.1.0 --build-from-source --runtime=node-webkit --target_arch=x64 --target=0.13.0

I get the following error message.

`> ref@1.2.0 install /Users/rohit/node-webkit-html5-desktop/app-html5-nodeWebkit/versioned_modules/v_0.13.0/node_modules/ref

> node-gyp rebuild

gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: 404 response downloading https://nodejs.org/dist/v0.13.0/node-v0.13.0.tar.gz
gyp ERR! stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:244:14)
gyp ERR! stack     at emitOne (events.js:95:20)
gyp ERR! stack     at Request.emit (events.js:182:7)
gyp ERR! stack     at Request.onRequestResponse (/usr/local/lib/node_modules/npm/node_modules/request/request.js:952:10)
gyp ERR! stack     at emitOne (events.js:90:13)
gyp ERR! stack     at ClientRequest.emit (events.js:182:7)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:458:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:103:23)
gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:348:20)
gyp ERR! stack     at emitOne (events.js:90:13)
gyp ERR! System Darwin 15.2.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/rohit/node-webkit-html5-desktop/app-html5-nodeWebkit/versioned_modules/v_0.13.0/node_modules/ref
gyp ERR! node -v v5.9.0
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok 
nw@0.0.1 /Users/rohit/node-webkit-html5-desktop/app-html5-nodeWebkit/versioned_modules/v_0.13.0
├─┬ del@1.2.1
│ └─┬ globby@2.1.0
│   └─┬ glob@5.0.15
│     ├─┬ inflight@1.0.4 
│     │ └── wrappy@1.0.1 
│     ├─┬ minimatch@3.0.0
│     │ └─┬ brace-expansion@1.1.3
│     │   └── concat-map@0.0.1 
│     └── path-is-absolute@1.0.0 
├─┬ mkdirp@0.5.1 
│ └── minimist@0.0.8 
├─┬ request@2.69.0
│ ├── caseless@0.11.0 
│ ├─┬ combined-stream@1.0.5 
│ │ └── delayed-stream@1.0.0 
│ ├── extend@3.0.0 
│ ├── forever-agent@0.6.1 
│ ├─┬ har-validator@2.0.6
│ │ ├─┬ chalk@1.1.3
│ │ │ ├─┬ has-ansi@2.0.0 
│ │ │ │ └── ansi-regex@2.0.0 
│ │ │ └── supports-color@2.0.0 
│ │ ├─┬ commander@2.9.0
│ │ │ └── graceful-readlink@1.0.1 
│ │ └─┬ is-my-json-valid@2.13.1
│ │   ├── generate-function@2.0.0 
│ │   ├─┬ generate-object-property@1.2.0 
│ │   │ └── is-property@1.0.2 
│ │   └── jsonpointer@2.0.0 
│ ├─┬ hawk@3.1.3
│ │ ├── cryptiles@2.0.5 
│ │ └── sntp@1.0.9 
│ ├── isstream@0.1.2 
│ └── json-stringify-safe@5.0.1 
├── sqlite3@3.1.0  extraneous
└─┬ unzip@0.1.11
  ├─┬ fstream@0.1.31 
  │ ├── graceful-fs@3.0.8 
  │ └── inherits@2.0.1 
  ├─┬ match-stream@0.0.2
  │ └─┬ readable-stream@1.0.33 
  │   └── isarray@0.0.1 
  ├─┬ pullstream@0.4.1
  │ ├─┬ readable-stream@1.0.33 
  │ │ └── isarray@0.0.1 
  │ └─┬ slice-stream@1.0.0
  │   └─┬ readable-stream@1.0.33 
  │     └── isarray@0.0.1 
  └─┬ readable-stream@1.0.33 
    ├── isarray@0.0.1 
    └── string_decoder@0.10.31 

npm WARN nw@0.0.1 No description
npm WARN nw@0.0.1 No repository field.
npm WARN nw@0.0.1 No license field.
npm ERR! Darwin 15.2.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "sqlite3@3.1.0" "--build-from-source" "--runtime=node-webkit" "--target_arch=x64" "--target=0.13.0"
npm ERR! node v5.9.0
npm ERR! npm  v3.7.3
npm ERR! code ELIFECYCLE

npm ERR! ref@1.2.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ref@1.2.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ref package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ref
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ref
npm ERR! There is likely additional logging output above.`

Please help.
Thanks.

**Comment by daniellockyer** [comment]
Please try with a newer version and let me know if you're still experiencing issues  🙂
