### ISSUE TITLE
Performing IN query using ?

### ISSUE THREAD

**Issue by BlakeLucchesi** [TryGhost/node-sqlite3#628]
I know the ? character is used as a means to replace values used in queries. But I'm wondering how this works with performing an IN query. For example, I tried to pass an array of values hoping that the query parser would do a join on the values and make `['item1', 'item2']` become: `"item1", "item2"`. 

``` SQL
var statuses = ['active', 'inactive'];

this.db.all('SELECT * FROM members WHERE status IN (?) ORDER BY search_name ASC LIMIT 200', [statuses], (err, rows) => {
   // access rows here.
});
```

However, it doesn't appear to parse the array of values correctly.  Thus for the time being I am just avoiding the SQL injection protection because its not a concern for me in this specific case, but I was curious if 

```
var statuses = "'active', 'inactive'";
this.db.all(`SELECT * FROM members WHERE status IN (${statuses}) ORDER BY search_name ASC LIMIT 200`, (err, rows) => {
   // access rows here.
});
```

The example is a bit contrived because i setup the statuses value here inline, but in my code I'm trying to get these values from input fields and passing them around so would prefer to handle them as an array as I pass them into the function to perform the query.

Thanks!

**Comment by nistala** [comment]
+1, need "IN" support

**Comment by amellnik** [comment]
Duplicate of #527, one workaround is discussed there.

**Comment by Houfeng** [comment]
+1，need "IN" supoort

**Comment by cjn566** [comment]
+1, need "IN" support

**Comment by Kycermann** [comment]
+1 please

**Comment by daniellockyer** [comment]
Closing as duplicate of https://github.com/TryGhost/node-sqlite3/issues/762
