### ISSUE TITLE
Installi sqlite3 (windows): node-pre-gyp install --fallback-to-build

### ISSUE THREAD

**Issue by Orionsg** [TryGhost/node-sqlite3#637]
[npm-sqlite3-inst-info.txt](https://github.com/mapbox/node-sqlite3/files/242967/npm-sqlite3-inst-info.txt)
[npm-sqlite3-inst-info.txt](https://github.com/mapbox/node-sqlite3/files/242969/npm-sqlite3-inst-info.txt)

I just installed node.js a couple of days ago under Windows 7 (32 bit) with the MSI and have the versions:
node -v : v4.4.3
npm -v : 2.15.1

When I try to install sqlite3: "npm install sqlite3 -save", I get:

> sqlite3@3.1.3 install C:\Users\Frank\AppData\Roaming\npm\node_modules\sqlite3
> node-pre-gyp install --fallback-to-build

The command then hangs with no more information. After a long time, I then can use Ctrl-C to break the process (I see no CPU activity for the process): 
^CTerminate batch job (Y/N)? y

Now, when I check the ...npm\node_modules folder there an sqlite3 folder created with sub folders and content.

As mentioned, this is a new node.js installation and this is the first npm package installed.

I have attached the output of installing with the command:
npm install sqlite3 --loglevel=info

**Comment by kxjhcs** [comment]
try 'npm install sqlite3 source'

**Comment by conor909** [comment]
I tried `npm install sqlite3 source` but got the error I'm getting on any other intsall

node v4.2.4
npm v1.4.3

`Failed at the sqlite3@3.1.3 install script`

**Comment by shellberg** [comment]
What level of Visual Studio compiler do you have installed?

**Comment by bingxueyizhou** [comment]
I have same question with using `npm install sqlite3 --save`.
I do as follow: 
download:
[Visual Studio Build tools](http://landinghub.visualstudio.com/visual-cpp-build-tools)
[Python 2.7](https://www.python.org/ftp/python/2.7/python-2.7.amd64.msi)
installed:
`npm install node-gyp -g`[node-gyp](https://www.npmjs.com/package/node-gyp)

Use `npm install sqlite3 --build-from-source --save`

But I'm failed.
[npm-debug.txt](https://github.com/mapbox/node-sqlite3/files/664326/npm-debug.txt)

**Comment by bingxueyizhou** [comment]
I solve my problem.

**Comment by OfekA** [comment]
> the error:MSBUILD : error MSB4132: 无法识别工具版本“2.0”。可用的工具版本为 "14.0", "4.0"。
run npm config set msvs_version 2015.

worked! thanks

**Comment by kands-code** [comment]
I meet the same problem, is there any way to solve it?

┌─[kands@kands-MicroPC] - [~] - [二 7月 07, 00:59]
└─[$] <> sudo npm i -g sql-language-server
[sudo] kands 的密码： 
/usr/local/bin/sql-language-server -> /usr/local/lib/node_modules/sql-language-server/dist/cli.js

> sqlite3@4.2.0 install /usr/local/lib/node_modules/sql-language-server/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp WARN Pre-built binaries not installable for sqlite3@4.2.0 and node@10.19.0 (node-v64 ABI, glibc) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Hit error EACCES: permission denied, mkdir '/usr/local/lib/node_modules/sql-language-server/node_modules/sqlite3/lib/binding' 
gyp WARN EACCES current user ("nobody") does not have permission to access the dev dir "/root/.cache/node-gyp/10.19.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/sql-language-server/node_modules/sqlite3/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/sql-language-server/node_modules/sqlite3/.node-gyp'
gyp ERR! System Linux 5.4.0-40-generic
gyp ERR! command "/usr/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/usr/local/lib/node_modules/sql-language-server/node_modules/sqlite3/lib/binding/node-v64-linux-x64/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/usr/local/lib/node_modules/sql-language-server/node_modules/sqlite3/lib/binding/node-v64-linux-x64" "--napi_version=5" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v64"
gyp ERR! cwd /usr/local/lib/node_modules/sql-language-server/node_modules/sqlite3
gyp ERR! node -v v10.19.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/usr/local/lib/node_modules/sql-language-server/node_modules/sqlite3/lib/binding/node-v64-linux-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/usr/local/lib/node_modules/sql-language-server/node_modules/sqlite3/lib/binding/node-v64-linux-x64 --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/sql-language-server/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:982:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
node-pre-gyp ERR! System Linux 5.4.0-40-generic
node-pre-gyp ERR! command "/usr/bin/node" "/usr/local/lib/node_modules/sql-language-server/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/local/lib/node_modules/sql-language-server/node_modules/sqlite3
node-pre-gyp ERR! node -v v10.19.0
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok 
Failed to execute '/usr/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/usr/local/lib/node_modules/sql-language-server/node_modules/sqlite3/lib/binding/node-v64-linux-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/usr/local/lib/node_modules/sql-language-server/node_modules/sqlite3/lib/binding/node-v64-linux-x64 --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)
npm WARN jsdom@16.2.2 requires a peer of canvas@^2.5.0 but none is installed. You must install peer dependencies yourself.
npm WARN ws@7.3.1 requires a peer of bufferutil@^4.0.1 but none is installed. You must install peer dependencies yourself.
npm WARN ws@7.3.1 requires a peer of utf-8-validate@^5.0.2 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/sql-language-server/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sqlite3@4.2.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sqlite3@4.2.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-07-06T17_00_09_122Z-debug.log
┌─[kands@kands-MicroPC] - [~] - [二 7月 07, 01:00]
└─[$] <>

**Comment by kands-code** [comment]
I've solved this problem by adding an option '--unsafe-perm', hope it is also useful to you.

**Comment by StianOvrevage** [comment]
`npm install sqlite3 --build-from-source --save` does not work
`npm install sqlite3 --unsafe-perm --save` does not work
`npm config set msvs_version 2015 && npm install sqlite3 --save` does not work

This breaks the Apollo tutorial at https://www.apollographql.com/docs/apollo-server/getting-started/ on WSL

**Comment by StianOvrevage** [comment]
This may work:

In PowerShell:
```
wsl --list --verbose
wsl --set-version Ubuntu-20.04 2
```

In WSL2:
```
sudo apt-get install python
npm install sqlite
```

**Comment by daniellockyer** [comment]
Would you be able to try with v5.0.3? 🙂
