### ISSUE TITLE
Possible memory leak in sqlite3MemMalloc (node-v11-linux-arm, maybe others)

### ISSUE THREAD

**Issue by cblair** [TryGhost/node-sqlite3#641]
While valgrinding our app, we found a possible leak:

```
==16916== 69,504 bytes in 53 blocks are possibly lost in loss record 117 of 120
==16916==    at 0x480D014: malloc (vg_replace_malloc.c:291)
==16916==    by 0x4F52843: sqlite3MemMalloc (in .../node_modules/sqlite3/lib/binding/node-v11-linux-arm/node_sqlite3.node)
```

Thoughts? Actual leak here? I'll be characterizing this a little more.

**Comment by cblair** [comment]
I'm trying to figure out how sqlite3MemMalloc gets pulled in... not source in this repo.

**Comment by springmeyer** [comment]
Can you provide a reduced testcase to replicate?

**Comment by cblair** [comment]
Yeah, let me mod an existing test and get a little more specific. I found out it's a one time leak, so I don't think it's a big issue at all. Just would be a code clean thing.

**Comment by daniellockyer** [comment]
Closing as the issue is stale but welcome any memory issues in the future 🙂
