### ISSUE TITLE
serialize error propagation

### ISSUE THREAD

**Issue by benjaminhon** [TryGhost/node-sqlite3#642]
Hi may i ask about error propagation in serialize?

```
db.serialize ->
        db.run "BEGIN"
        db.run [statement 1]
        db.run [statement 2]
        db.run [statement 3]        
        db.run "END", (err) ->
          if err? then reject err else resolve()
```

what happens when statement 1 has an error? does the last "END" statement gets run? and the final error callback executed?

i need to make a transaction and have to ensure the the final END is called. 

Thanks!

**Comment by kroggen** [comment]
If you don't pass a callback function to each statement then it will throw an exception in the first error and it will not continue to the next statements.

If you pass a callback, then it will be called and the next statements will be executed.
