### ISSUE TITLE
Where schema verification

### ISSUE THREAD

**Issue by jaumard** [TryGhost/node-sqlite3#644]
Is there any way to tell sequelize to check schema and try parsing field to the correct type ? 
Currently I'm trying this :

My model : 

```
var Model = sequelize.define('model', {
  isComplete: Sequelize.BOOLEAN
})
```

Then calling : 
`Model.destroy({where: {isComplete: 'true'}})`

But non was destroy because SQL look like : `DELETE FROM`model`WHERE`isComplete`= 'true'` is there any option to tell sequelize to parse my field into the correct type ? 

If there nothing to do this is the team interested in such feature ?

**Comment by kroggen** [comment]
Why don't you try `Model.destroy({where: {isComplete: true}})` or `Model.destroy({where: {isComplete: 1}})` ?

**Comment by jaumard** [comment]
@kroggen it will work like you said but field come from url like `http://localhost:3000/model/3?isComplete=true` so in my controllers I receive `isComplete='true'`. 
I can't parse it myself into boolean because it's under a library that can be use by anyone so I don't know if isComplete have to be a boolean, number, string... Sequelize already have the schema so technically it can check field type and try to parse it.

If sequelize don't have such a feature, I will have to develop it myself :/
