### ISSUE TITLE
Cached database doesn't take the mode into account

### ISSUE THREAD

**Issue by nnashok** [TryGhost/node-sqlite3#645]
The cached database only uses the filename in its check. Checking the mode also would enable an application to cache separate Database objects for `read` and `write` access. In my application, I open the database first for checking the data has been ingested and if not, continue to write to the database. As a result I cant use the cached instance (which would be the one with `read` mode). If the API supported accounting for the mode, then the code could benefit from opening the database in its required mode without concerning if it was opened in any other mode by the other parts of the code, a cached instance will always be used when available.

I'd be happy to work on a patch.

**Comment by daniellockyer** [comment]
Closing for now but would accept a PR 🙂
