### ISSUE TITLE
Unable to configure/build Sqlite3-3.1.4 with node 4.4.4

### ISSUE THREAD

**Issue by addankisatish** [TryGhost/node-sqlite3#656]
node-gyp confiure fails with below error:

gyp: Undefined variable module_name in binding.gyp while trying to load binding.gyp

Any solution ?

**Comment by YanjunLee** [comment]
node-pre-gyp

**Comment by xbolshe** [comment]
Use node-gyp confiure with --module-name.

BR,
xbolshe

**Comment by daniellockyer** [comment]
Would you be able to try with v5.0.3? 🙂
