### ISSUE TITLE
sqlite binary for openshift linux server - node-v47-linux-x64/node_sqlite3.node

### ISSUE THREAD

**Issue by barneydunning** [TryGhost/node-sqlite3#657]
Could someone please help... I'm not getting this!

I have an OpenShift server, and I am FTP'ing my node project over to the server (rather than using git and pushing) - now I know that this is not the desired approach... but its worked for me and keeps things simple.

The problem is sqlite.  I have v3.1.4 installed on my development machine (Windows 10) and all works fine.  When I copy the node_modules folder over to the OpenShift server (which I believe is Linux)... the node project fails to start.

It complains that it cannot find "binding/node-v47-linux-x64/node_sqlite3.node".  Now, this folder does not exist... so I've read a bit and it seems that I need to build the node sqlite3 from the source code.

Can someone help me through this process as I can't seem to get it to work.  I am using the following command, and it results in the subsequent error.

Any help on this would be greatly appreciated - thanks.

npm install --build-from-source=sqlite3 --target_arch=x64 --target_platform=linux

Command:
C:\temp\barnes>npm install --build-from-source=sqlite3 --target_arch=x64 --target_platform=linux

Output:

> sqlite3@3.1.4 install C:\temp
> node-pre-gyp install --fallback-to-build

C:\temp>if not defined npm_config_node_gyp (node "C:\Users\barnaby.dunning\AppData\Roaming\nvm\v5.9.1\node_modules\npm\bin\node-gyp-bin\....\node_modules\node-gyp\bin\node-gyp.js" clean )  else (node "" clean )

C:\temp>if not defined npm_config_node_gyp (node "C:\Users\barnaby.dunning\AppData\Roaming\nvm\v5.9.1\node_modules\npm\bin\node-gyp-bin\....\node_modules\node-gyp\bin\node-gyp.js" configure --fallback-to-build --module=C:\temp\lib\binding\node-v47-linux-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=C:\temp\lib\binding\node-v47-linux-x64 )  else (node "" configure --fallback-to-build --module=C:\temp\lib\binding\node-v47-linux-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=C:\temp\lib\binding\node-v47-linux-x64 )
C:\Users\barnaby.dunning\AppData\Roaming\nvm\v5.9.1\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\input.py:888: Warning: 'as' will become a reserved keyword in Python 2.6
Traceback (most recent call last):
  File "C:\Users\barnaby.dunning\AppData\Roaming\nvm\v5.9.1\node_modules\npm\node_modules\node-gyp\gyp\gyp_main.py", line 13, in <module>
    import gyp
  File "C:\Users\barnaby.dunning\AppData\Roaming\nvm\v5.9.1\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp__init__.py", line 8, in <module>
    import gyp.input
  File "C:\Users\barnaby.dunning\AppData\Roaming\nvm\v5.9.1\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\input.py", line 888
    except ImportError as e:
                        ^
SyntaxError: invalid syntax
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\barnaby.dunning\AppData\Roaming\nvm\v5.9.1\node_modules\npm\node_modules\node-gyp\lib\configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\Program Files\nodejs\node.exe" "C:\Users\barnaby.dunning\AppData\Roaming\nvm\v5.9.1\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" "configure" "--fallback-to-build" "--module=C:\temp\lib\binding\node-v47-linux-x64\node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=C:\temp\lib\binding\node-v47-linux-x64"
gyp ERR! cwd C:\temp
gyp ERR! node -v v5.9.1
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd configure --fallback-to-build --module=C:\temp\lib\binding\node-v47-linux-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=C:\temp\lib\binding\node-v47-linux-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\temp\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:100:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:850:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
node-pre-gyp ERR! System Windows_NT 10.0.10586
node-pre-gyp ERR! command "C:\Program Files\nodejs\node.exe" "C:\temp\node_modules\node-pre-gyp\bin\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\temp
node-pre-gyp ERR! node -v v5.9.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.28
node-pre-gyp ERR! not ok

**Comment by daniellockyer** [comment]
Please try with the latest version - v5.0.3 🙂
