### ISSUE TITLE
Sqlite3 build on raspberry pi B (latest Raspbian Jessie Lite)

### ISSUE THREAD

**Issue by ssbaksa** [TryGhost/node-sqlite3#664]
Hi,
I get this on all Node JS builds.

gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Linux 4.4.11+
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/node-sqlite3
gyp ERR! node -v v5.11.1
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
npm ERR! Linux 4.4.11+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "-g" "install" "node-sqlite3"
npm ERR! node v5.11.1
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE

npm ERR! node-sqlite3@0.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sqlite3@0.0.3 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-sqlite3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-sqlite3
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-sqlite3
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/npm-debug.log

[npm-debug.log.txt](https://github.com/mapbox/node-sqlite3/files/316914/npm-debug.log.txt)

[npm-debug1.log.txt](https://github.com/mapbox/node-sqlite3/files/316916/npm-debug1.log.txt)

**Comment by OperKH** [comment]
Have the same problem on Raspberry pi B (armv6l) Raspbian Wheezy
node v6.4.0
node-pre-gyp v0.6.28
npm  v3.10.3
sqlite3 v3.1.4

**Comment by OperKH** [comment]
After I did update from Wheezy to Jessie it start compile without errors, I found in issues that to compile need to have g++ and gcc versions 4.9+.

**Comment by ssbaksa** [comment]
Tnx for your info.
