### ISSUE TITLE
Embedding node_sqlite3 in nodejs

### ISSUE THREAD

**Issue by dmadan86** [TryGhost/node-sqlite3#666]
Hi,

I went through this document https://github.com/mapbox/node-sqlite3/wiki/Building-for-Android, I found that this works for 0.10.x node version, but how can I achieve the same in v4.x node version.

Regards,
Madan

**Comment by michael-ts** [comment]
@dmadan86 Did you get it to work with SQLCipher support?

**Comment by dmadan86** [comment]
I have to use this approach in an embedded project not in an android. So, was using this step for android  in 0.10.x node version, but now i have to move to latest node version these step won't work.

**Comment by Mithgol** [comment]
Have you tried [JXcore](https://github.com/jxcore/jxcore)? It should have integrated node-sqlite3 and should be able to run on Android, if I remember correctly.

**Comment by daniellockyer** [comment]
Closing as issue is stale, but if it's still a problem, please try with v5.0.4 🙂
