### ISSUE TITLE
Error: SQLITE_ERROR: near "AUTO_INCREMENT": syntax error

### ISSUE THREAD

**Issue by Jovonni** [TryGhost/node-sqlite3#682]
id INTEGER NOT NULL AUTO_INCREMENT, 

Does not work like standard SQL

How has anyone else setup a primary key with auto increment?

This is what I did,

CREATE TABLE sample (id INTEGER NOT NULL AUTO_INCREMENT, column2 TEXT, PRIMARY KEY('id'))

with auto increment, works just fine.

Thoughts?

**Comment by leeching** [comment]
Please try `CREATE TABLE sample (id INTEGER PRIMARY KEY AUTOINCREMENT, column2 TEXT)`.
