### ISSUE TITLE
Module node_sqlite3.node not found in node-v47-linux-x64 but npm installs v46

### ISSUE THREAD

**Issue by woubuc** [TryGhost/node-sqlite3#687]
I'm trying to use the sqlite3 module, and in the past it has worked fine, but recently when I try to start my app it throws an error:

```
Error: Cannot find module '/app/node_modules/sqlite3/lib/binding/node-v47-linux-x64/node_sqlite3.node'
```

I've checked `/lib/binding/` and there's a directory `node-v46-linux-x64` but not a `v47` one. I've tried both the regular install and `--build-from-source` but both give me the `v46` directory, and the module itself keeps looking for `v47`.

Is this a bug, or am I installing the module wrong? I've tried removing the module and re-installing it multiple times, but no changes. The install itself works just fine, but then when I start my Node app the error appears and the app crashes. Please help me or advise how to fix this error.

I'm using version `3.1.4` of node-sqlite, running on node `4.4.7` (currently the latest LTS release).

**Comment by hxfdarling** [comment]
You can try 'nw-gyp' module tu build node-sqlite3 sources.I build sucess

**Comment by jaypozo** [comment]
I'm having this same problem, problem also exists at version `3.1.3`

**Comment by spaceguy101** [comment]
I'm facing this same issue on `3.1.4` . Any solutions?

**Comment by jorditost** [comment]
Same problem here with node `5.7.1` and npm `3.6.0`. Thanks for any advice!

**Comment by jorditost** [comment]
Ok, I could fix it. Try just to remove the package inside the `node_modules` folder (or remove the entire folder) and then execute `npm install` in the Terminal in the main project folder.

**Comment by Thavaprakash** [comment]
I'm getting same error, even after i removed and reinstalled npm packages. Please help me to get rid of this issue.

I'm using following versions.
node version: v8.7.0
npm version: 5.4.2

**Comment by daniellockyer** [comment]
Would you be able to try with v5.0.3? 🙂
