### ISSUE TITLE
Since weeks in trouble with sqlite...Uncaught Error: Cannot find module 

### ISSUE THREAD

**Issue by Steviey** [TryGhost/node-sqlite3#707]
module.js:442 Uncaught Error: Cannot find module 'C:\MyPorn\HTML5\MyApp\node_modules\sqlite3\lib\binding\electron-v1.3-win32-x64\node_sqlite3.node'

**Comment by jmihelcic** [comment]
Same here.
Ps. love the path name

**Comment by Py-Tek** [comment]
Same issue here on Linux. The only difference is that the path is linux instead of win32

**Comment by bengotow** [comment]
Hey folks - `node-sqlite3` contains native C++ code that needs to be compiled against the correct V8 headers for your version of NodeJS. Most likely if you look in that `lib/binding` folder, you'll see that there's a folder there but it's named differently. (Eg not `electron-v1.3-win32-x64`).

You need to use something like https://github.com/electron/electron-rebuild to compile the sqlite3 module against the version of Node inside your version of Electron.

**Comment by Steviey** [comment]
I finally manged it by an amount of tweaking s, which is unacceptable. For all brothers and sisters, from my dev-log:


----------------------------------------------------------------------- Still no Sqlite3 [SOLVED] Start
Keyword: Sqlite3 Bug Fix

Vorbemerkung:
Das war das längste Hint-Hunting aller Zeiten (bis ca. 1 Woche)
Die Situation um node-gyp, den tools electron-rebuild etc. ist katastrophal was die maintainance anbelangt.
Die Dependency-Geschichten im HTML/JS-Kontext sind noch viel schlimmer und komplexer als bei C#.
Electron-rebuild kahm bei dieser Lösung nicht mehr zum Einsatz (nur node-gyp rebuild)
Native Extensions brauchen für Electron immer ein rebuild.

Mögliche Lösungsgründe/wichtige Vorarbeiten zur erfolgreichen Implementierung von Sqlite3 (important preperations)

1. Die PC-Environmentvariablen nüssen auf VS 2015 getrimmt sein (siehe oben Bugfix für electron-rebuild)
2. Node x64 braucht Python x64 und nicht x32
2.1 Node- und Python-Version überprüfen: 
  - $ node und dann im process-explorer unter Einblendung der Spalte für Bit-Version
  - $ python und dann im process-explorer unter Einblendung der Spalte für Bit-Version
3. I have Python 2.7 + PATH + Build Tools + C++ Build Tools + PATH on board.
4. Zum Auschluss von Sqlite3 vom Parsen durch Webpack: build > webpack.base.conf: 
	externals: {
	'sqlite3':'commonjs sqlite3',
	},
  
Vorgehen:
  
------start fix
1. npm install sqlite3 --save-dev

2. cd node_modules/sqlite3 && node-gyp rebuild --target=1.4.3 --arch=x64 --target_platform=win32 --runtime=electron --module_name=node_sqlite3 --module_path=../lib/binding/node-v46-win32-x64

3. Verzeichnis Umbennen (rename directory):

C:\b\node_modules\sqlite3\lib\binding\electron-v1.4-win32-x64 

4. Pfad-Verweis gleichlautend ändern in (change path in config.gypi):

C:\b\node_modules\sqlite3\build\config.gypi
----------End Fix
Fazit:

Die letzten auschlaggebenden Hinweise/Hints waren:

A) Das die 32bit-Version von Python nicht zu Node x64 passt
B) Dass man das falsche angelegte Verzeichnis "node-v46-win32-x64" einfach umbennen kann und in config.gypi umschreiben kann.
...https://github.com/electron/electron-rebuild/issues/33
...Beitrag von BafS
C) Es wurde auf folgende Schritte beim rebuild verzichtet (I did not use)
- npm run prepublish
- node-gyp configure

**Comment by daniellockyer** [comment]
Can you try with v5.0.3 please? 🙂

**Comment by Steviey** [comment]
> Can you try with v5.0.3 please? slightly_smiling_face

I don't code such stuff anymore. The whole stack is way to complicated and has way too much dependencies, without quality-control. It's a waste of time.
