### ISSUE TITLE
expose sqlite3_step() interface (new stm API)

### ISSUE THREAD

**Issue by gbrault** [TryGhost/node-sqlite3#737]
It can be convenient to do
- stm =prepare (Select * from table)
**** execute some code which is not in sequence ****
- stm.step() -> would call sqlite3_step()
**** execute some code which is not in sequence ****
- stm.get()
**** execute some code which is not in sequence ****

typically what we have from a client and a server

so a stm.step() is needed.

I didn't figure out how to use it or is it missing?

**Comment by daniellockyer** [comment]
Closing for now as this issue is 6 years old and the demand isn't there right now 🙂
