### ISSUE TITLE
node-pre-gyp is installed with npm 2.15.9

### ISSUE THREAD

**Issue by danderson00** [TryGhost/node-sqlite3#738]
For some reason, node-pre-gyp is installed without flattening the node_modules folder. This is causing issues on windows machines.

I believe this is because there is a field in the npm repo that specifies the npm version to 2.15.9. Try running `npm view sqlite3@3.1.8 _npmVersion`, or go to https://registry.npmjs.org/sqlite3 and look towards the end of the file at the _npmVersion property.

**Comment by Alan01252** [comment]
Hi @danderson00 

Do you have workaround for this? 

I'm having to overwrite the node-gyp from a version that did not flatten the node_modules folder, which isn't very elegant..

**Comment by danderson00** [comment]
Never did find a workaround. Can you refresh my memory on the actual consequences of this issue? We can bring this up with mapbox (sqlite3 repo owners) if need be.

**Comment by Alan01252** [comment]
I was/am hitting the 250 character limit in windows. 

I've worked around it by making node-gyp a dependency of the main project then running npm dedupe

Seems to be working okay.

**Comment by danderson00** [comment]
I just realized this issue is already in the mapbox repo :) I thought it was in a different repo. This should be a fairly simple fix, but not sure who to ping.

**Comment by daniellockyer** [comment]
Would you be able to try with v5.0.3? 🙂

**Comment by danderson00** [comment]
It's been a couple of years since using Windows (Ubuntu FTW). TBH, I can't
even remember the issue! Sorry!
