### ISSUE TITLE
Are callback methods serialized in respect of SQL queries methods?

### ISSUE THREAD

**Issue by Brank** [TryGhost/node-sqlite3#744]
Hello,
I am having huge issues with transactional queries I want to ask if the callback functions are serialized in respect of the queries methods. Maybe Ill explain better with an example:

```
function test()
{
    db.run("BEGIN;", function(err){
           console.log("Ill start begin");
     });
    db.run("SELECT * FROM tableExample",function(err,row){
            console.log("I am A");
    });
    db.run("COMMIT;", function(err){
            console.log("I am B");
     });
}
```

What would be the output? I am asking this because I am having problems with transactional queries, when I am having an error and try to rollback it throws "SQLITE_ERROR: cannot rollback - no transaction is active" and I am thinking that the last commit is executing before my callback method in this case of the SELECT query.

Regards and thanks in advance,

**Comment by kroggen** [comment]
You must put the next command in the callback of the previous.

Or use `db.serialize()`

**Comment by Brank** [comment]
Hello, thanks for your answer thats actually what I am doing but sometimes I cannot put the command inside the callback of the previous and cannot use db.serialize as well because I sometimes use loops for do an specific command.
