### ISSUE TITLE
failure trying to compile for arm+android

### ISSUE THREAD

**Issue by bibitiger** [TryGhost/node-sqlite3#746]
my os platform: Darwin fanxudeMacBook-Pro.local 15.5.0 Darwin Kernel Version 15.5.0: Tue Apr 19 18:36:36 PDT 2016; root:xnu-3248.50.21~8/RELEASE_X86_64 x86_64

env set like:

> export TOOLCHAIN=/Users/fanxu/Downloads/node-sqlite3-master/android-toolchain
mkdir -p /Users/fanxu/Downloads/node-sqlite3-master/android-toolchain
/Users/fanxu/workSoft/forAndroid/android-ndk-r12b/build/tools/make-standalone-toolchain.sh \
    --toolchain=arm-linux-androideabi-4.9 \
    --arch=arm \
    --install-dir=/Users/fanxu/Downloads/node-sqlite3-master/android-toolchain \
    --platform=android-21
    
export PATH=/Users/fanxu/Downloads/node-sqlite3-master/android-toolchain/bin:$PATH
export AR=/Users/fanxu/Downloads/node-sqlite3-master/android-toolchain/bin/arm-linux-androideabi-ar
export CC=/Users/fanxu/Downloads/node-sqlite3-master/android-toolchain/bin/arm-linux-androideabi-gcc
export CXX=/Users/fanxu/Downloads/node-sqlite3-master/android-toolchain/bin/arm-linux-androideabi-g++
export LINK=/Users/fanxu/Downloads/node-sqlite3-master/android-toolchain/bin/arm-linux-androideabi-g++

build with cmd:

> npm install --build-from-source --target_arch=arm --target_platform=android

and the error is:

>   ACTION deps_sqlite3_gyp_action_before_build_target_unpack_sqlite_dep Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c
  TOUCH Release/obj.target/deps/action_before_build.stamp
  CC(target) Release/obj.target/sqlite3/gen/sqlite-autoconf-3150000/sqlite3.o
arm-linux-androideabi-gcc: error: x86_64: No such file or directory
arm-linux-androideabi-gcc: error: unrecognized command line option '-mmacosx-version-min=10.5'
arm-linux-androideabi-gcc: error: unrecognized command line option '-arch'
make: *** [Release/obj.target/sqlite3/gen/sqlite-autoconf-3150000/sqlite3.o] Error 1

**Comment by daniellockyer** [comment]
Would you be able to try with v5.0.3? 🙂
