### ISSUE TITLE
Is there a way to return plain object for db.each and db.all?

### ISSUE THREAD

**Issue by xsq007** [TryGhost/node-sqlite3#754]
Now for db.all method, result array element is a special type, instead of plain object (i.e. object literal).

`db.all(sql, (err,  rows) => { }) `

I'd like common object literal because of following scenario. 
I load about 20,000 records from database and then 
do some checks for each record,  like finding some keys ( `obj[key]` ) and other calculation.

It takes more than 10s to do checks for all records, but if I transform those records into plain objects,
then it only takes about 60ms to do checks.  Much faster. The only difference is array element type.

I used Object.assign method to transform records into plain object. 

`records = records.map(record => Object.assign({}, record))`

But the transformation is very slow, which took about 17s.

Wondering if there is a way to get plain objects directly from db.all and db.each?

**Comment by kroggen** [comment]
SQL exists exactly to avoid iteration on all the records in our code. This must be done by the SQL engine.

So I suggest to use some filtering in the WHERE clause and return only those records that fit the search.
