### ISSUE TITLE
Concurrent transactions with the sqlite mutexes?

### ISSUE THREAD

**Issue by YugoAmaryl** [TryGhost/node-sqlite3#760]
I'm writing a server for a collaborative todo list. My server has to answer multiple clients through a publish/subscribe service.

For example, here is the code that updates the text of a todo entry :

```
db.run("BEGIN;");
var version = undefined;
try
{
    db.get("SELECT version FROM todos WHERE id = ?", [msg.id], function (err, row)
    {
        if (err) throw err;
        console.log("version : " + row.version);
        version = row.version + 1;

        db.run("UPDATE todos SET title = ?, version = ? WHERE id = ?", [msg.title, version, msg.id], function(err){
            if (err) throw err;
            db.run("COMMIT;");
            publish("broadcast", {cmd: "edit", todo: {id: msg.id, title: msg.title, version: version}});
        });
    });   
}
catch (err)
{
    db.run("ROLLBACK;");
    console.log(err);
    publish(msg.sender, {err: err, request: msg});
} 
```

The issue is this : 
whenever a thread is updating a todo, a second update request can arrive and trigger the start of a new transaction, which results in an error : "cannot start a transaction from within a transaction".

It seems the easiest way to solve this would be to acquire a mutex before starting a transaction.
I didn't find a simple, convincing, way of using mutexes with node, and I'm wondering whether it would be possible to extend the node API to wrap the sqlite3_mutex_enter() and related functions?

**Comment by kroggen** [comment]
First, I guess node.js use a single thread for this code, the main thread. The worker threads will run the SQL commands, wait for completion and then signal the main thread.

While the worker thread is waiting for a completion a new request can arrive and then it will be processed  in the main thread, that will call `db.run("BEGIN")` again. This causes the error.

I am wondering here whether using synchronous calls would not solve this, because this whole block would be executed and onlu


I am wondering here whether using synchronous calls would not make the code behave almost the same way as using a mutex. The whole block

**Comment by YugoAmaryl** [comment]
Thank you for your answer.
The code I gave as an example is executed in a handler when a request is received through the network. I would therefore expect it to be executed in a worker thread...

Why wouldn't a global mutex solve the problem?

"If a new request arrives and it is in the middle of a transaction then it could save the msg in the queue"

I don't see how to do such an implementation without a mutex. You need to be able to read the state and enqueue atomically. How to watch the state of the queue?

**Comment by kroggen** [comment]
Node.js is event loop based. Only the main thread will use your code, so there is no need to use mutex for nothing. Indeed a non-reentrant mutex could make node.js to block waiting to acquire a lock while it cannot be released by the same thread.

So you can handle the queue normally.

Suggested readings:
http://blog.mixu.net/2011/02/01/understanding-the-node-js-event-loop/
http://abdelraoof.com/blog/2015/10/28/understanding-nodejs-event-loop/

**Comment by kroggen** [comment]
You can use [node-mutex](https://www.npmjs.com/package/node-mutex) as it is not exactly a mutex. You can see it uses a callback.

Or [push-queue](https://www.npmjs.com/package/push-queue).

**Comment by YugoAmaryl** [comment]
Solution...

But first, let me acknowledge that my code in the first message is stupid. Since all the operations on the db are asynchronous, the try catch up there is useless.

I discussed the matter with a colleague of mine, and it appeared I could simply get rid of the transaction :

```
    db.get("SELECT version FROM todos WHERE id = ?", [msg.id], function (err, row)
    {
        if (err)
        {
            console.log(err);
            publish(msg.sender, {cmd: "err", err: err, request: msg});
            return;
        }
        var newVersion = row.version + 1;
        db.run("UPDATE todos SET title = ?, version = ? WHERE id = ? AND version = ?", [msg.title, newVersion, msg.id, row.version], function(err){
            if (err)
            {
                console.log(err);
                publish(msg.sender, {cmd: "err", err: err, request: msg});
                return;
            }
            if (this.changes)
                publish("broadcast", {cmd: "edit", todo: {id: msg.id, title: msg.title, version: newVersion}});
        });
```
