### ISSUE TITLE
Undefined variable module_name in binding.gyp while trying to load binding.gyp

### ISSUE THREAD

**Issue by niravjgandhi** [TryGhost/node-sqlite3#766]
Hi When i try to install sqllite3 and binding with the node webkit version 0.19.4 it says 
Undefined variable module_name in binding.gyp while trying to load binding.gyp
`gyp info it worked if it ends with ok
gyp info using nw-gyp@3.4.0
gyp info using node@6.9.5 | win32 | x64
gyp info spawn C:\Python27\python.EXE
gyp info spawn args [ 'C:\\Users\\act031\\AppData\\Roaming\\npm\\node_modules\\nw-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=auto',
gyp info spawn args   '-I',
gyp info spawn args   'F:\\svnrepo\\mosaic_site_server\\app\\node_modules\\sqlite3\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\act031\\AppData\\Roaming\\npm\\node_modules\\nw-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\act031\\.nw-gyp\\0.19.4\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\act031\\.nw-gyp\\0.19.4',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\act031\\AppData\\Roaming\\npm\\node_modules\\nw-gyp',
gyp info spawn args   '-Dnode_lib_file=nw.lib',
gyp info spawn args   '-Dmodule_root_dir=F:\\svnrepo\\mosaic_site_server\\app\\node_modules\\sqlite3',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '-Dv13=1',
gyp info spawn args   '--generator-output',
gyp info spawn args   'F:\\svnrepo\\mosaic_site_server\\app\\node_modules\\sqlite3\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp: Undefined variable module_name in binding.gyp while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\act031\AppData\Roaming\npm\node_modules\nw-gyp\lib\configure.js:324:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 6.1.7600
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\act031\\AppData\\Roaming\\npm\\node_modules\\nw-gyp\\bin\\nw-gyp.js" "con
figure" "--target=0.19.4"
gyp ERR! cwd F:\svnrepo\mosaic_site_server\app\node_modules\sqlite3
gyp ERR! node -v v6.9.5
gyp ERR! nw-gyp -v v3.4.0
gyp ERR! not ok
`

**Comment by mackybean** [comment]
I currently have the same issue

**Comment by cyrilfr** [comment]
Having the same issue on Ubuntu 20.04 with Node.js v10.19.0, sqlite3 v4.2.0 and node-gyp vv6.1.0.

**Comment by daniellockyer** [comment]
Would you be able to try with v5.0.3? 🙂
