### ISSUE TITLE
Download node-v48-linux-arm.tar.gz got 403

### ISSUE THREAD

**Issue by bestplay** [TryGhost/node-sqlite3#770]
node-pre-gyp ERR! Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.8/node-v48-linux-arm.tar.gz

I have tried :

- node0.10 / node6.9.5
- --unsafe-perm

didn't work for me

**Comment by rzr** [comment]
I am able to build a package, is there a place where I can upload it ?

https://github.com/mapbox/node-sqlite3/pull/1028

**Comment by daniellockyer** [comment]
Closing as this should no longer be relevant 🙂
