### ISSUE TITLE
Change request version to 2.79.0

### ISSUE THREAD

**Issue by ajmas** [TryGhost/node-sqlite3#776]
The current version of the project depends on request 2.76.0 which uses the deprecated module node-uuid. The latest version uses uuid, which is the recommended replacement package.

**Comment by springmeyer** [comment]
It is actually the node-pre-gyp tool, which is used for installing binaries. So to fix this we'll need to tag a new release that re-packages node-pre-gyp (since it is bundled due to https://github.com/mapbox/node-pre-gyp/issues/260)

**Comment by wmertens** [comment]
This has been done, this issue can be closed.
