### ISSUE TITLE
Modify SQLITE_LIMIT_VARIABLE_NUMBER

### ISSUE THREAD

**Issue by patrickdevivo** [TryGhost/node-sqlite3#780]
Hi all,

I apologize if this is the wrong place for me to post this.

I'd like to modify a SQLite3 limit, specifically: `SQLITE_LIMIT_VARIABLE_NUMBER` (I'd like to increase it).

However it [seems](http://stackoverflow.com/questions/12271877/is-it-possible-to-call-the-sqlite3-limit-function-from-sql) like I can only do so by calling `sqlite3_limit()` in the C implementation.

1) Is there an easy way (set a flag at compile time?) to modify this limit?
2) If not, would it be possible to develop a small loadable extension that makes that call and load it?
3) Are 1 or 2 viable solutions, if not, what might be?

Please let me know! And if this is more suitable for stackoverflow I can move there.

Thanks,
Patrick

**Comment by Circuit8** [comment]
Anyone have an update about this? Currently running into this issue.

Cheers

**Comment by andrewdotn** [comment]
Sadly `sqlite3_limit()` can only *lower* the limit at runtime, from its default value of 999, but not increase it.

https://www.sqlite.org/c3ref/c_limit_attached.html:

> These constants define various performance limits that can be lowered at run-time using `sqlite3_limit()`

The docs do explain how to [change that default at compile time][max_variable_number] though. Translated for `node-sqlite3`, that would be:

[max_variable_number]: https://www.sqlite.org/limits.html#max_variable_number

    --- a/deps/sqlite3.gyp
    +++ b/deps/sqlite3.gyp
    @@ -97,6 +97,7 @@
        'defines': [
            '_REENTRANT=1',
    +       'SQLITE_MAX_VARIABLE_NUMBER=10000',
            'SQLITE_THREADSAFE=1',
            'HAVE_USLEEP=1',
            'SQLITE_ENABLE_FTS3',
            'SQLITE_ENABLE_FTS4',

**Comment by daniellockyer** [comment]
v5.0.3 ships with SQLIte v3.38.2, and v3.32.0 increased the limit to 32766. I'm going to close this as it should solve your initial request of 10000, although the limit is still not configurable yet 🙂
