### ISSUE TITLE
illumos systems need -D__EXTENSIONS__ for large file compilation

### ISSUE THREAD

**Issue by jclulow** [TryGhost/node-sqlite3#781]
To give 32-bit binaries the ability to deal with files larger than 2GB, illumos provides the [large file compilation environment](http://illumos.org/man/5/lfcompile).  This environment appears to be correctly activated with the current set of build scripts; i.e., `-D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64` is passed to the C compiler.

The _node-sqlite3_ build specifies `std=c99`, and according to the GCC documentation:

> By default, GCC provides some extensions to the C language that on rare occasions conflict with the C standard.
> ...
> Use of the `-std` options listed above will disable these extensions where they conflict with the C standard version selected.

illumos systems are generally strict about symbol visibility, and unfortunately for this case the selection of strict C99 conformance (via `-std=c99`) appears to preclude the use of the large file compilation environment.  Through the use of `-D__EXTENSIONS__`, we can enable interfaces that, though not strict C99, are generally safe to use -- including the large file versions of calls like `lstat(2)`, etc.

**Comment by jclulow** [comment]
I'm not particularly familiar with the use of `gyp`, but I've put together [a patch](https://github.com/mapbox/node-sqlite3/compare/master...jclulow:illumos_lfcompile) that seems to work so far.

**Comment by davepacheco** [comment]
Is there any chance we could get this change integrated?

**Comment by daniellockyer** [comment]
Please open a PR and I'd be happy to take a look 🙂
