### ISSUE TITLE
Issue with cached database

### ISSUE THREAD

**Issue by papakai** [TryGhost/node-sqlite3#783]
When trying to open a database file (new sqlite3.cached.Database) which has access rights set in a way that opening it will fail, further connections to that file will simply run into a timeout.

So why not cleaning up sqlite3.cached.objects in case of such an error and to make it possible to recreate that db from scratch for example.

So, what I did was to simply write some unit test for error handling.

`
var filename = __dirname + '/../mydatabase.db';
 fs.open(filename, 'r', function(err) {
        var fd;
        if (err) {
          fs.writeFileSync(filename, '');
        }
        fd = fs.openSync(filename, 'r+');
        fs.fchmodSync(fd, '0100');
        fs.closeSync(fd);
        
       /*
        here i instantiate now the DB and do some SQL
        if anything fails that error will be returned in the callback
        finally I delete this testfile
       
        The next test will reuse this database (and as that db file does not exist, I would expect it to be created through my source code as I have this handled.
       */
});`

Any attempt to close that cached db instance in the error handler seems not to be working.

When I change the instantiation from new sqlite3.cached.Database to new sqlite3.Database, all tests succeed.

**Comment by daniellockyer** [comment]
Hey @papakai, if this is still an issue, would you be able to re-open the issue with an issue template? 🙂 https://github.com/TryGhost/node-sqlite3/issues/new/choose
