### ISSUE TITLE
SQLITE RTREE

### ISSUE THREAD

**Issue by bertrandmd** [TryGhost/node-sqlite3#784]
Hi, 

is node-sqlite3 build with the option -DSQLITE_ENABLE_RTREE ?

when i used it on cordova application, I have `Error: SQLITE_ERROR:no such module: rtree`

thanks for the help,

Bertrand

**Comment by rs0h** [comment]
Despite that the question is old but installing with build helps:

`npm install sqlite3 --loglevel=verbose --build-from-source`

Does anyone know if there is a better solution?

**Comment by daniellockyer** [comment]
This is now shipped in the prebuilt binaries 🙂
