### ISSUE TITLE
Getting prebuilt binaries

### ISSUE THREAD

**Issue by premitius** [TryGhost/node-sqlite3#785]
When building an Electron App on Mac containing node-sqlite3, the app doesn't work on Windows because it's missing a binary. I would like to be able to build the app on Mac for all platforms (Mac,Win & Linux). I understand it has something to do with prebuilt binaries, but can't figure it out from the docs, can you please help?

**Comment by Bizarrus** [comment]
Need the same.

Im using `node-sqlite3` with `node-webkit`.

**Comment by jefpmn** [comment]
i had compiled binding for `electron-1.4-win32-ia32` and `electron-1.4-win32-x64`. want to try my prebuilt binding binary?

**Comment by tsemerad** [comment]
@jefpmn Yes, could you post it?

**Comment by jefpmn** [comment]
of course, i just uploaded [here](https://www.dropbox.com/sh/rp4pc9fn1qdmqnd/AACcK4TrfMho8O6DCokdqdOga?dl=0). this binding compiled with electron 1.4.12 header. just tell me if you need another version.

**Comment by tsemerad** [comment]
Thank you very much!

**Comment by daniellockyer** [comment]
Would you be able to try with v5.0.3? 🙂
