### ISSUE TITLE
Upgrade bundled sqlite

### ISSUE THREAD

**Issue by agauniyal** [TryGhost/node-sqlite3#786]
Version 3.17.0 - https://www.sqlite.org/download.html - https://www.sqlite.org/releaselog/3_17_0.html

Brings better perf for few cases :)

**Comment by koljakutschera** [comment]
2017-06-08 (3.19.3)

**Comment by daniellockyer** [comment]
v5.0.3 now ships with SQLite v3.38.2 🙂
