### ISSUE TITLE
Is there a way to interact with the VFS part of SQLite?

### ISSUE THREAD

**Issue by lmatteis** [TryGhost/node-sqlite3#801]
I need to interact with the VFS part of SQLite: https://sqlite.org/vfs.html

Is there a way to do this via these bindings?

**Comment by hn3000** [comment]
You can specify which one of the built-in VFS should be used by giving the vfs= parameter on the database uri, you may need to enable uri processing using the mode bit SQLITE_OPEN_URI (0x40, see https://sqlite.org/uri.html ).

Is that the type of interaction you're looking for?

**Comment by daniellockyer** [comment]
Closing as the issue is stale but please re-open with an issue template if it's still desired 🙂
