### ISSUE TITLE
Is it possible to get the output from executing a non-CRUD SQL command (e.g. a PRAGMA)?

### ISSUE THREAD

**Issue by andrewferrier** [TryGhost/node-sqlite3#806]
I am attempting to use node-sqlite3 to run `PRAGMA integrity_check` against a SQLite DB. I have tried this with both `Database.run` and `Database.exec` - in both cases the command appears to execute OK, but I don't get any useful information in the callback to be sure (just `null` to indicate there wasn't an error - but I'm not even sure that PRAGMA errors would be trapped anyway). When I run this interactively using the sqlite command-line util, I get an output that explicitly says "ok" - I'd like to be able to get this output from the node-sqlite3 API so I can check it explicitly (and obviously the non-happy-path case too).

**Comment by keenguy** [comment]
Use Database.get() instead.   You'll get the output in the callback.
```
Database.get("pragma schema_version;",function(err,res){
                    if(err){
                        console.log("invalid database !");
                    }else{
                        console.log(res);
                    }
                });
```
The output may look like `{ schema_version: 0 }`. This can also be used to decide whether a database really exists.
