### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by ORESoftware** [TryGhost/node-sqlite3#809]
Not sure if you have TS support or if that's in the works, but Webstorm complains a lot with this library, saying methods are not recognized or arguments/signatures are wrong. e.g.:

`sql.Database` => Unresolved type "Database" (WS assumes this is a class/constructor)
`db.configure `=> Unresolved function or method
`db.serialize(function(){}); `=> Argument type Function is not assignable to parameter type Request 

![screenshot 2017-04-19 14 31 37](https://cloud.githubusercontent.com/assets/11139560/25203174/1433ca32-250d-11e7-8d51-e16f8c178167.png)

It would be really cool if you rewrote with TS (doesn't take that long, usually), and exported some type info.

Here is a really weird warning, by the way:

![screenshot 2017-04-19 14 33 41](https://cloud.githubusercontent.com/assets/11139560/25203204/392e37aa-250d-11e7-8c85-03f09a977e10.png)

Thanks!

**Comment by natesilva** [comment]
There’s an `@types/sqlite3` but it only describes version 2.2. Would be nice to have it updated for version 3.

**Comment by hn3000** [comment]
An update for version 3.1 has been merged some days ago: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/16656

**Comment by kewde** [comment]
@daniellockyer https://github.com/microsoft/vscode-node-sqlite3/blob/vscode/index.d.ts

**Comment by daniellockyer** [comment]
@kewde I believe they also opened a PR for that here: https://github.com/TryGhost/node-sqlite3/pull/1527

Will get around to checking it at some point 🙂

**Comment by daniellockyer** [comment]
I've merged a PR to add this: https://github.com/TryGhost/node-sqlite3/commit/ffda15f49dcbc4da6dc8025af864098330479a5c

I'll be updating the types before releasing soon 🙂
