### ISSUE TITLE
npm install sqlite3 fail on Ubuntu

### ISSUE THREAD

**Issue by cool-firer** [TryGhost/node-sqlite3#815]
npm-debug.log, for short:
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   'sqlite3' ]
2 info using npm@3.8.3
3 info using node@v5.10.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData sqlite3@https://registry.npmjs.org/sqlite3/-/sqlite3-3.1.8.tgz
8 silly fetchOtherPackageData sqlite3@https://registry.npmjs.org/sqlite3/-/sqlite3-3.1.8.tgz
9 silly cache add args [ 'sqlite3@https://registry.npmjs.org/sqlite3/-/sqlite3-3.1.8.tgz',
9 silly cache add   null ]
10 verbose cache add spec sqlite3@https://registry.npmjs.org/sqlite3/-/sqlite3-3.1.8.tgz
11 silly cache add parsed spec Result {
11 silly cache add   raw: 'sqlite3@https://registry.npmjs.org/sqlite3/-/sqlite3-3.1.8.tgz',
11 silly cache add   scope: null,
11 silly cache add   name: 'sqlite3',
11 silly cache add   rawSpec: 'https://registry.npmjs.org/sqlite3/-/sqlite3-3.1.8.tgz',
11 silly cache add   spec: 'https://registry.npmjs.org/sqlite3/-/sqlite3-3.1.8.tgz',
11 silly cache add   type: 'remote' }
12 silly mapToRegistry name sqlite3@https://registry.npmjs.org/sqlite3/-/sqlite3-3.1.8.tgz
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry https://registry.npmjs.org/
15 silly mapToRegistry data Result {
15 silly mapToRegistry   raw: 'sqlite3@https://registry.npmjs.org/sqlite3/-/sqlite3-3.1.8.tgz',
15 silly mapToRegistry   scope: null,
15 silly mapToRegistry   name: 'sqlite3',
15 silly mapToRegistry   rawSpec: 'https://registry.npmjs.org/sqlite3/-/sqlite3-3.1.8.tgz',
15 silly mapToRegistry   spec: 'https://registry.npmjs.org/sqlite3/-/sqlite3-3.1.8.tgz',
15 silly mapToRegistry   type: 'remote' }
16 silly mapToRegistry uri https://registry.npmjs.org/sqlite3/-/sqlite3-3.1.8.tgz
17 verbose addRemoteTarball https://registry.npmjs.org/sqlite3/-/sqlite3-3.1.8.tgz not in flight; adding
18 verbose addRemoteTarball [ 'https://registry.npmjs.org/sqlite3/-/sqlite3-3.1.8.tgz',
18 verbose addRemoteTarball   null ]
19 info retry fetch attempt 1 at 10:48:21
20 info attempt registry request try #1 at 10:48:21
21 http fetch GET https://registry.npmjs.org/sqlite3/-/sqlite3-3.1.8.tgz
22 verbose request id de1ac33a922a3eb6
23 http fetch 200 https://registry.npmjs.org/sqlite3/-/sqlite3-3.1.8.tgz
24 silly fetchAndShaCheck shasum 4cbcf965d8b901d1b1015cbc7fc415aae157dfaa
25 verbose addTmpTarball /tmp/npm-18498-15b20608/registry.npmjs.org/sqlite3/-/sqlite3-3.1.8.tgz not in flight; adding
26 verbose correctMkdir /root/.npm correctMkdir not in flight; initializing
27 verbose addTmpTarball validating metadata from /tmp/npm-18498-15b20608/registry.npmjs.org/sqlite3/-/sqlite3-3.1.8.tgz
28 verbose tar unpack /tmp/npm-18498-15b20608/registry.npmjs.org/sqlite3/-/sqlite3-3.1.8.tgz
29 verbose tar unpacking to /tmp/npm-18498-15b20608/unpack-91e3d77b
30 silly gentlyRm /tmp/npm-18498-15b20608/unpack-91e3d77b is being purged
31 verbose gentlyRm don't care about contents; nuking /tmp/npm-18498-15b20608/unpack-91e3d77b
32 silly gunzTarPerm modes [ '755', '644' ]
33 silly gunzTarPerm extractEntry package.json
34 silly gunzTarPerm extractEntry README.md
35 silly gunzTarPerm extractEntry LICENSE
36 silly gunzTarPerm extractEntry .eslintrc.js
37 silly gunzTarPerm extractEntry sqlite3.js
38 silly gunzTarPerm extractEntry binding.gyp
39 silly gunzTarPerm extractEntry appveyor.yml
40 silly gunzTarPerm extractEntry deps/common-sqlite.gypi
41 silly gunzTarPerm extractEntry deps/extract.py
42 silly gunzTarPerm extractEntry deps/sqlite-autoconf-3150000.tar.gz
43 silly gunzTarPerm extractEntry deps/sqlite3.gyp
44 silly gunzTarPerm extractEntry lib/index.js
45 silly gunzTarPerm extractEntry lib/sqlite3.js
46 silly gunzTarPerm extractEntry lib/trace.js
47 silly gunzTarPerm extractEntry src/async.h
48 silly gunzTarPerm extractEntry src/database.cc
49 silly gunzTarPerm extractEntry src/database.h

**Comment by cool-firer** [comment]
Here is debug log
[npm-debug.txt](https://github.com/mapbox/node-sqlite3/files/972382/npm-debug.txt)

**Comment by cool-firer** [comment]
alright, I update the npm version: npm install -g npm, problems sovled!

**Comment by agauniyal** [comment]
@cool-firer you should close this issue then :)
