### ISSUE TITLE
npm ERR! Failed at the sqlite3@3.1.8 install script.

### ISSUE THREAD

**Issue by pavinthan** [TryGhost/node-sqlite3#839]
node-pre-gyp ERR! Tried to download(undefined): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.8/node-v57-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for sqlite3@3.1.8 and node@8.1.2 (node-v57 ABI) (falling back to source compile with node-gyp)

**Comment by peterssonanton** [comment]
```
node-pre-gyp http GET https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.8/node-v48-linux-x64.tar.gz
node-pre-gyp ERR! Tried to download(undefined): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.8/node-v48-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for sqlite3@3.1.8 and node@6.11.2 (node-v48 ABI) (falling back to source compile with node-gyp) 
```


I have the same error with node 6.11.2

**Comment by daniellockyer** [comment]
Would you be able to try v5.0.3? 🙂
