### ISSUE TITLE
Confusing documentation on how to create a database

### ISSUE THREAD

**Issue by mblandfo** [TryGhost/node-sqlite3#844]
https://github.com/mapbox/node-sqlite3/wiki/API
> callback (optional): If provided, this function will be called when the database was opened successfully or when an error occurred.

There aren't any examples either. So, when I do this:

`var db = new sqlite3.Database(data.dbPath, mode, err => {`

If the database doesn't exist and I pass in mode = sqlite3.OPEN_CREATE, well, that crashes with Error: SQLITE_MISUSE: out of memory

So, I don't pass in mode and that works. Ah, next issue: If the db file does not exist, the callback does not get called. So, I can use the returned db immediately, I guess? I think the documentation should clarify this - I spent some time trying to figure out why the db file was created but the callback was never called. That's technically a bug given the current documentation wording. If I open the file like this and the file did already exist, then the callback is called even though there is no error, so that's inconsistent.

**Comment by mereacre** [comment]
I get the same "Error: SQLITE_MISUSE: out of memory" when assign the callback function to the sqlite.Database function.

**Comment by dhulke** [comment]
Is this still an open issue? Can I use the database right away or do I have to wait for the callback?

**Comment by alexjab** [comment]
In case anyone is wondering, the solution is provided in this thread https://github.com/mapbox/node-sqlite3/issues/674

The key here is to use:

```
sqlite3.OPEN_READWRITE | sqlite3.OPEN_CREATE
```
