### ISSUE TITLE
'npm install --json --silent' produces invalid JSON with sqlite3 package

### ISSUE THREAD

**Issue by thehunmonkgroup** [TryGhost/node-sqlite3#850]
Something in the sqlite3 build process spits out a ```[sqlite3] Success:``` line prior to outputting JSON when executing the install with ```npm install --json --silent```:

```
[~/Desktop/test] $ npm install --json --silent
[sqlite3] Success: "/Users/hunmonk/Desktop/test/node_modules/sqlite3/lib/binding/node-v48-darwin-x64/node_sqlite3.node" is installed via remote
{
  "name": "test",
  "version": "0.0.1",
  "dependencies": {
    "sqlite3": {
  ...clipped...
```

That line creates a problem, because the output is no longer a valid, parseable JSON string. Using the ```---silent``` arg with NPM *should* suppress all output besides the JSON string, so not sure what's going on there.

Any ideas where that output is generated, and why it's being output in this case?

**Comment by daniellockyer** [comment]
I believe this is a bug in node-pre-gyp: https://github.com/mapbox/node-pre-gyp/blob/7da93d8fd5c1924557884fb4273925d9411b1df4/lib/install.js#L229. Please report it there and I'd be happy to merge the update 🙂
