### ISSUE TITLE
Is it possible to return a row as an array of positional values instead of an object?

### ISSUE THREAD

**Issue by dennismckinnon** [TryGhost/node-sqlite3#854]
The problem I'm having is I am doing a lot of joins on automatically generated tables, many of which will have columns with the same names but this will obviously not work because the object field names can't collide.

for example:

SELECT ref.date, t0.date, t1.date FROM ...

I know I can get around this by doing something like the following:

SELECT ref.date, t0.date as c1, t1.date as c2 FROM ...

and wrapping the function to force it into an array but this makes the solution somewhat less nice. When using the sqlite module in python it returns as lists... well tuples so I was hoping that this functionality was available in the node-sqlite module and was just hidden as a parameter or something.

Thanks

**Comment by dennismckinnon** [comment]
basically is this the best way I can handle this right now?

```
function toArray(row){
	var rowArray = []

	Object.keys(row).forEach(function(element, key){
		rowArray.push(row[element])
	})

	return rowArray
}

sqlcache.prototype.all = function(stmt, callback) {
	var self = this;

	self.db.all(stmt, function(err, rows){
		if (err) return callback(err);
		newRows = rows.map(toArray)
		return callback(null, newRows)
	})
}
```

I'm worried that it might be fragile, can we be sure that the order of the keys in the object will be the same as the order specified in the select? 

Thanks for any insight you can provide

**Comment by jimmywarting** [comment]
have the same question...

**Comment by daniellockyer** [comment]
It's not currently possible but if there is sufficient demand, it could be added. Given the issue is old and stale, I'm going to close this for now
