### ISSUE TITLE
Problem with building sqlite3+sqlcipher for electron on Windows. Please help!

### ISSUE THREAD

**Issue by ororambocentric** [TryGhost/node-sqlite3#856]
Does anybody know how to build node-sqlite3 with sqlcipher for electron on Windows? For linux I'm doing this:

export LDFLAGS="-L/usr/local/lib"
export CPPFLAGS="-I/usr/local/include -I/usr/local/include/sqlcipher"
export CXXFLAGS="$CPPFLAGS"
npm install sqlite3 --build-from-source --sqlite_libname=sqlcipher --sqlite=/usr/local --verbose

and then something like this:

cd node_modules/sqlite3 && node-gyp configure --module_name=node_sqlite3 --build-from-source --sqlite_libname=sqlcipher --sqlite=/usr/local --module_path=../lib/binding/electron-v1.4-linux-x64 && node-gyp rebuild --target=1.4.13 --arch=x64 --target_platform=linux --dist-url=https://atom.io/download/atom-shell --module_name=node_sqlite3 --build-from-source --sqlite_libname=sqlcipher --sqlite=/usr/local --module_path=../lib/binding/electron-v1.4-linux-x64 && cd -

But it's unclear how to do it on Windows OS

**Comment by mm739521** [comment]
I'm having the same issue, help would greatly be appreciated!

**Comment by silaspedrosa** [comment]
Me too! I've trying to use sqlcipher from electron on Windows for months. It seems to be something really hard to accomplish. Does anyone has a clue?

**Comment by bobnguyen** [comment]
I have same trouble.

**Comment by daniellockyer** [comment]
Closing as the issue is stale but please try with the latest version 🙂
