### ISSUE TITLE
Problem cross-compiling for Node.js with Visual Studio 2017

### ISSUE THREAD

**Issue by 10rsaxman** [TryGhost/node-sqlite3#874]
Attempting to use Sqlite3 with Node.JS on a RaspberryPi running Windows 10 IoT.
Development environment is MS Visual Studio Community 2017.
Trying to build npm package from within visual studio, using the built in npm package manager.

Package manager runs the command:
npm install sqlite3 --save --target-arch=arm

Package installation fails. See attached log.

[npm-debug.txt](https://github.com/mapbox/node-sqlite3/files/1294048/npm-debug.txt)

**Comment by springmeyer** [comment]
We need the output of the terminal to help debug, not the `npm-log.txt`

**Comment by 10rsaxman** [comment]
Here is the terminal output. Note, the command is run with administrative privileges.

C:\WINDOWS\system32>npm install sqlite3 --save --target-arch=arm

> sqlite3@3.1.11 install C:\WINDOWS\system32\node_modules\sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.11/node-v48-win32-arm.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for sqlite3@3.1.11 and node@6.11.3 (node-v48 ABI) (falling back to source compile with node-gyp)
C:\Python27\python.exe: can't open file 'C:\Windows\System32\node_modules\node-gyp\gyp\gyp_main.py': [Errno 2] No such file or directory
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onCpExit (C:\Windows\System32\node_modules\node-gyp\lib\configure.js:336:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:219:12)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Windows\\System32\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=C:\\WINDOWS\\system32\\node_modules\\sqlite3\\lib\\binding\\node-v48-win32-arm\\node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=C:\\WINDOWS\\system32\\node_modules\\sqlite3\\lib\\binding\\node-v48-win32-arm" "--python=C:\\Python27\\python.exe" "--msvs_version=2017"
gyp ERR! cwd C:\WINDOWS\system32\node_modules\sqlite3
gyp ERR! node -v v6.11.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Windows\System32\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\WINDOWS\system32\node_modules\sqlite3\lib\binding\node-v48-win32-arm\node_sqlite3.node --module_name=node_sqlite3 --module_path=C:\WINDOWS\system32\node_modules\sqlite3\lib\binding\node-v48-win32-arm --python=C:\Python27\python.exe --msvs_version=2017' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Windows\System32\node_modules\sqlite3\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:920:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
node-pre-gyp ERR! System Windows_NT 10.0.15063
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Windows\\System32\\node_modules\\sqlite3\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\WINDOWS\system32\node_modules\sqlite3
node-pre-gyp ERR! node -v v6.11.3
node-pre-gyp ERR! node-pre-gyp -v v0.6.37
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe C:\Windows\System32\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\WINDOWS\system32\node_modules\sqlite3\lib\binding\node-v48-win32-arm\node_sqlite3.node --module_name=node_sqlite3 --module_path=C:\WINDOWS\system32\node_modules\sqlite3\lib\binding\node-v48-win32-arm --python=C:\Python27\python.exe --msvs_version=2017' (1)
npm WARN enoent ENOENT: no such file or directory, open 'C:\WINDOWS\system32\package.json'
npm WARN system32 No description
npm WARN system32 No repository field.
npm WARN system32 No README data
npm WARN system32 No license field.
npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "sqlite3" "--save" "--target-arch=arm"
npm ERR! node v6.11.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! sqlite3@3.1.11 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sqlite3@3.1.11 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sqlite3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sqlite3
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sqlite3
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\WINDOWS\system32\npm-debug.log

**Comment by e-beach** [comment]
So the first issue is that https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.11/node-v48-win32-arm.tar.gz returns 403 Forbidden. Why could that be happening?

**Comment by 10rsaxman** [comment]
The 403 error is because there is not a pre-built binary for Windows 10 IoT on a Raspberry Pi (win32-arm). npm is supposed to manage compiling a binary for my system. Somewhere in the compilation stage is where the process fails. This is what I am looking for help troubleshooting.

**Comment by daniellockyer** [comment]
Would you be able to try with v5.0.3? 🙂
