### ISSUE TITLE
npm i fails on ubuntu 16.04

### ISSUE THREAD

**Issue by empierre** [TryGhost/node-sqlite3#880]
node v4.4.7
Linux tnef 4.2.0-42-lowlatency 
Ubuntu 16.04.3 LTS

**Comment by empierre** [comment]
npm debug
[a.zip](https://github.com/mapbox/node-sqlite3/files/1311907/a.zip)

**Comment by daniellockyer** [comment]
Would you be able to try with v5.0.3? 🙂
