### ISSUE TITLE
SELECT query text field result sometimes null, appears to truncate based on length

### ISSUE THREAD

**Issue by nbuchanan** [TryGhost/node-sqlite3#881]
I am having trouble with the result rows for a query when I run it using the node-sqlite3 bindings. Sometimes the expected value for a column returns and sometimes it is null. The issue can be reproduced with SQL similar to the following.

`SELECT product_type as productType, AsGeoJSON(Simplify(ST_UnaryUnion(ST_Collect(geometry)), 0.001)) as geom FROM footprints GROUP BY product_type;`

and the code snippet that is used is essentially `db.each(SQL_ABOVE, rowCallback, completionCallback)`

In my test table there are two product types. When I get the result rows back in the callback the row corresponding to Type 1 has null for the `geom` property and Type 2 has the GeoJSON string I would expect. The reason I am hoping I might get some type of insight here is that the same query runs on the same database as expected when run in other clients (IntelliJ, DB Browser for SQLite, etc.). It seems like there is something either being truncated or the callback is being called prematurely. In the other clients I queried the length of the `geom` result for each type. Type 1 was 264 and Type 2 was 220 - could there be something internally in the node bindings that is limiting allowed results to 256?

I realize that this might not be an "officially" supported configuration but I am hoping someone might at least be able to point me in the direction of where to look internally. I have tried wrapping the logic in serialize, in the query itself asking for WKB and WKT instead of GeoJSON, switching out use of the db.each() method to a statement based approach as well as a call to db.all(), explicitly using `CAST(x) AS TEXT` and nothing seems to give me any clues. I am grasping at straws at this point.

Thanks in advance.

**Comment by daniellockyer** [comment]
Closing as the issue is stale but please re-open with an issue template and a repro case if it's still a problem 🙂
