### ISSUE TITLE
flapping tests

### ISSUE THREAD

**Issue by springmeyer** [TryGhost/node-sqlite3#887]
Seeing this failure randomly on travis, like 1 in 100 times. Has happened with node v4 on OS X against the brew sqlite. And also another version I don't remember right now:

```
  133 passing (34s)
  1 failing
  1) each retrieve 100,000 rows with Statement#each:
      Uncaught AssertionError: Only retrieved 99582 out of 100000 rows.
      + expected - actual
      -99582
      +100000
      
      at Database.<anonymous> (test/each.test.js:20:20)
```

**Comment by daniellockyer** [comment]
Haven't seen anything like that yet but will keep an eye out 🙂
