### ISSUE TITLE
Can not Build node-sqlite3 for nw.js on win7.

### ISSUE THREAD

**Issue by bensonzhow** [TryGhost/node-sqlite3#891]
**I'm almost ready for the component environment to build node-sqlite3 for nw.js,but always compile not ok.
The following is the console information**

Z:\xwork\zdemo\app>npm install sqlite3 --build-from-source --runtime=node-webkit
 --target_arch=x64 --target=0.24.2

> sqlite3@3.1.12 install Z:\xwork\zdemo\app\node_modules\sqlite3
> node-pre-gyp install --fallback-to-build

gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: read ECONNRESET
gyp ERR! stack     at exports._errnoException (util.js:953:11)
gyp ERR! stack     at TCP.onread (net.js:563:26)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\admin\\AppDat
a\\Roaming\\npm\\node_modules\\nw-gyp\\bin\\nw-gyp.js" "configure" "--fallback-t
o-build" "--module=Z:\\xwork\\zdemo\\app\\node_modules\\sqlite3\\lib\\binding\\n
ode-webkit-v0.24.2-win32-x64\\node_sqlite3.node" "--module_name=node_sqlite3" "-
-module_path=Z:\\xwork\\zdemo\\app\\node_modules\\sqlite3\\lib\\binding\\node-we
bkit-v0.24.2-win32-x64" "--python=C:/Python27" "--msvs_version=2013"
gyp ERR! cwd Z:\xwork\zdemo\app\node_modules\sqlite3
gyp ERR! node -v v6.2.0
gyp ERR! nw-gyp -v v3.4.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'nw-gyp.cmd configure --fallbac
k-to-build --module=Z:\xwork\zdemo\app\node_modules\sqlite3\lib\binding\node-web
kit-v0.24.2-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path
=Z:\xwork\zdemo\app\node_modules\sqlite3\lib\binding\node-webkit-v0.24.2-win32-x
64 --python=C:/Python27 --msvs_version=2013' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (Z:\xwork\zdemo\app\node
_modules\sqlite3\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:850:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/chi
ld_process.js:215:5)
node-pre-gyp ERR! System Windows_NT 6.1.7601
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "Z:\\xwork\\zdem
o\\app\\node_modules\\sqlite3\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "i
nstall" "--fallback-to-build"
node-pre-gyp ERR! cwd Z:\xwork\zdemo\app\node_modules\sqlite3
node-pre-gyp ERR! node -v v6.2.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.38
node-pre-gyp ERR! not ok
Failed to execute 'nw-gyp.cmd configure --fallback-to-build --module=Z:\xwork\zd
emo\app\node_modules\sqlite3\lib\binding\node-webkit-v0.24.2-win32-x64\node_sqli
te3.node --module_name=node_sqlite3 --module_path=Z:\xwork\zdemo\app\node_module
s\sqlite3\lib\binding\node-webkit-v0.24.2-win32-x64 --python=C:/Python27 --msvs_
version=2013' (1)
npm WARN zdemo@1.0.0 No repository field.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "sqlite3" "--build-from-source" "-
-runtime=node-webkit" "--target_arch=x64" "--target=0.24.2"
npm ERR! node v6.2.0
npm ERR! npm  v3.8.9
npm ERR! code ELIFECYCLE

npm ERR! sqlite3@3.1.12 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sqlite3@3.1.12 install script 'node-pre-gyp install --fal
lback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sqlite3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sqlite3
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sqlite3
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     Z:\xwork\zdemo\app\npm-debug.log

**Comment by Zuzon** [comment]
try to build --target=0.22.2
only this target works for me

**Comment by daniellockyer** [comment]
Would you be able to try with v5.0.3? 🙂
