### ISSUE TITLE
can not find sqlite3 module in node.js v9.0.0

### ISSUE THREAD

**Issue by liukaigsx** [TryGhost/node-sqlite3#902]

**Comment by nshtg** [comment]
+ Building fallback fails on node 9.0.0 on both windows and linux

**Comment by nshtg** [comment]
If you want to build sqlite with docker you need additional dependencies:

```
# If there are no pre-built sqlite3 versions available we have to build it.
RUN apk --no-cache add --virtual .build-dependencies python gcc g++ make \
 && npm install --strip . \
 && npm cache clean --force \
 && apk del .build-dependencies
```

**Comment by patlachance** [comment]
same issue when trying to install as root in docker container with:
node -v: 9.0.0
npm -v: 5.5.1
docker: 17.10.0-ce

**Comment by rpellerin** [comment]
Would love to see this issue fixed as well :)

**Comment by lhammond** [comment]
same here

**Comment by telmotrooper** [comment]
Arch Linux has updated it's Node.js package to 9.2.0, which broke node-sqlite3 for me.

I tried downgrading the package with `sudo pacman -U /var/cache/pacman/pkg/nodejs-8.8.1-1-x86_64.pkg.tar.xz`, but then I couldn't even get `node` to run, since it seems to rely at some other library that as also been updated. The error given is:
`node: error while loading shared libraries: libicui18n.so.59: cannot open shared`

For the time being some of my projects will have to be developed on Windows (since I can use Node.js 8.9.1 LTS just fine there). I hope you guys get around to fixing it soon though.

**Comment by k2s** [comment]
@telmotrooper I am also developping under ArchLinux. I am using https://github.com/creationix/nvm (it exists also in AUR). That way I have full controll what nodejs version I am using depending on project.

**Comment by telmotrooper** [comment]
@k2s I'll give it a try when I get home, thanks!

**Comment by telmotrooper** [comment]
Just wanted to let you guys now, the method suggested by @k2s works really well and it's quite easy to do. Just installed nvm with `curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.6/install.sh | bash`, then `nvm install 8.9.1` and `nvm install 9.2.0` to get both versions, and did `nvm use 8` to use 8.9.1. Then I could run `npm install` just fine in my project that uses node-sqlite3.

**Comment by Dzieni** [comment]
Actually, there is an issue during the module compilation on Node v9.2:

```
In file included from /Users/michald/.node-gyp/9.2.0/include/node/node.h:63:
/Users/michald/.node-gyp/9.2.0/include/node/v8.h:208:5: error: assigning to 'v8::Context *volatile' from incompatible type 'v8::String *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/michald/.node-gyp/9.2.0/include/node/v8.h:162:37: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../src/database.cc:133:27: note: in instantiation of function template specialization 'v8::Local<v8::Context>::Local<v8::String>' requested here
    info.This()->ForceSet(Nan::New("filename").ToLocalChecked(), info[0].As<String>(), ReadOnly);
                          ^
```

**Comment by mah3uz** [comment]
Same problem here, any chance to get the solution for build <v7.x Nodejs

**Comment by Punknoodles** [comment]
Still happening to me too...

```
node-pre-gyp ERR! Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.12/node-v59-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for sqlite3@3.1.12 and node@9.2.0 (node-v59 ABI) (falling back to source compile with node-gyp)
```

**Comment by Punknoodles** [comment]
Fixed it by using NVM to switch between node versions... anything prior to 9.0.0 seems to work for me.

**Comment by eMerzh** [comment]
Same thing with node 9.4.0 here on osx

**Comment by k1r0s** [comment]
Just came acros this issue, no pressure! :+1:

**Comment by daniellockyer** [comment]
Would you be able to try with v5.0.3 please? 🙂
