### ISSUE TITLE
node-webkit win64 prebuilt binaries here

### ISSUE THREAD

**Issue by sclem** [TryGhost/node-sqlite3#905]
I read in the wiki to post links to prebuilt binaries here to be added to the s3 repo.

Here are recent node-webkit-win32-x64 builds, I'll continue to update them as long as I'm using this package as well and there's interest:

https://github.com/sclem/node-sqlite3-prebuilt/releases

**Comment by 10mitri** [comment]
Thank you for this. Could you please make the same for win32 ?

**Comment by daniellockyer** [comment]
I don't think this is needed anymore as we use Node-API in v5+ 🙂
