### ISSUE TITLE
Get vs All

### ISSUE THREAD

**Issue by Dragas** [TryGhost/node-sqlite3#930]
Lately I've come to an issue where due to lack of awareness and reading comprehension people in general call `Database.prototype.get`  instead of `Database.prototype.all` when they want to get all results for particular query. I suggest that `get` would be deprecated and renamed to `Database.prototype.first` to avoid this misconception.

**Comment by daniellockyer** [comment]
Whilst I'd agree it'd make the library a little better to use, it's unlikely something we're going to do soon so I'm going to close this for now 🙂
