### ISSUE TITLE
Poor query performance with a rather small table

### ISSUE THREAD

**Issue by tensleep** [TryGhost/node-sqlite3#934]
Hello,

I'm somewhat new to Node, and as such, would love nothing more than to be told that I'm doing something wrong here, but I do have a pretty tiny test case that demonstrates the problem. I'd be happy to post the exact schemas, data and test programs here as well, but I don't know if that's actually welcome, so I'll only do that if told to.

To summarize, I have a small table -- 11 columns and just 58 rows -- in a sqlite3 db file that takes up just 14336 bytes on disk. The two columns being searched in the query are both 4-character strings, and there's an index created on the pair (in the same order as the query). The rest of the columns are either integers or 4-8 character strings.

My test program simply queries for every row from this table, using `Sqlite3.get('SELECT rowid,* FROM test_table WHERE foo = ? AND bar = ?', foo, bar, (row) => { ... }`, repeatedly, and in the same order on each iteration. For just 1,000 iterations (so 58,000 total queries), this program consistently takes over 4.8 seconds to complete, and 4.78s of that is user CPU time (110-115% CPU usage).

Even more interestingly, that's only if I call `serialize()` upon opening the DB -- without that, it takes almost ten *minutes*, almost all of which is also user CPU time! (And, unlike with `serialize()`, it records exactly 100% of CPU time, not 110%+.)

For a comparison, I translated the test program as closely to verbatim as possible to Perl, using the DBD::SQLite library from that world, and it completes the same 1,000 iterations in ~2.7 seconds. (Still not quite what I expected, but already an improvement over the Node version.)

Just for a control case, I made a second version of the Node test that loads the entire table into memory -- the same query, but without the `WHERE`, loaded into a two-level table using Sqlite3.each() and then simply looked up like `table[foo][bar]` and that completes in 100 milliseconds or so, including the initial query and the same 1,000 iterations; a million iterations take 5 seconds.

So, that about sums it up. While I'm a little surprised that either SQL query is taking *that* much longer than the control, it's perhaps even more surprising that the Node version is over 75% slower than the equivalent Perl code. And of course, the really bad performance without `serialize()` is just totally baffling (the same thing happens if I call `serialize()` followed by `parallelize()`, for what it's worth).

Versions are:
npm- sqlite3@3.1.13
node- v9.4.0
sqlite3 from Ubuntu 16.04: 3.11.0 2016-02-15 17:29:24 3d862f207e3adc00f78066799ac5a8c282430a5f

Thanks for reading, I apologize if I've overlooked anything obvious.

**Comment by wmertens** [comment]
* The architectural underpinnings of this module assume that sqlite can do parallel queries on a single connection; it cannot. `parallellize()` just adds a lot of bookkeeping for no benefit.
* It won't make much of a difference, but try doing the queries on a `:memory:` database. Just `.dump` your disk table and load it at program start. I would be interested in the results.

You should be able to get much better speed with the https://github.com/JoshuaWise/better-sqlite3 module - it is completely synchronous and thus doesn't have to do a lot of copying and locking. On the sad side, it will block your main thread. Sqlite is very fast, but on larger datasets you can still do things that take seconds. See https://github.com/JoshuaWise/better-sqlite3/issues/32 for the reasoning there.

I'm looking for a middle road option, having this module support synchronous calls. There's a PR, #523, but it is stalled.

**Comment by daniellockyer** [comment]
I am working on synchronous functions for this library, but this issue is 4 years old so I'm closing it for now 🙂
