### ISSUE TITLE
Google Function: Deployment error. Error in the build environment

### ISSUE THREAD

**Issue by khailenkomaksym** [TryGhost/node-sqlite3#937]
I'm using Google Function and sqlite3 module. It was all good, but from yesterday when I try to deploy my functions I getting error: "Deployment error. Error in the build environment".  I have tried to remove dependency "sqlite3": "^3.1.13" from package.json and now it's good. But why it's failed with using module sqlite3?

**Comment by daniellockyer** [comment]
Would you be able to try with v5.0.3? 🙂
