### ISSUE TITLE
How to use latest version of sqlite

### ISSUE THREAD

**Issue by Rahulkr2** [TryGhost/node-sqlite3#940]
I have build and run electron app with node-sqlite3 successfully using electron-rebuild.
But the default SQLite version is 3.15.0, I would like to use the latest version i.e 3.22.0.
Kindly give me step by step instructions to do so.

**I'm new to programming so please forgive my ignorance.**
Thanks

**Comment by daniellockyer** [comment]
v5.0.3 now ships with SQLite v3.38.2 🙂
