### ISSUE TITLE
Inconsistent output in some queries

### ISSUE THREAD

**Issue by dtgoitia** [TryGhost/node-sqlite3#945]
## Inconsistent output in JOINs

I have create and populated the following tables:

* **`applications`** table:

  | id | name               | description                   |
  |:--:|:-------------------|:------------------------------|
  | 1  | application name   | application description       |
  | 2  | application 2 name | small application description |

* **`tags`** table:

  | id | name |
  |:--:|:----:|
  | 1  | tax  |
  | 2  | car  |

* **`applications_tags`** table:

  | application_id | tag_id |
  |:--------------:|:------:|
  |       1        |   1    |
  |       1        |   2    |
  |       2        |   1    |

```javascript
// Create tables
db.run(`
  CREATE TABLE IF NOT EXISTS applications (
    id INTEGER PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT
  )`, errorHandlingCallBack)
  .run(`
  CREATE TABLE IF NOT EXISTS tags (
    id INTEGER PRIMARY KEY,
    name TEXT NOT NULL
  )`, errorHandlingCallBack)
  .run(`
  CREATE TABLE IF NOT EXISTS applications_tags (
    id INTEGER PRIMARY KEY,
    application_id INTEGER NOT NULL,
    tag_id INTEGER NOT NULL
  )`, errorHandlingCallBack);

// Populate tables
db.run(`
  INSERT INTO applications
    (name,description)
  VALUES
    ("application name",   "application description"),
    ("application 2 name", "small application description")
  `, errorHandlingCallBack)
.run(`
  INSERT INTO tags
    (name)
  VALUES
    ("tax"),
    ("car")
  `, errorHandlingCallBack)
.run(`
  INSERT INTO applications_tags
    (application_id, tag_id)
  VALUES
    (1, 1),
    (1, 2),
    (2, 1)
  `, errorHandlingCallBack)

// ... more code

db.close(errorHandlingCallBack);
```
Then I run this query:
```javascript
db.all(`
  SELECT a.description, t.name
  FROM applications a
  JOIN applications_tags at
    ON a.id = at.application_id
  JOIN tags t
    ON at.tag_id = t.id
`, function (err, tables) {
  console.log(JSON.stringify(tables, null, 2));
});
```
which returns me the following array:
```json
[{
  "description": "application description",
  "name": "tax"
},
{
  "description": "application description",
  "name": "car"
},
{
  "description": "small application description",
  "name": "tax"
}]
```
Until this point, everything runs as expected. However, if I change the query from `SELECT a.description, t.name` to `SELECT a.name, t.name`, it doesn't return the `a.name`, I only get the `t.name`:
```json
[{
  "name": "tax"
},
{
  "name": "car"
},
{
  "name": "tax"
}]
```
Where are my `a.name`? Is there any mapping conflict?

EDIT:
This unexpected behaviour happens with this query as well:
```javascript
db.all(`
  SELECT
    a.description,
    t.name
  FROM
    applications a,
    applications_tags at,
    tags t
  WHERE a.id = at.application_id
  AND at.tag_id = t.id
`, function (err, tables) {
  console.log(JSON.stringify(tables, null, 2));
});
```

**Comment by daniellockyer** [comment]
I believe the answer above is correct so I'm going to close this 🙂
