### ISSUE TITLE
Using <placeholder> instead of $<placeholder> in params will allow for deconstructing

### ISSUE THREAD

**Issue by willowiscool** [TryGhost/node-sqlite3#957]
Deconstructing is a recent feature that turns `{id: id, name: name}` into `{id, name}`. The problem here is that if you do something like

```js
db.run("INSERT INTO table (text, anothertext, textthree) VALUES ($text, $texttwo, $textthree)", 
{$text: text, $texttwo: texttwo, $textthree: textthree})
```

you're forced to use the older method, which becomes increasingly bothersome as you add more inputs. I suggest letting you use the name of the placeholder without the dollar sign (or colon, or whatever else) to make something like the following possible:

```js
db.run("INSERT INTO table (text, anothertext, textthree) VALUES ($text, $texttwo, $textthree)", 
{text, texttwo, textthree})
```

**Comment by daniellockyer** [comment]
Whilst I understand the desire for this, this is unfortunately how SQLite works with binding parameters: https://www.sqlite.org/c3ref/bind_blob.html
