### ISSUE TITLE
Feature Request - Expose an option to set SQLITE_FCNTL_CHUNK_SIZE

### ISSUE THREAD

**Issue by trevershick** [TryGhost/node-sqlite3#980]
Our C code uses this option to set a 'larger than default' chunk size to help with fragmentation.  However, our Node code is unable to take advantage of this feature.

There is already a `db.configure('busyTimeout', 1000)` feature it would be great if we could `db.configure('chunkSize', 1024*1024)`.

see https://sqlite.org/c3ref/c_fcntl_chunk_size.html
ref (about fragmentation https://stackoverflow.com/questions/13393866/sqlite-wal-performance-improvement)

**Comment by daniellockyer** [comment]
@trevershick Is this still something that is desired? 🙂

**Comment by trevershick** [comment]
> @trevershick Is this still something that is desired? 🙂

I think it's useful but no this is no longer something that's immediately desired.
