### ISSUE TITLE
Is it possible to get full parameterized query back?

### ISSUE THREAD

**Issue by Nostradamos** [TryGhost/node-sqlite3#988]
For example i run my query like this:
```
let query = db.run('SELECT * FROM foo WHERE bar = ?', ['xyz'], (err) => {
   ....
});
```

Is it possible to somehow get back the full query? So i want to get back the full `SELECT * FROM foo WHERE bar = 'xyz'` query.

**Comment by daniellockyer** [comment]
Unfortunately I don't think it is, but happy to accept a PR if someone finds out how 🙂
