### ISSUE TITLE
 Error: SQLITE_RANGE: bind or column index out of range on prepare statement

### ISSUE THREAD

**Issue by Codhex** [TryGhost/node-sqlite3#999]
Hello, i've this type of code
``      
       let res = []
        let query = 'SELECT ? FROM EvtAttr WHERE ? LIKE ? limit ?';
        connection.each(query, [field, field, value, limit], (err, row) => {
            res.push(row[field]);
        });
        return res;
``
connection is my database object connection. 
With the debugger, i see the length of res is equal to 0. Node JS read the line "connection.each..." but, Node JS execute return res and go into the loop.
Thx for reading this. :)

**Comment by Codhex** [comment]
Ok, the code have changed but i've this error:
Error: SQLITE_RANGE: bind or column index out of range

corresponding to this:
``
       let stmt = connection.prepare('SELECT $field FROM EvtAttr WHERE $field LIKE " $value " limit $limit');
        const params = {
            $field: field,
            $value: value,
            $limit: limit
        }
        stmt.each(params, (err, row) => {
            res.push(row[field]);
        });
``
the values are defined. Do you see the problem ?

Thx for reading.

**Comment by UFBin** [comment]
Got the same issue, Node.js 10.15.3, sqlite@3.0.3.


    TEST() {

        let sqlRequest = "SELECT * FROM TRecords WHERE TargetDate='$month/$day/$year'";
        let sqlParams = { 
            $year: '2015',
            $month: '03',
            $day: '01'
        };        

        return new Promise(function (resolve, reject) {
            database.db.all(sqlRequest, sqlParams, (err, rows) => {
                if (err) {
                    console.log(err);
                    reject();
                }
                resolve(rows);
            });
        });
        
    }

When I run this function, I got error like this:
`
{ [Error: SQLITE_RANGE: colum index out of range] errno: 25, code: 'SQLITE_RANGE' }
`



Then I tried to write SQL statement myself:
`
let sqlRequest = "SELECT * FROM TRecords WHERE TargetDate='03/01/2015'";
`
and delete the params:
`
database.db.all(sqlRequest, (err, rows) => {
`
and it works.
I don't know if this is an issue or if there is something wrong with my code, hope someone could help me.

**Comment by lamontadams** [comment]
I'm seeing this error executing a query with no where clause, just a LIMIT when running against a table that doesn't have any rows:
```SELECT * FROM [config] LIMIT 1;```

**Comment by jaredkrinke** [comment]
Couple of observations:

1. Parameters are automatically quoted and escaped as needed, so don't put quotes around e.g. $stringParam -- if you do, you can get the SQLITE_RANGE error
2. If your parameter array has the wrong number of parameters (or the wrong names), you will also get the SQLITE_RANGE error

The following code works for me (note: no quotes around $string):

    var sqlite3 = require('sqlite3');
    var db = new sqlite3.Database(":memory:");
    db.run("CREATE TABLE Test (Number INTEGER, String VARCHAR(10))", function (err) {
        if (err === null) {
            db.run("INSERT INTO Test (Number, String) VALUES ($number, $string)", {
                $number: 5,
                $string: "foo",
            })
        }
    });

The second command is executed as:

> INSERT INTO Test (Number, String) VALUES (5, 'foo')

**Comment by Apro123** [comment]
I got this issue but it just turns out that I had a value in the args field but no "?" in the sql.
Hope this helps someone

**Comment by JJosephttg** [comment]
For me this is not the case. I am not surrounding quotes or having the incorrect amounts of parameters for mine and I am still running into this issue in my project.

Output of what my SQL looks like in one string:
```
BEGIN TRANSACTION; 
INSERT INTO App (AppName,AppPath,LaunchArgs,ImgSrc,IsFavorite,CategoryId)
SELECT $appName,$appPath,$launchArgs,$imgSrc,$isFavorite,Id FROM Category WHERE CategoryName = $categoryName; COMMIT;
```
My parameters:
```
sqlParams = {
                $appName: app.AppName,
                $appPath: app.AppPath,
                $launchArgs: app.LaunchArgs,
                $imgSrc: app.ImgSrc,
                $isFavorite: app.IsFavorite,
                $categoryName: app.CategoryName
        };
```
```
    CREATE TABLE IF NOT EXISTS App (
        "Id"            INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
        "AppName"       VARCHAR(200) NOT NULL UNIQUE,
        "AppPath"       TEXT NOT NULL,
        "CategoryId"	INTEGER,
        "LaunchArgs"    TEXT,
        "ImgSrc"	    BLOB,
        "IsFavorite"    INTEGER NOT NULL DEFAULT 0 CHECK(IsFavorite IN (0,1))
    );
    
    CREATE TABLE IF NOT EXISTS Category (
        "Id"           INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
        "CategoryName" TEXT NOT NULL
    )
```

I am honestly clueless why this doesn't work. If I eventually find a solution I will update and let you know why. All of the variables have values too.

**Comment by daniellockyer** [comment]
Closing as the issue is stale and I think everyone has solved their problem. Please open a new issue with a reproducible example if you're still encountering something 🙂
